//! Differential conformance harness — shared module root.
//!
//! This module is the foundation of the differential conformance suite driven by
//! `tests/conformance.rs`. It declares the eleven sibling harness modules, owns the
//! entire shared vocabulary (target, optimization level, oracle identity, divergence
//! class, verdict, cell, outcome, error), owns the canonical command-line flag tables
//! that keep `compile.rs` and `flagprobe.rs` from drifting apart, and owns the path
//! roots from which every filesystem location the suite touches is derived.
//!
//! # The three oracles
//!
//! The suite compiles and executes a hand-authored corpus of self-contained C programs
//! and judges bcc's observable behaviour — stdout bytes and exit status, nothing else —
//! against three mutually independent oracles:
//!
//! - Oracle (a), reference compiler: bcc versus an external reference C compiler, same
//!   target and same optimization level. Detects a wrong answer that bcc produces
//!   consistently across all four of its backends.
//! - Oracle (b), cross backend: every non-baseline target versus the x86-64 baseline at
//!   the same optimization level. Detects a wrong answer confined to a single backend,
//!   which is where ABI, register-allocation and instruction-selection defects surface.
//! - Oracle (c), golden record: every cell versus the `expected_stdout` recorded in the
//!   program's own `.expected` file. Catches the single failure mode that pure
//!   differential testing structurally cannot detect — both compilers changing behaviour
//!   in the same direction at the same time, which oracle (a) still reports as agreement.
//!
//! Standard error is captured for finding artifacts but is never compared: diagnostic
//! wording legitimately differs between compilers, and comparing it would produce a
//! flood of divergences that say nothing about code correctness.
//!
//! # Structural invariants
//!
//! - **Pure standard library.** The project forbids third-party crates absolutely and
//!   admits no exceptions, so every module here is written against `std` alone: no
//!   serialization crate, no process-assertion crate, no temporary-directory crate, no
//!   snapshot crate, no dynamic-test-case crate.
//! - **No test functions live in this directory.** Every test of the suite lives in
//!   `tests/conformance.rs`; these modules are pure infrastructure and add nothing to the
//!   repository's test count. That is what keeps the documented suite-health numbers
//!   intact, including the invariant count of thirteen ignored tests, which is the most
//!   direct mechanical check that no existing test was skipped or weakened.
//! - **This directory must never contain a `main.rs`.** Cargo turns `tests/<dir>/main.rs`
//!   into an integration-test target; a nested directory holding neither a `main.rs` nor
//!   any target entry point is never a target, so it may hold shared helper modules.
//!   That single fact is why the suite requires no package-manifest change at all, and
//!   needing one would mean the layout had been implemented incorrectly.
//! - **The shared vocabulary is defined at this module root**, not in a nested types
//!   module that would then have to be re-exported, so the driver writes
//!   `conformance_harness::Verdict` and `conformance_harness::Outcome` directly and its
//!   call sites stay short. A `pub use self::…` line re-exporting items that are already
//!   defined here would be redundant and would raise an unused-import warning, which the
//!   project's zero-warning gate escalates to an error; the submodule surface is
//!   re-exported by the `pub mod` declarations below, so `conformance_harness::compile`
//!   and friends resolve as well.
//! - **Parallel safety by construction, not by locking.** `cargo test` runs tests
//!   concurrently by default, so shared mutable resources are eliminated rather than
//!   guarded: every cell owns a workspace whose path is a pure function of its identity
//!   (see [`CellKey::slug`]), and every feature area writes only its own report file.
//!
//! # Artifact path contract
//!
//! Shared with the driver, the repository ignore rules and the continuous-integration
//! job. Everything the suite writes lives beneath the Cargo build directory, and nothing
//! is ever written outside it:
//!
//! - `target/conformance-work/<cell-slug>/` — one hermetic workspace per compile-and-run
//!   cell, removed on success and retained on failure so a failing cell leaves behind
//!   exactly the artifacts needed to investigate it.
//! - `target/conformance-report/areas/<area>.md` and `.tsv` — per-area reports, one file
//!   per area so concurrent areas never contend, plus `summary.md` and `summary.tsv` for
//!   the run as a whole.
//! - `target/conformance-findings/F-NNNN-<slug>/` — findings generated by the current
//!   run.
//!
//! The curated, committed finding set under `tests/conformance/findings/` is a
//! deliverable and is never written by a test run.
//!
//! # Compatibility
//!
//! Edition 2021, minimum supported Rust 1.70. No standard-library API newer than 1.70 is
//! used anywhere in this module.

pub mod classify;
pub mod compare;
pub mod compile;
pub mod env;
pub mod execute;
pub mod findings;
pub mod flagprobe;
pub mod manifest;
pub mod report;
pub mod sandbox;
pub mod ubaudit;

use std::fmt;
use std::path::{Path, PathBuf};

// ---------------------------------------------------------------------------
// Coverage matrix
// ---------------------------------------------------------------------------
//
// Coverage for this suite is stated as an enumerable matrix rather than a ratio.
// Instrumenting line coverage would require a development dependency, which the project
// forbids absolutely, so no ratio published here could be verified by anyone working in
// this repository. Every number below is instead countable directly from the committed
// file set and is re-reported by `report.rs` on every run, which makes the run summary
// the suite's coverage evidence.

/// Number of feature-area directories in the corpus: the nine areas the requirements
/// mandate plus five supplementary areas carrying the widest cross-backend divergence
/// surface.
pub const AREA_COUNT: usize = 14;

/// Total number of C programs in the corpus, one semantic concern per program.
pub const PROGRAM_COUNT: usize = 108;

/// Number of optimization levels swept per program. Exactly the levels both compilers
/// honour with the same meaning.
pub const OPT_LEVEL_COUNT: usize = OptLevel::ALL.len();

/// Number of target architectures swept per program, unless a program restricts its own
/// target list and records the reason for the restriction.
pub const TARGET_COUNT: usize = Target::ALL.len();

/// Compile-and-run cells executed with bcc: every program, on every target, at every
/// optimization level.
pub const BCC_CELL_COUNT: usize = PROGRAM_COUNT * TARGET_COUNT * OPT_LEVEL_COUNT;

/// Reference-compiler cells on the native target, using the native driver.
pub const REFERENCE_NATIVE_CELL_COUNT: usize = PROGRAM_COUNT * OPT_LEVEL_COUNT;

/// Reference-compiler cells on the three non-native targets, using the matching cross
/// drivers. An upper bound: a cross driver that is absent from the environment degrades
/// its arm of oracle (a) to [`Verdict::Unavailable`] rather than silently vanishing.
pub const REFERENCE_CROSS_CELL_COUNT_MAX: usize =
    PROGRAM_COUNT * OPT_LEVEL_COUNT * (TARGET_COUNT - 1);

/// Oracle (a) comparisons: one per bcc cell that has a same-target reference cell to be
/// compared against.
pub const ORACLE_A_COMPARISON_COUNT: usize =
    REFERENCE_NATIVE_CELL_COUNT + REFERENCE_CROSS_CELL_COUNT_MAX;

/// Oracle (b) comparisons: every non-baseline target against the baseline, per program
/// per optimization level.
pub const ORACLE_B_COMPARISON_COUNT: usize = PROGRAM_COUNT * OPT_LEVEL_COUNT * (TARGET_COUNT - 1);

/// Oracle (c) assertions: one golden-record assertion per bcc cell.
pub const ORACLE_C_ASSERTION_COUNT: usize = BCC_CELL_COUNT;

/// Total differential and golden assertions the full matrix performs.
pub const TOTAL_ASSERTION_COUNT: usize =
    ORACLE_A_COMPARISON_COUNT + ORACLE_B_COMPARISON_COUNT + ORACLE_C_ASSERTION_COUNT;

/// Floor on the number of programs in a mandated feature area. Supplementary areas carry
/// no floor; `report.rs` applies this bound only where `AreaSpec::mandated` holds.
pub const MIN_PROGRAMS_PER_MANDATED_AREA: usize = 6;

/// One feature area of the corpus: its directory name, how many programs it is expected
/// to contain, and whether the requirements mandate it or it is supplementary.
///
/// The table is authoritative and read-only, which is why no public constructor is
/// offered: `report.rs` and the driver look an area up by directory name with
/// [`AreaSpec::lookup`] and read the fields.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct AreaSpec {
    /// Directory name beneath [`corpus_root`], for example `04_bitfields`. Also the stem
    /// of the area's report files and the suffix of the driver's area test name.
    pub directory: &'static str,
    /// Number of programs the area is expected to contain. A discovered count that
    /// disagrees with this number is a corpus defect, never something to paper over.
    pub program_count: usize,
    /// True when the requirements name the area explicitly, false when it is one of the
    /// five supplementary areas added for cross-backend divergence surface.
    pub mandated: bool,
}

impl AreaSpec {
    /// Private table constructor, used only to build [`AREAS`].
    const fn new(directory: &'static str, program_count: usize, mandated: bool) -> AreaSpec {
        AreaSpec {
            directory,
            program_count,
            mandated,
        }
    }

    /// Look an area up by its directory name, trimming surrounding whitespace.
    ///
    /// Returns `None` for a directory that is not part of the corpus, which the caller
    /// must treat as a corpus defect and report loudly rather than skip.
    pub fn lookup(directory: &str) -> Option<&'static AreaSpec> {
        let wanted = directory.trim();
        AREAS.iter().find(|area| area.directory == wanted)
    }
}

impl fmt::Display for AreaSpec {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let kind = if self.mandated {
            "mandated"
        } else {
            "supplementary"
        };
        write!(
            f,
            "{} ({} programs, {})",
            self.directory, self.program_count, kind
        )
    }
}

/// The fourteen feature areas in numeric order, with the program count each is expected
/// to contain. The counts sum to [`PROGRAM_COUNT`].
///
/// `report.rs` iterates this table to finalize the run summary once every area report
/// exists, and the driver iterates it to dispatch its area tests.
pub const AREAS: [AreaSpec; AREA_COUNT] = [
    AreaSpec::new("01_integer_conversions", 10, true),
    AreaSpec::new("02_constant_expressions", 8, true),
    AreaSpec::new("03_initializers", 11, true),
    AreaSpec::new("04_bitfields", 7, true),
    AreaSpec::new("05_pointers", 10, true),
    AreaSpec::new("06_control_flow", 10, true),
    AreaSpec::new("07_variadics", 6, true),
    AreaSpec::new("08_gcc_extensions", 8, true),
    AreaSpec::new("09_optimization_levels", 8, true),
    AreaSpec::new("10_declarations_and_types", 10, false),
    AreaSpec::new("11_literals_and_strings", 4, false),
    AreaSpec::new("12_preprocessor", 6, false),
    AreaSpec::new("13_floating_point", 4, false),
    AreaSpec::new("14_abi_calling_convention", 6, false),
];

// ---------------------------------------------------------------------------
// Canonical flag tables
// ---------------------------------------------------------------------------
//
// The requirement these tables serve is "only pass command-line flags that both
// compilers honour with the same meaning, and verify flag handling rather than assuming
// it". `compile.rs` ENFORCES the tables when it builds an argument vector and
// `flagprobe.rs` VERIFIES them by compiling a purpose-built program with both compilers
// and asserting an observable consequence of each flag. Defining the tables exactly once,
// here, is what stops the enforcer and the verifier from drifting apart.
//
// The discipline constrains oracle (a) only. Oracle (b) is bcc against bcc, so a bcc-only
// target-selection flag trivially satisfies "both compilers honour it with the same
// meaning" there, because both sides are the same compiler. That distinction is
// load-bearing: without it, cross-backend testing would be impossible, since selecting a
// target is precisely what oracle (b) requires.

/// Flags measured to be accepted by both compilers with identical meaning, and therefore
/// the outer envelope within which maintenance of the differential invocations may move.
///
/// `flagprobe.rs` iterates this set and asserts an observable consequence per flag rather
/// than mere acceptance — the output file appears at the requested path, the object-versus
/// -executable ELF type field changes, the interpreter program header disappears under
/// static linking, a debug section appears, a macro's printed value changes, and so on.
/// Acceptance alone is not verification: two compilers can accept the same spelling and
/// mean different things by it, which is exactly why `-fcf-protection` is excluded below
/// despite both compilers taking it.
///
/// `-L` and `-l` are verified for acceptance only. Verifying them semantically would need
/// an archive-creation tool, which lies outside the no-new-dependency envelope and is
/// unnecessary because the corpus links nothing but the C runtime, which is linked by
/// default. That limitation is stated rather than glossed over.
pub const SHARED_FLAGS_VERIFIED: &[&str] = &[
    "-o", "-c", "-O0", "-O1", "-O2", "-I", "-D", "-U", "-L", "-l", "-g", "-static", "-fPIC",
];

/// The deliberately minimal flag set actually used in a differential invocation: the
/// output path, static linkage, and exactly one optimization level from
/// [`OptLevel::flag`].
///
/// Everything else in [`SHARED_FLAGS_VERIFIED`] is verified so that maintenance has a
/// proven envelope to work within, not because the suite currently needs it. Static
/// linkage is not a stylistic choice: it is the one linkage mode both compilers spell
/// identically, and it is what lets emulated execution work with no sysroot and no
/// dynamic-loader configuration on any of the four targets.
pub const DIFFERENTIAL_FLAGS_MINIMAL: &[&str] = &["-o", "-static"];

/// Flags that must never appear in a differential invocation, asserted negatively by
/// `flagprobe.rs` so that a maintenance edit cannot quietly reintroduce one.
///
/// The first eighteen entries are reference-compiler-only or have divergent defaults; the
/// final two are bcc-only target-selection spellings that are legitimate inside oracle (b)
/// and nowhere else. Reasons, in table order:
///
/// - `-O3`, `-Os` — bcc documents no support; only `-O0`, `-O1` and `-O2` are in scope.
/// - `-std=` — bcc has no such flag at all, and the reference compiler's default mode was
///   measured as gnu17, which already enables the GNU extensions the corpus exercises.
///   Passing a standard selector to one side and not the other would compare two
///   different languages.
/// - `-pedantic`, `-Wall`, `-Wextra`, `-Werror` — diagnostic control belongs exclusively
///   to the undefined-behaviour audit gate in `ubaudit.rs`, which drives the reference
///   compiler only and never bcc.
/// - `-m32` — measured to fail on the reference host because the multilib start files are
///   absent. i686 coverage comes from the dedicated i686 cross driver, which is also the
///   correct choice for parity because it matches the per-target driver pattern used for
///   AArch64 and RISC-V 64.
/// - `-S`, `-E` — stopping the pipeline before a runnable artifact exists makes every
///   oracle in the suite inapplicable, because all three compare the behaviour of a
///   program that ran.
/// - `-fwrapv`, `-fno-strict-aliasing` — these redefine the language the corpus is
///   written in. The corpus is undefined-behaviour-free by construction and machine-
///   audited to be so, so neither flag can change a correct program's meaning, and
///   passing them would obscure that guarantee.
/// - `-fsanitize=` — sanitizers are documented as unsupported by bcc, and they belong
///   exclusively to the audit gate, where they judge the test program rather than the
///   compiler.
/// - `-fno-builtin`, `-ffreestanding`, `-nostdlib` — these change which runtime and which
///   builtin set the program is compiled against, and the two compilers do not agree on
///   the consequences.
/// - `-mretpoline` — a bcc-only hardening spelling with no reference-compiler equivalent
///   of the same scope.
/// - `-fcf-protection` — accepted by BOTH compilers, yet excluded, because their default
///   scopes differ. This is the entry that proves verification had to be semantic rather
///   than syntactic: acceptance alone would have been a false positive.
/// - `--target`, `--sysroot` — bcc-only. The reference compiler has no target-selection
///   flag; the `--target=` spelling belongs to a different compiler family and was
///   measured to be rejected. Oracle (a)'s cross arm therefore uses the matching cross
///   driver binary, while oracle (b) legitimately passes `--target` to both of its sides
///   because both sides are bcc.
pub const FORBIDDEN_IN_DIFFERENTIAL: &[&str] = &[
    "-O3",
    "-Os",
    "-std=",
    "-pedantic",
    "-Wall",
    "-Wextra",
    "-Werror",
    "-m32",
    "-S",
    "-E",
    "-fwrapv",
    "-fno-strict-aliasing",
    "-fsanitize=",
    "-fno-builtin",
    "-ffreestanding",
    "-nostdlib",
    "-mretpoline",
    "-fcf-protection",
    "--target",
    "--sysroot",
];

/// True when `flag` must not appear in a differential (oracle (a)) invocation.
///
/// Three matching forms are recognised, so that a guard placed on an argument vector
/// cannot be defeated by a spelling variant:
///
/// - exact match, which covers `-O3`, `-Wall`, `-static` and the rest of the plain forms;
/// - prefix match for the two table entries that end in `=`, namely `-std=` and
///   `-fsanitize=`, which never appear without a value;
/// - `<entry>=<value>` for every other entry, which catches `--target=aarch64-linux-gnu`
///   and `-fcf-protection=full` as surely as their space-separated spellings.
///
/// The value form is checked explicitly rather than by a bare prefix test, so that
/// legitimate flags are not swept up by accident: `-static` is not rejected because it
/// happens to begin with `-S`, and `-O0` is not rejected because it resembles `-O3`.
///
/// `compile.rs` calls this on every argument it is about to pass to either compiler, and
/// `flagprobe.rs` calls it to assert the set negatively.
pub fn is_forbidden_in_differential(flag: &str) -> bool {
    let candidate = flag.trim();
    FORBIDDEN_IN_DIFFERENTIAL.iter().any(|entry| {
        if entry.ends_with('=') {
            return candidate.starts_with(entry);
        }
        if candidate == *entry {
            return true;
        }
        match candidate.strip_prefix(entry) {
            Some(remainder) => remainder.starts_with('='),
            None => false,
        }
    })
}

// ---------------------------------------------------------------------------
// Target architecture
// ---------------------------------------------------------------------------

/// One of the four target architectures bcc supports.
///
/// The triple spellings, pointer widths, `long` widths, ELF classes and endianness below
/// are the repository's own authoritative target table, not this suite's invention, and
/// the ELF class in particular encodes the documented rule that i686 output is ELF32
/// while the other three targets are ELF64.
///
/// # Measured implementation-defined properties
///
/// Three properties genuinely differ across these targets and were measured rather than
/// assumed. They are recorded here as documentation and report material only; no logic in
/// this harness branches on them, because a divergence caused by an implementation-defined
/// difference is not a compiler defect and must be handled by how a test program is
/// written or by a per-oracle exclusion in that program's own expectation record:
///
/// - Plain `char` signedness: signed on x86-64 and i686, unsigned on AArch64 and
///   RISC-V 64. Corpus programs therefore use explicit `signed char` or `unsigned char`
///   and never print a value whose plain-`char` signedness matters.
/// - `sizeof(long)` and `sizeof(void *)`: four bytes on i686, eight on the other three.
///   Exposed by [`Target::long_width_bytes`] and [`Target::pointer_width_bytes`].
/// - `sizeof(long double)`: measured as sixteen, twelve, sixteen and sixteen bytes in
///   table order, an x87 eighty-bit format on the two x86 targets against IEEE binary128
///   elsewhere. This is the requirements' own implementation-defined carve-out, so the
///   `long double` program disables cross-backend value equality alone and stays fully
///   compared against its same-target reference.
///
/// Properties that were measured to be IDENTICAL on all four targets — bitfield layout,
/// size, alignment and byte image; arithmetic right shift of a negative value; integer
/// division truncating toward zero with a dividend-signed remainder; little-endian byte
/// order — need no restriction at all, so a cross-backend divergence in any of them is a
/// genuine finding rather than an expected difference.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Target {
    /// x86-64: the baseline for oracle (b) and, in the planned and continuous-integration
    /// environments, the host architecture.
    X86_64,
    /// i686: the only ELF32 target, and the only one whose `long` and pointer widths
    /// differ from the rest.
    I686,
    /// AArch64.
    Aarch64,
    /// RISC-V 64.
    Riscv64,
}

impl Target {
    /// Every target, in the repository's documented table order.
    ///
    /// The driver sweeps this array to build a program's cell matrix, and
    /// [`Target::parse`] searches it, which keeps the accepted spellings and the emitted
    /// spellings the same set by construction.
    pub const ALL: [Target; 4] = [
        Target::X86_64,
        Target::I686,
        Target::Aarch64,
        Target::Riscv64,
    ];

    /// The baseline every other target is compared against under oracle (b).
    ///
    /// x86-64 is chosen because it is the host architecture, so executing a baseline cell
    /// involves no emulator and therefore introduces no emulation-related variable into
    /// the comparison.
    pub const BASELINE: Target = Target::X86_64;

    /// The canonical target triple, exactly as the repository's target table spells it and
    /// exactly as bcc's target-selection flag expects it.
    pub fn triple(self) -> &'static str {
        match self {
            Target::X86_64 => "x86_64-linux-gnu",
            Target::I686 => "i686-linux-gnu",
            Target::Aarch64 => "aarch64-linux-gnu",
            Target::Riscv64 => "riscv64-linux-gnu",
        }
    }

    /// The stable short slug used in workspace paths, report rows and artifact filenames.
    ///
    /// This is deliberately NOT the name of the target's emulator: the i686 runner is
    /// spelled `qemu-i386`, never `qemu-i686`. Keeping the two concepts apart is why
    /// runner discovery lives in `env.rs` and this module exposes only the slug.
    pub fn short_name(self) -> &'static str {
        match self {
            Target::X86_64 => "x86_64",
            Target::I686 => "i686",
            Target::Aarch64 => "aarch64",
            Target::Riscv64 => "riscv64",
        }
    }

    /// ELF class of this target's output: 32 for i686, 64 for the other three.
    ///
    /// `flagprobe.rs` needs this to pick the right header layout when it reads an ELF
    /// identification field directly, which is how the flag probe verifies `-c`, `-static`
    /// and `-g` without depending on any binary-inspection tool being installed.
    pub fn elf_class(self) -> u8 {
        match self {
            Target::I686 => 32,
            Target::X86_64 | Target::Aarch64 | Target::Riscv64 => 64,
        }
    }

    /// Pointer width in bytes: four on i686, eight on the other three.
    ///
    /// Consumed by report legends and by the environment fingerprint written into every
    /// finding, so that a width-related divergence can be read off the artifact directly.
    pub fn pointer_width_bytes(self) -> u8 {
        match self {
            Target::I686 => 4,
            Target::X86_64 | Target::Aarch64 | Target::Riscv64 => 8,
        }
    }

    /// Width of `long` in bytes: four on i686, eight on the other three.
    ///
    /// Same consumers as [`Target::pointer_width_bytes`]. Corpus programs normalize this
    /// away with fixed-width types rather than relying on it.
    pub fn long_width_bytes(self) -> u8 {
        match self {
            Target::I686 => 4,
            Target::X86_64 | Target::Aarch64 | Target::Riscv64 => 8,
        }
    }

    /// True when this target's binaries execute directly on the host, with no emulator.
    ///
    /// The host architecture is read at run time rather than assumed, so the harness stays
    /// correct if it is ever run somewhere other than the planned x86-64 host. The
    /// mapping is written out explicitly because the standard library reports 32-bit x86
    /// as `x86`, not as `i686`.
    ///
    /// i686 is therefore reported as non-native on an x86-64 host even though such a host
    /// can usually execute 32-bit binaries. That is deliberate: the suite routes i686
    /// execution through its emulator exactly as it does AArch64 and RISC-V 64, which
    /// keeps the emulation variable uniform across all three non-baseline targets and
    /// leaves the baseline as the only emulator-free arm.
    pub fn is_native(self) -> bool {
        let host = std::env::consts::ARCH;
        match self {
            Target::X86_64 => host == "x86_64",
            Target::I686 => host == "x86",
            Target::Aarch64 => host == "aarch64",
            Target::Riscv64 => host == "riscv64",
        }
    }

    /// Parse a target from either its full triple or its short slug, ignoring surrounding
    /// whitespace.
    ///
    /// Both spellings are accepted because expectation records list targets in the short
    /// form (`targets = x86_64, i686, aarch64, riscv64`) while command templates and
    /// report rows use the triple. Returns `None` for anything else; the caller must
    /// treat an unrecognised target as a defect in the expectation record and say so,
    /// never drop the cell.
    pub fn parse(text: &str) -> Option<Target> {
        let wanted = text.trim();
        Target::ALL
            .iter()
            .copied()
            .find(|candidate| candidate.triple() == wanted || candidate.short_name() == wanted)
    }
}

impl fmt::Display for Target {
    /// `{}` renders the canonical triple.
    ///
    /// `{:#}` renders the full documented fact row — triple, pointer width, `long` width,
    /// ELF class, byte order, execution mode and baseline role — which is what report
    /// legends and finding environment fingerprints need.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if !f.alternate() {
            return f.write_str(self.triple());
        }
        let execution = if self.is_native() {
            "native execution"
        } else {
            "emulated execution"
        };
        let role = if *self == Target::BASELINE {
            "oracle_b baseline"
        } else {
            "compared against the oracle_b baseline"
        };
        write!(
            f,
            "{} (pointer {} bytes, long {} bytes, ELF{}, little-endian, {}, {})",
            self.triple(),
            self.pointer_width_bytes(),
            self.long_width_bytes(),
            self.elf_class(),
            execution,
            role,
        )
    }
}

impl std::str::FromStr for Target {
    type Err = HarnessError;

    /// Idiomatic entry point onto [`Target::parse`], for callers that want a `Result`
    /// carrying an explanatory error instead of a bare `None`.
    fn from_str(text: &str) -> Result<Target, HarnessError> {
        Target::parse(text).ok_or_else(|| {
            HarnessError::new(
                "parsing a target architecture",
                format!(
                    "{text:?} is not one of the four supported targets; expected a triple or short \
                     name from: {}",
                    joined_target_names()
                ),
            )
        })
    }
}

/// Every accepted target spelling, as one comma-separated line for diagnostics.
fn joined_target_names() -> String {
    let mut rendered = String::new();
    for target in Target::ALL {
        if !rendered.is_empty() {
            rendered.push_str(", ");
        }
        rendered.push_str(target.short_name());
        rendered.push_str(" / ");
        rendered.push_str(target.triple());
    }
    rendered
}

/// Render a list of static labels as one comma-separated line for diagnostics.
fn comma_separated(labels: &[&str]) -> String {
    labels.join(", ")
}

// ---------------------------------------------------------------------------
// Optimization level
// ---------------------------------------------------------------------------

/// An optimization level in the sweep.
///
/// The sweep is exactly these three levels and nothing else, because they are the only
/// levels the repository documents as in scope and therefore the only ones both compilers
/// honour with the same meaning. Levels above `-O2`, and size-directed levels, are
/// documented as out of scope, so no variant for them exists here — not even an unused
/// one, which would invite a maintainer to start passing one.
///
/// Sweeping the levels is what turns the suite into a semantic-preservation test. The
/// repository's existing optimization tests assert that folding, dead-code elimination and
/// common-subexpression elimination OCCUR, which is a property of the optimizer's
/// implementation; asserting that a program's output is byte-identical at every level is a
/// property of the optimizer's CORRECTNESS, and only the second can catch a
/// miscompilation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum OptLevel {
    /// No optimization.
    O0,
    /// Light optimization.
    O1,
    /// The highest level in scope.
    O2,
}

impl OptLevel {
    /// Every optimization level, in ascending order.
    ///
    /// The driver sweeps this array per program, and [`OptLevel::parse`] searches it.
    pub const ALL: [OptLevel; 3] = [OptLevel::O0, OptLevel::O1, OptLevel::O2];

    /// The command-line spelling, passed identically to bcc and to the reference compiler.
    pub fn flag(self) -> &'static str {
        match self {
            OptLevel::O0 => "-O0",
            OptLevel::O1 => "-O1",
            OptLevel::O2 => "-O2",
        }
    }

    /// The bare spelling used in workspace paths, report rows and artifact filenames,
    /// where a leading dash would be awkward.
    pub fn short(self) -> &'static str {
        match self {
            OptLevel::O0 => "O0",
            OptLevel::O1 => "O1",
            OptLevel::O2 => "O2",
        }
    }

    /// Parse an optimization level from either spelling, ignoring surrounding whitespace.
    ///
    /// Both are accepted because expectation records list the levels in flag form
    /// (`opt_levels = -O0, -O1, -O2`) while report rows and artifact names use the bare
    /// form.
    pub fn parse(text: &str) -> Option<OptLevel> {
        let wanted = text.trim();
        OptLevel::ALL
            .iter()
            .copied()
            .find(|candidate| candidate.flag() == wanted || candidate.short() == wanted)
    }
}

impl fmt::Display for OptLevel {
    /// Renders the command-line spelling, so a rendered level can be pasted straight into
    /// a reproduction command.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.flag())
    }
}

impl std::str::FromStr for OptLevel {
    type Err = HarnessError;

    fn from_str(text: &str) -> Result<OptLevel, HarnessError> {
        OptLevel::parse(text).ok_or_else(|| {
            HarnessError::new(
                "parsing an optimization level",
                format!(
                    "{text:?} is not an optimization level in scope; expected one of: {}",
                    comma_separated(&OptLevel::ALL.map(OptLevel::flag))
                ),
            )
        })
    }
}

// ---------------------------------------------------------------------------
// Oracle identity
// ---------------------------------------------------------------------------

/// Which of the three independent oracles produced a comparison.
///
/// Oracle identity is a first-class value rather than an implicit property of a call site
/// because an exclusion must be expressible narrowly, per oracle. That is what allows a
/// construct whose value legitimately differs between architectures to remain fully
/// compared against its same-target reference while being excluded from cross-backend
/// value equality alone — so a difficult feature is scoped, not dropped, and every
/// [`Outcome`] records which oracle spoke.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Oracle {
    /// Oracle (a). bcc versus an external reference C compiler, same target and same
    /// optimization level. Detects a wrong answer that bcc produces consistently across
    /// all four of its backends, which no amount of self-comparison could reveal.
    ReferenceCompiler,
    /// Oracle (b). Every non-baseline target versus the x86-64 baseline at the same
    /// optimization level. Detects a wrong answer confined to a single backend, which is
    /// where ABI, register-allocation and instruction-selection defects surface.
    CrossBackend,
    /// Oracle (c). Every cell versus the `expected_stdout` recorded in the program's own
    /// expectation record. Catches the single failure mode differential testing
    /// structurally cannot detect — both compilers changing behaviour in the same
    /// direction at the same time, which oracle (a) still reports as agreement — and with
    /// it, toolchain drift and plain regression over time.
    GoldenRecord,
}

impl Oracle {
    /// Every oracle, in requirement order.
    ///
    /// `report.rs` iterates this array to tally the summary per oracle, and
    /// [`Oracle::parse`] searches it.
    pub const ALL: [Oracle; 3] = [
        Oracle::ReferenceCompiler,
        Oracle::CrossBackend,
        Oracle::GoldenRecord,
    ];

    /// The single letter that names this oracle in the requirements.
    ///
    /// `findings.rs` uses it to build artifact filenames of the form
    /// `outputs/<letter>-<target>-<opt>.stdout`, which is why a short, filename-safe token
    /// exists alongside the human-readable label.
    pub fn letter(self) -> char {
        match self {
            Oracle::ReferenceCompiler => 'a',
            Oracle::CrossBackend => 'b',
            Oracle::GoldenRecord => 'c',
        }
    }

    /// The human-readable label used in reports and failure messages.
    ///
    /// The leading token matches the per-oracle toggle key in an expectation record
    /// (`oracle_a`, `oracle_b`, `oracle_c`), so a report line and the record that governs
    /// it name the oracle the same way.
    pub fn label(self) -> &'static str {
        match self {
            Oracle::ReferenceCompiler => "oracle_a (reference compiler)",
            Oracle::CrossBackend => "oracle_b (cross-backend)",
            Oracle::GoldenRecord => "oracle_c (golden record)",
        }
    }

    /// Parse an oracle from its letter (`a`), its record key (`oracle_a`) or its full
    /// label, ignoring surrounding whitespace.
    ///
    /// `manifest.rs` needs the record-key form to read the per-oracle toggles, and
    /// `report.rs` needs the round trip when it re-reads its own machine-readable rows.
    pub fn parse(text: &str) -> Option<Oracle> {
        let wanted = text.trim();
        let bare = wanted.strip_prefix("oracle_").unwrap_or(wanted);
        Oracle::ALL.iter().copied().find(|candidate| {
            if wanted == candidate.label() {
                return true;
            }
            let mut characters = bare.chars();
            characters.next() == Some(candidate.letter()) && characters.next().is_none()
        })
    }
}

impl fmt::Display for Oracle {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.label())
    }
}

impl std::str::FromStr for Oracle {
    type Err = HarnessError;

    fn from_str(text: &str) -> Result<Oracle, HarnessError> {
        Oracle::parse(text).ok_or_else(|| {
            HarnessError::new(
                "parsing an oracle identity",
                format!(
                    "{text:?} names no oracle; expected a letter, a record key or a label from: {}",
                    comma_separated(&Oracle::ALL.map(Oracle::label))
                ),
            )
        })
    }
}

// ---------------------------------------------------------------------------
// Divergence class
// ---------------------------------------------------------------------------

/// The shape a divergence took, independently of how it was classified into a verdict.
///
/// The set is closed at six members and stays closed: a newly observed failure shape must
/// be mapped onto one of these, never appended as a seventh, so that the classification
/// table in `classify.rs` remains total and auditable.
///
/// The labels are the machine-readable tokens an expectation record uses in the `class`
/// field of an expected-divergence marker, so `manifest.rs` reads a marker and
/// `classify.rs` renders a verdict using one vocabulary.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum DivergenceClass {
    /// One compiler rejected a program the other accepted. Asymmetric compilation is
    /// itself a signal, so the diagnostics are captured even though they are never
    /// compared.
    CompileFailure,
    /// Compilation succeeded but the artifact failed to link, most often because a
    /// target's C runtime is missing from the environment rather than because of a
    /// compiler defect — a distinction the environment fingerprint in a finding preserves.
    LinkFailure,
    /// The program terminated on a signal instead of exiting normally. Exit status is
    /// compared as a raw wait status precisely so that this is never conflated with a
    /// numerically equal ordinary exit.
    RunCrash,
    /// Both programs ran to completion and agreed on stdout, but their exit statuses
    /// differ.
    ExitCodeMismatch,
    /// The compared stdout byte streams differ. The first divergent line and byte offset
    /// are always reported, because a divergence that cannot be located cannot be
    /// minimized.
    StdoutMismatch,
    /// Execution exceeded its per-cell budget. A first-class divergence class rather than
    /// an infrastructure error: a program that finishes promptly under one compiler and
    /// hangs under another is exactly the kind of defect the suite exists to surface.
    Timeout,
}

impl DivergenceClass {
    /// Every divergence class, in the order `classify.rs` considers them.
    ///
    /// `report.rs` iterates this array to tally divergences per class, and
    /// [`DivergenceClass::parse`] searches it.
    pub const ALL: [DivergenceClass; 6] = [
        DivergenceClass::CompileFailure,
        DivergenceClass::LinkFailure,
        DivergenceClass::RunCrash,
        DivergenceClass::ExitCodeMismatch,
        DivergenceClass::StdoutMismatch,
        DivergenceClass::Timeout,
    ];

    /// The machine-readable token, matching the `class` field of an expected-divergence
    /// marker.
    pub fn label(self) -> &'static str {
        match self {
            DivergenceClass::CompileFailure => "compile_failure",
            DivergenceClass::LinkFailure => "link_failure",
            DivergenceClass::RunCrash => "run_crash",
            DivergenceClass::ExitCodeMismatch => "exit_code_mismatch",
            DivergenceClass::StdoutMismatch => "stdout_mismatch",
            DivergenceClass::Timeout => "timeout",
        }
    }

    /// Parse a divergence class from its token, ignoring surrounding whitespace and ASCII
    /// case.
    ///
    /// Case is ignored so that a marker written in a different case is still understood
    /// rather than silently treated as an unknown class, which would turn a documented
    /// expected divergence into an unexplained failure.
    pub fn parse(text: &str) -> Option<DivergenceClass> {
        let wanted = text.trim();
        DivergenceClass::ALL
            .iter()
            .copied()
            .find(|candidate| wanted.eq_ignore_ascii_case(candidate.label()))
    }
}

impl fmt::Display for DivergenceClass {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.label())
    }
}

impl std::str::FromStr for DivergenceClass {
    type Err = HarnessError;

    fn from_str(text: &str) -> Result<DivergenceClass, HarnessError> {
        DivergenceClass::parse(text).ok_or_else(|| {
            HarnessError::new(
                "parsing a divergence class",
                format!(
                    "{text:?} names no divergence class; the closed set is: {}",
                    comma_separated(&DivergenceClass::ALL.map(DivergenceClass::label))
                ),
            )
        })
    }
}

// ---------------------------------------------------------------------------
// Verdict
// ---------------------------------------------------------------------------

/// The outcome of one comparison, from a closed and exhaustive set of six.
///
/// There is deliberately NO "skip because unsupported" verdict, and no code path anywhere
/// in the harness may silently drop a cell. An oracle whose tooling is genuinely absent is
/// reported as [`Verdict::Unavailable`] — loudly, and in the summary — which is what keeps
/// a modest environment from masquerading as a passing run.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Verdict {
    /// The compared outputs agree exactly: identical stdout bytes and identical exit
    /// status.
    Pass,
    /// A divergence that a marker in the program's own expectation record explains, citing
    /// a limitation the repository already documents. A marked program still compiles and
    /// still runs the feature; a marker changes how a divergence is CLASSIFIED, never
    /// whether the feature is EXERCISED.
    XFail,
    /// A marker is present but the divergence it describes has disappeared.
    ///
    /// This fails the run by default, following the standard convention that unexpected
    /// success is a failure. The justification is asymmetric cost: a stale marker is stale
    /// documented knowledge that will mislead the next reader, whereas retiring it is a
    /// trivial test-only edit. An environment-variable escape hatch exists for a
    /// marker-retirement window, and this verdict is always listed separately and
    /// prominently in the summary so it can never pass unnoticed.
    XPass,
    /// An undocumented divergence. It yields a self-contained artifact directory — the
    /// minimized reproducer, its expectation record, a manifest, exact reproduction
    /// commands, the captured outputs per compiler and per backend, an environment
    /// fingerprint and the computed difference — plus an entry in the findings register.
    ///
    /// A finding is a deliverable, not a defect to patch: no compiler source change is
    /// ever made in response to one.
    Finding,
    /// A divergence with no explanation at all, or an internal inconsistency in the suite
    /// itself. Fails the run.
    Fail,
    /// An oracle's tooling is genuinely absent from the environment, so this comparison
    /// could not be attempted.
    ///
    /// Always reported, never silent, and never a pass. Under the strict setting intended
    /// for continuous integration — where the toolchain is installed deliberately, so a
    /// missing oracle indicates a broken workflow rather than a modest machine — the
    /// driver escalates this to a failure.
    Unavailable,
}

impl Verdict {
    /// Every verdict, in reporting order.
    ///
    /// `report.rs` iterates this array so that the summary's verdict tally is always
    /// complete and always in the same order, including zero rows, and
    /// [`Verdict::parse`] searches it.
    pub const ALL: [Verdict; 6] = [
        Verdict::Pass,
        Verdict::XFail,
        Verdict::XPass,
        Verdict::Finding,
        Verdict::Fail,
        Verdict::Unavailable,
    ];

    /// True for exactly the two verdicts that make a run fail: an unexplained failure and
    /// an unexpected success.
    ///
    /// The four verdicts permitted in a passing run are [`Verdict::Pass`],
    /// [`Verdict::XFail`], [`Verdict::Finding`] and [`Verdict::Unavailable`] — each of
    /// which is still reported in full. A finding does not fail the run because findings
    /// are deliverables; an unavailable oracle does not fail the run by default because
    /// the environment, not the compiler, is what is incomplete.
    pub fn fails_run(self) -> bool {
        matches!(self, Verdict::Fail | Verdict::XPass)
    }

    /// The uppercase report token, spelled exactly as the requirements spell it so that a
    /// report line and the specification read identically.
    pub fn label(self) -> &'static str {
        match self {
            Verdict::Pass => "PASS",
            Verdict::XFail => "XFAIL",
            Verdict::XPass => "XPASS",
            Verdict::Finding => "FINDING",
            Verdict::Fail => "FAIL",
            Verdict::Unavailable => "UNAVAILABLE",
        }
    }

    /// Parse a verdict from its report token, ignoring surrounding whitespace and ASCII
    /// case, so that `report.rs` can re-read the machine-readable rows it wrote.
    pub fn parse(text: &str) -> Option<Verdict> {
        let wanted = text.trim();
        Verdict::ALL
            .iter()
            .copied()
            .find(|candidate| wanted.eq_ignore_ascii_case(candidate.label()))
    }
}

impl fmt::Display for Verdict {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.label())
    }
}

impl std::str::FromStr for Verdict {
    type Err = HarnessError;

    fn from_str(text: &str) -> Result<Verdict, HarnessError> {
        Verdict::parse(text).ok_or_else(|| {
            HarnessError::new(
                "parsing a verdict",
                format!(
                    "{text:?} names no verdict; the closed set is: {}",
                    comma_separated(&Verdict::ALL.map(Verdict::label))
                ),
            )
        })
    }
}

// ---------------------------------------------------------------------------
// Cell identity
// ---------------------------------------------------------------------------

/// Separator between the components of a cell slug.
///
/// A doubled underscore is unambiguous because [`sanitize_path_component`] guarantees no
/// component contains a doubled underscore and no component begins or ends with one.
const SLUG_SEPARATOR: &str = "__";

/// Placeholder for a component that sanitizes to nothing, so a slug is never malformed.
const EMPTY_COMPONENT_PLACEHOLDER: &str = "unnamed";

/// Fold one slug component into the filesystem-safe alphabet `[A-Za-z0-9._-]`.
///
/// Every character outside that alphabet — and the underscore itself — folds to a single
/// underscore; runs collapse to one; leading and trailing runs are dropped entirely. Two
/// properties follow, and together they are what make [`CellKey::slug`] collision-free:
/// no result contains a doubled underscore, and no result begins or ends with an
/// underscore, so the doubled-underscore separator can never be confused with a character
/// belonging to a component.
///
/// The mapping is a pure function of its input: no clock, no process identifier, no
/// randomness, no environment.
fn sanitize_path_component(raw: &str) -> String {
    let mut sanitized = String::with_capacity(raw.len());
    let mut separator_pending = false;
    for character in raw.chars() {
        if character.is_ascii_alphanumeric() || character == '.' || character == '-' {
            if separator_pending && !sanitized.is_empty() {
                sanitized.push('_');
            }
            separator_pending = false;
            sanitized.push(character);
        } else {
            separator_pending = true;
        }
    }
    if sanitized.is_empty() {
        return String::from(EMPTY_COMPONENT_PLACEHOLDER);
    }
    sanitized
}

/// Identifies exactly one cell of the build matrix: one program, on one target, at one
/// optimization level.
///
/// This is the unit of work the whole harness is organized around, and it is the sole
/// input to a cell's workspace path, which is how concurrent execution is made safe by
/// construction rather than by locking.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct CellKey {
    /// Feature-area directory name, for example `04_bitfields`.
    pub area: String,
    /// Program stem without an extension, for example `003_compound_assignment`.
    pub program: String,
    /// Target architecture this cell was built and executed for.
    pub target: Target,
    /// Optimization level this cell was built at.
    pub opt: OptLevel,
}

impl CellKey {
    /// A deterministic, collision-free, filesystem-safe rendering of this identity, for
    /// example `01_integer_conversions__004_narrowing_conversions__aarch64__O1`.
    ///
    /// The slug contains no process identifier, no timestamp and no counter, so the same
    /// identity yields the same slug in every process and on every run. That is what makes
    /// a retained workspace reproducible and inspectable after the fact, and it is also
    /// what removes the need for any lock: two concurrent cells cannot collide because
    /// distinct identities cannot render to the same slug.
    pub fn slug(&self) -> String {
        let components = [
            sanitize_path_component(&self.area),
            sanitize_path_component(&self.program),
            sanitize_path_component(self.target.short_name()),
            sanitize_path_component(self.opt.short()),
        ];
        let mut rendered = String::new();
        for component in components {
            if !rendered.is_empty() {
                rendered.push_str(SLUG_SEPARATOR);
            }
            rendered.push_str(&component);
        }
        rendered
    }
}

impl fmt::Display for CellKey {
    /// Human-readable form for failure messages, for example
    /// `04_bitfields/003_compound_assignment @ aarch64-linux-gnu -O1`.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "{}/{} @ {} {}",
            self.area, self.program, self.target, self.opt
        )
    }
}

/// One fully resolved cell: its identity, the two files that define it, and the single
/// directory it is permitted to write into.
///
/// A cell is deliberately self-describing. Requirement four demands that every cell be
/// reproducible in isolation from its source file and its expectation record alone, so both
/// paths travel with the identity rather than being recomputed by each consumer.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct Cell {
    /// Which program, target and optimization level this cell is.
    pub key: CellKey,
    /// Absolute path to the C program.
    pub source: PathBuf,
    /// Absolute path to the sibling expectation record that governs this program.
    pub expectation: PathBuf,
    /// The one directory this cell may write into, derived from [`work_root`] and
    /// [`CellKey::slug`].
    pub workspace: PathBuf,
}

impl Cell {
    /// Resolve a cell, validating the two input paths and deriving the workspace.
    ///
    /// The workspace is derived rather than supplied, so hermeticity is decided in exactly
    /// one place: every cell writes beneath [`work_root`] and nowhere else.
    ///
    /// Validation is strict on purpose. A program without a sibling expectation record, or
    /// a path that is not absolute, is a broken invariant of the corpus rather than a
    /// condition an environment can legitimately produce, so it becomes an explanatory hard
    /// failure that names the cell — never a quiet skip and never an opaque panic.
    pub fn new(key: CellKey, source: PathBuf, expectation: PathBuf) -> HarnessResult<Cell> {
        Cell::require_absolute(&key, "source", &source)?;
        Cell::require_extension(&key, "source", &source, "c")?;
        Cell::require_absolute(&key, "expectation record", &expectation)?;
        Cell::require_extension(&key, "expectation record", &expectation, "expected")?;
        let workspace = work_root().join(key.slug());
        Ok(Cell {
            key,
            source,
            expectation,
            workspace,
        })
    }

    /// Reject a relative path, naming the cell and the role of the offending path.
    fn require_absolute(key: &CellKey, role: &str, path: &Path) -> HarnessResult<()> {
        if path.is_absolute() {
            return Ok(());
        }
        Err(HarnessError::new(
            format!("resolving the {role} path for {key}"),
            format!(
                "{} is not absolute; corpus paths are derived from the package manifest \
                 directory so that a cell never depends on the working directory",
                path.display()
            ),
        ))
    }

    /// Reject a path whose extension is not the one the role requires.
    fn require_extension(
        key: &CellKey,
        role: &str,
        path: &Path,
        wanted: &str,
    ) -> HarnessResult<()> {
        let found = path.extension().and_then(|extension| extension.to_str());
        if found == Some(wanted) {
            return Ok(());
        }
        Err(HarnessError::new(
            format!("resolving the {role} path for {key}"),
            format!(
                "{} does not have the required extension {wanted:?}; every program in the corpus \
                 is a .c file paired with a sibling .expected record",
                path.display()
            ),
        ))
    }
}

impl fmt::Display for Cell {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "{} [source {}, expectation {}, workspace {}]",
            self.key,
            self.source.display(),
            self.expectation.display(),
            self.workspace.display()
        )
    }
}

// ---------------------------------------------------------------------------
// Accumulated outcome
// ---------------------------------------------------------------------------

/// One accumulated verdict: what a single oracle concluded about a single cell.
///
/// Outcomes are accumulated rather than asserted one at a time. Each feature-area test
/// runs its complete matrix and collects every outcome before asserting, because the
/// deliverable summary must enumerate every result — every expected divergence with its
/// documented basis and every finding with its reproducer — and stopping at the first
/// divergence would truncate exactly the artifact the requirements ask for.
///
/// An outcome is keyed by oracle as well as by cell, which is what lets a construct be
/// excluded from one oracle while remaining fully compared under the others.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct Outcome {
    /// The cell this outcome is about.
    pub key: CellKey,
    /// Which oracle produced it.
    pub oracle: Oracle,
    /// What was concluded.
    pub verdict: Verdict,
    /// The shape of the divergence, when there was one. `None` for an agreement and for an
    /// oracle that could not be attempted.
    pub class: Option<DivergenceClass>,
    /// Identifier of the expected-divergence marker that explains this outcome, present for
    /// an expected divergence and for an unexpected success, absent otherwise.
    pub marker_id: Option<String>,
    /// Everything a reader needs to understand the outcome without re-running it: the first
    /// divergent line and byte offset, both exit statuses, and the command lines involved.
    pub detail: String,
}

impl Outcome {
    /// Record one outcome.
    ///
    /// The detail is never allowed to be empty. If a caller supplies nothing, an
    /// explanatory sentence naming the verdict, the oracle and the cell is substituted, and
    /// for a verdict that fails the run the substitution says plainly that the missing
    /// detail is itself a defect — because a run-failing outcome with an opaque message is
    /// exactly what makes a real divergence impossible to act on.
    pub fn new(
        key: CellKey,
        oracle: Oracle,
        verdict: Verdict,
        class: Option<DivergenceClass>,
        marker_id: Option<String>,
        detail: impl Into<String>,
    ) -> Outcome {
        let supplied = detail.into();
        let detail = if supplied.trim().is_empty() {
            let severity = if verdict.fails_run() {
                "this verdict fails the run, so the absent detail is itself a defect in the \
                 caller that recorded it"
            } else {
                "no further detail was recorded"
            };
            format!("{verdict} from {oracle} for {key} carries no detail: {severity}")
        } else {
            supplied
        };
        Outcome {
            key,
            oracle,
            verdict,
            class,
            marker_id,
            detail,
        }
    }
}

impl fmt::Display for Outcome {
    /// One-line rendering used verbatim in the driver's verdict table and in failure
    /// messages, so a failing run reproduces the same text a report contains.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "[{}] {} {}", self.verdict, self.oracle, self.key)?;
        if let Some(class) = self.class {
            write!(f, " (class {class})")?;
        }
        if let Some(marker) = &self.marker_id {
            write!(f, " (marker {marker})")?;
        }
        write!(f, ": {}", self.detail)
    }
}

// ---------------------------------------------------------------------------
// Error reporting
// ---------------------------------------------------------------------------

/// A harness failure that is genuinely the suite's or the corpus's fault.
///
/// The distinction this type draws is the one the requirements insist on. A tool that an
/// environment can legitimately lack is NOT an error: it becomes [`Verdict::Unavailable`],
/// reported loudly and in the summary. An error is reserved for a broken invariant — a
/// program with no sibling expectation record, an unreadable corpus directory, a compiler
/// under test that is absent, a marker that cites a document which does not exist — and it
/// always surfaces as an explanatory hard failure. Neither path is ever a silent pass.
///
/// Both halves are carried separately so that a message always says what the harness was
/// doing as well as what went wrong, which is what makes a failure actionable without a
/// stack trace.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct HarnessError {
    /// What the harness was attempting, phrased as a gerund, for example
    /// `resolving the source path for 04_bitfields/002_read_write @ i686-linux-gnu -O1`.
    pub context: String,
    /// What went wrong, in enough detail to act on without re-running.
    pub cause: String,
}

impl HarnessError {
    /// Build an error from its context and its cause.
    ///
    /// Both arguments accept a borrowed or an owned string, so a call site can pass a
    /// literal for the fixed half and a formatted string for the variable half without
    /// ceremony.
    pub fn new(context: impl Into<String>, cause: impl Into<String>) -> HarnessError {
        HarnessError {
            context: context.into(),
            cause: cause.into(),
        }
    }
}

impl fmt::Display for HarnessError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "conformance harness failed while {}: {}",
            self.context, self.cause
        )
    }
}

impl std::error::Error for HarnessError {}

impl From<std::io::Error> for HarnessError {
    /// Adapt a filesystem or process error so that the question-mark operator works
    /// throughout the harness.
    ///
    /// The context is necessarily generic here, which is why call sites that know what they
    /// were doing should build the error with [`HarnessError::new`] instead. The underlying
    /// message is preserved verbatim, so the cause is never lost.
    fn from(error: std::io::Error) -> HarnessError {
        HarnessError::new(
            "performing a filesystem or process operation",
            error.to_string(),
        )
    }
}

/// Result alias used throughout the harness.
pub type HarnessResult<T> = Result<T, HarnessError>;

// ---------------------------------------------------------------------------
// Path roots
// ---------------------------------------------------------------------------
//
// Every filesystem location the harness touches is derived from the four roots below, so
// hermeticity is provable by inspecting one place. The suite reads only a program's source
// and its expectation record, and it writes only beneath the work, report and findings
// roots — all three of which live inside the Cargo build directory. Nothing is written
// outside it, no path outside the build directory is created, and no socket is opened
// anywhere in the harness.

/// Absolute path to the package root, taken from the manifest directory Cargo provides at
/// compile time.
///
/// Resolved from the manifest directory rather than from the working directory on purpose:
/// `cargo test` makes no guarantee about the working directory of a test process, so a
/// relative guess or a parent-directory walk would be a latent bug that only appears when
/// the suite is invoked from somewhere unexpected.
pub fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// Absolute path to the corpus root, which holds the feature-area directories, the
/// registers, the single fixture header, the maintenance tooling and the curated findings.
///
/// The corpus is discovered by scanning this directory, which is why adding a program takes
/// exactly two new files and no harness change at all.
pub fn corpus_root() -> PathBuf {
    manifest_dir().join("tests").join("conformance")
}

/// Absolute path to the Cargo build directory, the only place the harness writes.
///
/// The configured target directory is honoured when set, because a build that redirects its
/// output would otherwise have the harness writing into a directory the build does not own
/// — the most common way a test harness escapes its sandbox. A configured value that is
/// relative is resolved against the package root rather than against the working directory,
/// so the result is absolute in every case.
pub fn build_root() -> PathBuf {
    let configured = std::env::var_os("CARGO_TARGET_DIR").filter(|value| !value.is_empty());
    match configured {
        Some(value) => {
            let configured_root = PathBuf::from(value);
            if configured_root.is_absolute() {
                configured_root
            } else {
                manifest_dir().join(configured_root)
            }
        }
        None => manifest_dir().join("target"),
    }
}

/// Root of the per-cell workspaces, one subdirectory per [`CellKey::slug`].
///
/// A workspace is removed once its cell has passed and retained when it has not, so a
/// failing cell leaves behind exactly the artifacts needed to investigate it; the retention
/// setting keeps every workspace when a maintainer wants to inspect a passing cell too.
pub fn work_root() -> PathBuf {
    build_root().join("conformance-work")
}

/// Root of the run's reports: one Markdown and one tab-separated file per feature area,
/// plus the run summary in both forms.
///
/// Each area writes only its own file, so concurrently executing areas never contend, and
/// the summary is finalized by a check-and-write that succeeds once every area file exists
/// — which requires no ordering between tests and adds no test of its own.
pub fn report_root() -> PathBuf {
    build_root().join("conformance-report")
}

/// Root of the findings generated by the current run.
///
/// This is deliberately distinct from the curated, committed finding set that lives under
/// the corpus root: that set is a deliverable, and a test run must never write into it, so
/// an in-progress run cannot pollute it. No function in this harness returns a writable
/// handle to the committed set for exactly that reason.
pub fn findings_root() -> PathBuf {
    build_root().join("conformance-findings")
}
