//! Shared vocabulary, flag tables and path roots for the differential conformance
//! harness driven by `tests/conformance.rs`.
//!
//! # The three oracles
//!
//! Each cell of the build matrix — one program, one target, one optimization level — is
//! judged on stdout bytes and exit status alone:
//!
//! - [`Oracle::ReferenceCompiler`] compares bcc against an external reference C compiler
//!   at the same target and level.
//! - [`Oracle::CrossBackend`] compares every non-baseline target against
//!   [`Target::BASELINE`] at the same level.
//! - [`Oracle::GoldenRecord`] compares a cell against the `expected_stdout` recorded in
//!   the program's own `.expected` file.
//!
//! Standard error is captured for finding artifacts but never compared, because
//! diagnostic wording legitimately differs between compilers.
//!
//! # Invariants callers may rely on
//!
//! - Only `std` is used; the project permits no third-party crate.
//! - This directory contains no `#[test]` function and no `main.rs`, so Cargo treats it
//!   as a plain module directory rather than a test target.
//! - Nothing is written outside the Cargo build directory. The three write roots are
//!   [`work_root`] (one workspace per cell, keyed by [`CellKey::slug`]),
//!   [`report_root`] (one file per feature area, plus the run summary) and
//!   [`findings_root`] (findings generated by the current run). The committed finding set
//!   under [`corpus_root`] is a deliverable and is never written by a run.
//! - No shared mutable state: a cell's workspace path is a pure function of its identity
//!   and each area writes only its own report file, so `cargo test`'s default concurrency
//!   needs no lock.
//!
//! Edition 2021, minimum supported Rust 1.70.

pub mod classify;
pub mod compare;
pub mod compile;
pub mod env;
pub mod execute;
pub mod findings;
pub mod flagprobe;
pub mod manifest;
pub mod report;
pub mod sandbox;
pub mod ubaudit;

use std::fmt;
use std::path::{Path, PathBuf};

// Expected size of the build matrix. `report.rs` re-reports these counts on every run
// and treats a discovered count that disagrees with one of them as a corpus defect.

pub const AREA_COUNT: usize = 14;

pub const PROGRAM_COUNT: usize = 108;

pub const OPT_LEVEL_COUNT: usize = OptLevel::ALL.len();

/// Number of target architectures swept per program, unless a program restricts its own
/// target list and records the reason for the restriction.
pub const TARGET_COUNT: usize = Target::ALL.len();

pub const BCC_CELL_COUNT: usize = PROGRAM_COUNT * TARGET_COUNT * OPT_LEVEL_COUNT;

/// Reference-compiler cells on the native target, using the native driver.
pub const REFERENCE_NATIVE_CELL_COUNT: usize = PROGRAM_COUNT * OPT_LEVEL_COUNT;

/// Reference-compiler cells on the three non-native targets, using the matching cross
/// drivers. An upper bound: a cross driver that is absent from the environment degrades
/// its arm of oracle (a) to [`Verdict::Unavailable`] rather than silently vanishing.
pub const REFERENCE_CROSS_CELL_COUNT_MAX: usize =
    PROGRAM_COUNT * OPT_LEVEL_COUNT * (TARGET_COUNT - 1);

/// Oracle (a) comparisons, assuming every cross driver is present.
pub const ORACLE_A_COMPARISON_COUNT: usize =
    REFERENCE_NATIVE_CELL_COUNT + REFERENCE_CROSS_CELL_COUNT_MAX;

/// Oracle (b) comparisons: every non-baseline target against the baseline, per program
/// per optimization level.
pub const ORACLE_B_COMPARISON_COUNT: usize = PROGRAM_COUNT * OPT_LEVEL_COUNT * (TARGET_COUNT - 1);

pub const ORACLE_C_ASSERTION_COUNT: usize = BCC_CELL_COUNT;

pub const TOTAL_ASSERTION_COUNT: usize =
    ORACLE_A_COMPARISON_COUNT + ORACLE_B_COMPARISON_COUNT + ORACLE_C_ASSERTION_COUNT;

/// Floor on the number of programs in a mandated feature area. `report.rs` applies this
/// bound only where [`AreaSpec::mandated`] holds.
pub const MIN_PROGRAMS_PER_MANDATED_AREA: usize = 6;

/// One feature area of the corpus.
///
/// The [`AREAS`] table is the only source of values: there is no public constructor, so
/// callers look an area up with [`AreaSpec::lookup`] and read the fields.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct AreaSpec {
    /// Directory name beneath [`corpus_root`], for example `04_bitfields`. Also the stem
    /// of the area's report files and the suffix of the driver's area test name.
    pub directory: &'static str,
    pub program_count: usize,
    /// True when the requirements name the area explicitly, false when it is
    /// supplementary.
    pub mandated: bool,
}

impl AreaSpec {
    const fn new(directory: &'static str, program_count: usize, mandated: bool) -> AreaSpec {
        AreaSpec {
            directory,
            program_count,
            mandated,
        }
    }

    /// Look an area up by its directory name, trimming surrounding whitespace.
    ///
    /// Returns `None` for a directory that is not part of the corpus, which the caller
    /// must report rather than skip.
    pub fn lookup(directory: &str) -> Option<&'static AreaSpec> {
        let wanted = directory.trim();
        AREAS.iter().find(|area| area.directory == wanted)
    }
}

impl fmt::Display for AreaSpec {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let kind = if self.mandated {
            "mandated"
        } else {
            "supplementary"
        };
        write!(
            f,
            "{} ({} programs, {})",
            self.directory, self.program_count, kind
        )
    }
}

/// The feature areas in numeric order. The program counts sum to [`PROGRAM_COUNT`].
pub const AREAS: [AreaSpec; AREA_COUNT] = [
    AreaSpec::new("01_integer_conversions", 10, true),
    AreaSpec::new("02_constant_expressions", 8, true),
    AreaSpec::new("03_initializers", 11, true),
    AreaSpec::new("04_bitfields", 7, true),
    AreaSpec::new("05_pointers", 10, true),
    AreaSpec::new("06_control_flow", 10, true),
    AreaSpec::new("07_variadics", 6, true),
    AreaSpec::new("08_gcc_extensions", 8, true),
    AreaSpec::new("09_optimization_levels", 8, true),
    AreaSpec::new("10_declarations_and_types", 10, false),
    AreaSpec::new("11_literals_and_strings", 4, false),
    AreaSpec::new("12_preprocessor", 6, false),
    AreaSpec::new("13_floating_point", 4, false),
    AreaSpec::new("14_abi_calling_convention", 6, false),
];

// The flag tables below are defined once and used twice: `compile.rs` enforces them when
// it builds an argument vector, and `flagprobe.rs` verifies them against both compilers.
//
// The discipline governs the SHARED argument set — the flags passed identically to both
// compilers — so it is the reference side that decides admissibility. The split is by
// compiler side rather than by oracle, because the two sides select a target differently:
// the reference compiler has no target-selection flag (the `--target=` spelling belongs to
// another compiler family and was measured to be rejected, and `-m32` fails on the reference
// host), so a target is selected there by choosing a different driver binary; the compiler
// under test has no cross drivers, so `--target <triple>` is the only way it can reach a
// non-native backend and is required for every non-native cell under oracle (a) exactly as
// much as under oracle (b). [`is_forbidden_for_side`] is the one place that split is
// expressed.

/// Flags both compilers are expected to accept with the same meaning, and therefore the
/// envelope within which maintenance of the differential invocations may move.
///
/// `flagprobe.rs` asserts an observable consequence per flag rather than mere acceptance,
/// because two compilers can accept the same spelling and mean different things by it —
/// which is why `-fcf-protection` appears in [`FORBIDDEN_IN_DIFFERENTIAL`] instead.
///
/// `-L` and `-l` are checked for acceptance only. Verifying them semantically would need
/// an archive-creation tool, and the corpus links nothing but the C runtime, which is
/// linked by default.
pub const SHARED_FLAGS_VERIFIED: &[&str] = &[
    "-o", "-c", "-O0", "-O1", "-O2", "-I", "-D", "-U", "-L", "-l", "-g", "-static", "-fPIC",
];

/// The minimal flag set actually used in a differential invocation: the output path,
/// static linkage, and one optimization level from [`OptLevel::flag`].
///
/// Static linkage is what lets emulated execution work with no sysroot and no
/// dynamic-loader configuration on any of the four targets.
pub const DIFFERENTIAL_FLAGS_MINIMAL: &[&str] = &["-o", "-static"];

/// Flags that must never appear in the SHARED argument set of a differential invocation, nor
/// on the reference-compiler side of one, asserted negatively by `flagprobe.rs` so that a
/// maintenance edit cannot quietly reintroduce one.
///
/// This is the reference-and-shared table. For the compiler-under-test side ask
/// [`is_forbidden_for_side`] instead: the final two entries are the bcc-only target-selection
/// spellings of [`BCC_TARGET_SELECTORS`], and one of them is *required* on that side for every
/// non-native cell.
///
/// - Only the reference side accepts them: `-O3`, `-Os`, `-std=`, `-m32`. bcc documents no
///   optimization level above `-O2` and has no `-std` flag at all; the reference compiler's
///   default mode was measured as gnu17, which already enables the GNU extensions the corpus
///   exercises. `-m32` is unusable on the reference host, which is why i686 coverage comes
///   from the i686 cross driver instead.
/// - They belong to the audit gate, which drives the reference compiler and never bcc:
///   `-pedantic`, `-Wall`, `-Wextra`, `-Werror`, `-Wconversion`, `-Wsign-conversion`,
///   `-Wshadow`, `-fsanitize=`. Every member of [`UB_AUDIT_GATE_DEFAULT`] is listed here
///   without exception, so a gate flag can never be admitted into a `shared_flags` list.
/// - They redefine the language or the runtime the corpus is written against, so the compared
///   programs would no longer be the same program: `-fwrapv`, `-fno-strict-aliasing`,
///   `-fno-builtin`, `-ffreestanding`, `-nostdlib`.
/// - They stop before a runnable artifact exists, leaving all three oracles nothing to compare:
///   `-S`, `-E`.
/// - Both compilers accept them but disagree on the default scope, so acceptance alone would be
///   a false positive: `-fcf-protection`. This is the entry that proves verification had to be
///   semantic rather than syntactic.
/// - They are bcc spellings, forbidden on the reference side rather than everywhere:
///   `--target`, `--sysroot`. `-mretpoline` is bcc-only hardening with no reference equivalent
///   of the same scope.
pub const FORBIDDEN_IN_DIFFERENTIAL: &[&str] = &[
    "-O3",
    "-Os",
    "-std=",
    "-pedantic",
    "-Wall",
    "-Wextra",
    "-Werror",
    "-Wconversion",
    "-Wsign-conversion",
    "-Wshadow",
    "-m32",
    "-S",
    "-E",
    "-fwrapv",
    "-fno-strict-aliasing",
    "-fsanitize=",
    "-fno-builtin",
    "-ffreestanding",
    "-nostdlib",
    "-mretpoline",
    "-fcf-protection",
    "--target",
    "--sysroot",
];

/// The two bcc-only target-selection spellings.
///
/// Both appear in [`FORBIDDEN_IN_DIFFERENTIAL`], because neither may enter the shared
/// argument set or the reference side, and both are permitted on the compiler-under-test
/// side, because that side is where a target is selected by flag rather than by driver
/// binary. Naming them once, here, is what lets [`is_forbidden_for_side`] express the split
/// without a second table that could drift from the first.
pub const BCC_TARGET_SELECTORS: &[&str] = &["--target", "--sysroot"];

/// The compiler-under-test target-selection flag.
///
/// Spelled once so that the flag table, the argument builder in `compile.rs` and the
/// `bcc_command` template contract in `manifest.rs` cannot disagree about it.
pub const BCC_TARGET_FLAG: &str = "--target";

/// Which side of a differential invocation an argument is destined for.
///
/// The shared-flag discipline governs the flags passed identically to both compilers, so it
/// is the reference side that decides whether a spelling is admissible: a flag the reference
/// compiler rejects can never be part of a set both compilers honour with the same meaning.
/// An argument that reaches only the compiler under test is judged by the same table minus
/// the target selectors, which that side alone can honour.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum CompilerSide {
    /// The compiler under test. Target selection by flag is permitted here, and required for
    /// a non-native cell — see [`bcc_requires_explicit_target`].
    UnderTest,
    /// The reference compiler, and by extension the shared argument set. Target selection by
    /// flag is forbidden here: the reference compiler has none, so a target is selected by
    /// choosing a different driver binary.
    Reference,
}

impl CompilerSide {
    /// The phrase used in diagnostics, so a rejection says which side rejected the argument.
    pub fn label(self) -> &'static str {
        match self {
            CompilerSide::UnderTest => "compiler under test",
            CompilerSide::Reference => "reference compiler",
        }
    }
}

impl fmt::Display for CompilerSide {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.label())
    }
}

/// True when `flag` is one of the bcc-only target-selection spellings, in any of the three
/// matching forms [`is_forbidden_in_differential`] recognises.
pub fn is_bcc_target_selector(flag: &str) -> bool {
    matches_flag_table(flag, BCC_TARGET_SELECTORS)
}

/// True when `flag` must not appear in the shared argument set of a differential invocation,
/// nor on the reference-compiler side of one.
///
/// Three matching forms are recognised, so a guard on an argument vector cannot be
/// defeated by a spelling variant:
///
/// - exact match, which covers `-O3`, `-Wall`, `-S` and the rest of the plain forms;
/// - prefix match for the two table entries that end in `=`, namely `-std=` and
///   `-fsanitize=`, which never appear without a value;
/// - `<entry>=<value>` for every other entry, which catches `--target=aarch64-linux-gnu`
///   and `-fcf-protection=full` as surely as their space-separated spellings.
///
/// The value form is checked explicitly rather than by a bare prefix test, so that
/// permitted flags are not swept up by accident: `-static` is not rejected because it
/// happens to begin with `-S`, and `-O0` is not rejected because it resembles `-O3`.
///
/// `manifest.rs` calls this to reject a record whose shared-flag list names a flag only one
/// compiler honours, and `flagprobe.rs` calls it to assert the set negatively. `compile.rs`
/// builds a side-specific argument vector and therefore calls [`is_forbidden_for_side`], so
/// that the target selection bcc requires for a non-native cell is not rejected as if it had
/// been destined for both compilers.
pub fn is_forbidden_in_differential(flag: &str) -> bool {
    matches_flag_table(flag, FORBIDDEN_IN_DIFFERENTIAL)
}

/// True when `flag` must not be passed to `side` in a differential invocation.
///
/// The reference side is judged by [`FORBIDDEN_IN_DIFFERENTIAL`] in full. The
/// compiler-under-test side is judged by the same table with [`BCC_TARGET_SELECTORS`]
/// removed, because those two spellings are how that side — which has no cross drivers —
/// reaches a non-native backend at all.
///
/// This is the only place the per-side split is decided, so a maintenance edit cannot make
/// one caller stricter than another.
pub fn is_forbidden_for_side(flag: &str, side: CompilerSide) -> bool {
    match side {
        CompilerSide::Reference => is_forbidden_in_differential(flag),
        CompilerSide::UnderTest => {
            is_forbidden_in_differential(flag) && !is_bcc_target_selector(flag)
        }
    }
}

/// True when the compiler under test must be given an explicit target selection for `target`.
///
/// True for every non-native target, because the compiler under test is a single binary with
/// no cross drivers: without [`BCC_TARGET_FLAG`] it would emit for the host and the cell would
/// compare a host binary against a cross-compiled one. This holds under oracle (a) exactly as
/// much as under oracle (b) — the cross arm of oracle (a) compares bcc's output for a target
/// against the matching cross driver's output for that same target.
///
/// The corpus records pass the selection unconditionally, including for the native target,
/// which is always permitted and keeps one template correct for every cell of a program. This
/// predicate states the minimum the harness must enforce, not the maximum it may pass.
pub fn bcc_requires_explicit_target(target: Target) -> bool {
    !target.is_native()
}

/// The two arguments that select `target` on the compiler-under-test side.
///
/// Returned as a pair rather than one joined string because they are passed as two separate
/// arguments, and a joined `--target=<triple>` spelling — while accepted by the matching form
/// in [`is_forbidden_in_differential`] — is not the spelling the corpus records use.
pub fn bcc_target_arguments(target: Target) -> [String; 2] {
    [String::from(BCC_TARGET_FLAG), String::from(target.triple())]
}

/// Match a flag against one of the tables above, in all three recognised forms.
///
/// Shared by [`is_forbidden_in_differential`] and [`is_bcc_target_selector`] so that the two
/// cannot disagree about whether `--target=aarch64-linux-gnu` is the same flag as
/// `--target aarch64-linux-gnu`.
fn matches_flag_table(flag: &str, table: &[&str]) -> bool {
    let candidate = flag.trim();
    table.iter().any(|entry| {
        if entry.ends_with('=') {
            return candidate.starts_with(entry);
        }
        if candidate == *entry {
            return true;
        }
        match candidate.strip_prefix(entry) {
            Some(remainder) => remainder.starts_with('='),
            None => false,
        }
    })
}

// The audit gate below is driven by the REFERENCE COMPILER ONLY and never by the compiler
// under test, so it is not part of the shared-flag discipline and no member of it may ever
// appear in a differential invocation. That is an invariant rather than an intention: every
// member of `UB_AUDIT_GATE_DEFAULT` is also an entry of `FORBIDDEN_IN_DIFFERENTIAL`, so the
// guard that keeps a reference-only flag out of the shared argument set keeps every gate flag
// out of it too. The gate establishes the precondition that makes all three oracles sound — a
// divergence is evidence about a compiler only when the program is free of undefined and
// unspecified behaviour — so it is a judgement about the TEST PROGRAM, never about bcc. It
// lives here because `manifest.rs` validates a per-program deviation against it and
// `ubaudit.rs` executes it, and defining it once is what stops the two from drifting apart.

/// The strict warning gate every corpus program passes through, in the order it is passed,
/// driven by the reference compiler alone.
///
/// This is the machine half of the undefined-behaviour-freedom guarantee that makes a divergence
/// readable as evidence about the compiler at all: if a program contains undefined behaviour, two
/// compilers disagreeing about it proves nothing, because both are permitted to do anything.
///
/// Measured to genuinely bite rather than decorate: it rejected a probe program on a real
/// diagnostic during design.
///
/// A deviation from this gate is a **removal, never an addition**: a program that cannot pass the
/// full gate records the gate it does want, and that value must be a non-empty subset of this
/// table which drops only [`UB_AUDIT_GATE_REMOVABLE`] members and always retains
/// [`UB_AUDIT_GATE_MANDATORY`]. Modelling it that way is what makes the audit unable to become an
/// arbitrary compiler invocation: no plugin-loading, subprogram-replacing,
/// specification-overriding, search-path or output option can be named at all, because only these
/// seven spellings are accepted.
pub const UB_AUDIT_GATE_DEFAULT: &[&str] = &[
    "-Wall",
    "-Wextra",
    "-pedantic",
    "-Wconversion",
    "-Wsign-conversion",
    "-Wshadow",
    "-Werror",
];

/// The default gate under the name the record-validation code uses for it.
///
/// An alias rather than a second array, so there is exactly one authority for the gate's content
/// and no possibility of two tables drifting apart.
pub const UB_GATE_DEFAULT: &[&str] = UB_AUDIT_GATE_DEFAULT;

/// The only members a program may drop from [`UB_AUDIT_GATE_DEFAULT`], and the sole reason
/// each may be dropped:
///
/// - `-pedantic` — for the supported-extension area, because an extension is non-standard by
///   definition and this flag exists precisely to reject one.
/// - `-Wconversion`, `-Wsign-conversion` — for the deliberate narrowing-conversion programs,
///   because there a narrowing conversion is the behaviour under test rather than a mistake.
///
/// Every other member is non-negotiable. Because a deviation may only REMOVE a member of the
/// default gate, no compiler option outside the gate can be introduced through it — neither a
/// suppression such as `-w` or `-Wno-error`, nor an option that changes include search,
/// specification files, plugins, wrappers or output paths.
pub const UB_AUDIT_GATE_REMOVABLE: &[&str] = &["-pedantic", "-Wconversion", "-Wsign-conversion"];

/// The one member of the gate that no deviation may ever drop.
///
/// A gate that warned without failing would be a gate in name only, so a deviation that dropped
/// this flag would turn every remaining diagnostic into advice.
pub const UB_AUDIT_GATE_MANDATORY: &str = "-Werror";

/// The first sanctioned reduction of the gate: the default without `-pedantic`.
///
/// Sanctioned only in [`EXTENSION_AREA`], where the subject under test is by definition
/// non-standard and `-pedantic` exists precisely to reject it. Dropping it anywhere else would
/// discard a diagnostic that would be a genuine defect in the test program.
pub const UB_GATE_WITHOUT_PEDANTIC: &[&str] = &[
    "-Wall",
    "-Wextra",
    "-Wconversion",
    "-Wsign-conversion",
    "-Wshadow",
    "-Werror",
];

/// The second sanctioned reduction of the gate: the default without the conversion diagnostics.
///
/// Sanctioned where a narrowing conversion is the behaviour under test rather than a mistake, so
/// that the diagnostic which exists to catch an accidental narrowing does not reject a program
/// whose whole subject is a deliberate one.
pub const UB_GATE_WITHOUT_CONVERSION: &[&str] =
    &["-Wall", "-Wextra", "-pedantic", "-Wshadow", "-Werror"];

/// The one feature area whose warning gate may drop `-pedantic`.
///
/// This names the directory of the GCC-extensions area in [`AREAS`]; the two must agree, and the
/// area lookup in `manifest.rs` rejects any record naming a directory that is not in that table.
pub const EXTENSION_AREA: &str = "08_gcc_extensions";

/// True when `flag` is a member of the default audit gate.
pub fn is_ub_audit_gate_member(flag: &str) -> bool {
    let candidate = flag.trim();
    UB_AUDIT_GATE_DEFAULT.contains(&candidate)
}

/// True when `flag` is a member of the default audit gate that a program may drop.
pub fn is_ub_audit_gate_removable(flag: &str) -> bool {
    let candidate = flag.trim();
    UB_AUDIT_GATE_REMOVABLE.contains(&candidate)
}

/// The audit-gate members that no deviation may drop, in gate order.
pub fn ub_audit_gate_required() -> Vec<&'static str> {
    UB_AUDIT_GATE_DEFAULT
        .iter()
        .copied()
        .filter(|flag| !UB_AUDIT_GATE_REMOVABLE.contains(flag))
        .collect()
}

/// One of the four target architectures bcc supports.
///
/// The triple spellings, widths and ELF classes below come from the repository's own
/// target table rather than from this suite.
///
/// # Implementation-defined properties this harness does not branch on
///
/// Plain `char` signedness, `sizeof(long)` and `sizeof(void *)`, and `sizeof(long double)` all
/// differ across these targets. A divergence caused by an implementation-defined difference is
/// not a compiler defect, so each is handled by how a program is written or by a per-oracle
/// exclusion in that program's expectation record — never by harness logic. The two widths are
/// exposed by [`Target::long_width_bytes`] and [`Target::pointer_width_bytes`] for report
/// legends and fingerprints, not for branching.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Target {
    /// x86-64, and the baseline for oracle (b).
    X86_64,
    /// i686, the only ELF32 target.
    I686,
    Aarch64,
    Riscv64,
}

impl Target {
    /// Every target, in the repository's documented table order. [`Target::parse`]
    /// searches this array, so the accepted and emitted spellings are the same set.
    pub const ALL: [Target; 4] = [
        Target::X86_64,
        Target::I686,
        Target::Aarch64,
        Target::Riscv64,
    ];

    /// The baseline every other target is compared against under oracle (b).
    ///
    /// x86-64 is chosen because it is the intended host architecture, so a baseline cell
    /// runs without an emulator and introduces no emulation-related variable.
    pub const BASELINE: Target = Target::X86_64;

    /// The canonical target triple, spelled as the repository's target table spells it and
    /// as bcc's target-selection flag expects it.
    pub fn triple(self) -> &'static str {
        match self {
            Target::X86_64 => "x86_64-linux-gnu",
            Target::I686 => "i686-linux-gnu",
            Target::Aarch64 => "aarch64-linux-gnu",
            Target::Riscv64 => "riscv64-linux-gnu",
        }
    }

    /// The short slug used in workspace paths, report rows and artifact filenames.
    ///
    /// Not the name of the target's emulator: the i686 runner is spelled `qemu-i386`, so
    /// runner names live in `env.rs` and this module exposes only the slug.
    pub fn short_name(self) -> &'static str {
        match self {
            Target::X86_64 => "x86_64",
            Target::I686 => "i686",
            Target::Aarch64 => "aarch64",
            Target::Riscv64 => "riscv64",
        }
    }

    /// ELF class of this target's output: 32 for i686, 64 for the other three.
    ///
    /// `flagprobe.rs` needs it to pick the right header layout when it reads an ELF
    /// identification field directly, which is how `-c`, `-static` and `-g` are verified
    /// without depending on a binary-inspection tool being installed.
    pub fn elf_class(self) -> u8 {
        match self {
            Target::I686 => 32,
            Target::X86_64 | Target::Aarch64 | Target::Riscv64 => 64,
        }
    }

    /// Pointer width in bytes: four on i686, eight on the other three.
    ///
    /// Consumed by report legends and by the environment fingerprint written into every
    /// finding, so a width-related divergence can be read off the artifact directly.
    pub fn pointer_width_bytes(self) -> u8 {
        match self {
            Target::I686 => 4,
            Target::X86_64 | Target::Aarch64 | Target::Riscv64 => 8,
        }
    }

    /// Width of `long` in bytes: four on i686, eight on the other three.
    ///
    /// Same consumers as [`Target::pointer_width_bytes`]. Corpus programs normalize the
    /// difference away rather than relying on it.
    pub fn long_width_bytes(self) -> u8 {
        match self {
            Target::I686 => 4,
            Target::X86_64 | Target::Aarch64 | Target::Riscv64 => 8,
        }
    }

    /// True when this target's binaries execute directly on the host, with no emulator.
    ///
    /// The host architecture is read at run time rather than assumed. The i686 arm is
    /// matched against `x86`, which is how the standard library spells 32-bit x86.
    ///
    /// i686 is therefore reported as non-native on an x86-64 host even though such a host
    /// can usually execute 32-bit binaries. That is deliberate: routing i686 through its
    /// emulator like AArch64 and RISC-V 64 keeps the emulation variable uniform across
    /// all three non-baseline targets and leaves the baseline as the only emulator-free
    /// arm.
    pub fn is_native(self) -> bool {
        let host = std::env::consts::ARCH;
        match self {
            Target::X86_64 => host == "x86_64",
            Target::I686 => host == "x86",
            Target::Aarch64 => host == "aarch64",
            Target::Riscv64 => host == "riscv64",
        }
    }

    /// Parse a target from either its full triple or its short slug, ignoring surrounding
    /// whitespace.
    ///
    /// Both spellings are accepted because expectation records list targets in the short
    /// form (`targets = x86_64, i686, aarch64, riscv64`) while command templates and
    /// report rows use the triple. Returns `None` for anything else, which the caller must
    /// report as a defect in the expectation record rather than drop the cell.
    pub fn parse(text: &str) -> Option<Target> {
        let wanted = text.trim();
        Target::ALL
            .iter()
            .copied()
            .find(|candidate| candidate.triple() == wanted || candidate.short_name() == wanted)
    }
}

impl fmt::Display for Target {
    /// `{}` renders the canonical triple; `{:#}` renders the fact row report legends and
    /// finding fingerprints need — triple, pointer width, `long` width, ELF class, byte
    /// order, execution mode and baseline role.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if !f.alternate() {
            return f.write_str(self.triple());
        }
        let execution = if self.is_native() {
            "native execution"
        } else {
            "emulated execution"
        };
        let role = if *self == Target::BASELINE {
            "oracle_b baseline"
        } else {
            "compared against the oracle_b baseline"
        };
        write!(
            f,
            "{} (pointer {} bytes, long {} bytes, ELF{}, little-endian, {}, {})",
            self.triple(),
            self.pointer_width_bytes(),
            self.long_width_bytes(),
            self.elf_class(),
            execution,
            role,
        )
    }
}

impl std::str::FromStr for Target {
    type Err = HarnessError;

    /// [`Target::parse`] for callers that want an explanatory error instead of `None`.
    fn from_str(text: &str) -> Result<Target, HarnessError> {
        Target::parse(text).ok_or_else(|| {
            HarnessError::new(
                "parsing a target architecture",
                format!(
                    "{text:?} is not one of the four supported targets; expected a triple or short \
                     name from: {}",
                    joined_target_names()
                ),
            )
        })
    }
}

/// Every accepted target spelling, as one comma-separated line for diagnostics.
fn joined_target_names() -> String {
    let mut rendered = String::new();
    for target in Target::ALL {
        if !rendered.is_empty() {
            rendered.push_str(", ");
        }
        rendered.push_str(target.short_name());
        rendered.push_str(" / ");
        rendered.push_str(target.triple());
    }
    rendered
}

/// Render a list of static labels as one comma-separated line for diagnostics.
fn comma_separated(labels: &[&str]) -> String {
    labels.join(", ")
}

/// An optimization level in the sweep.
///
/// These three levels are the whole sweep: levels above `-O2` and size-directed levels are
/// documented as out of scope, so no variant for them exists — not even an unused one,
/// which would invite a maintainer to start passing one. Comparing output across the
/// levels is what makes the suite a semantic-preservation test rather than a check that a
/// particular optimization occurred.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum OptLevel {
    O0,
    O1,
    /// The highest level in scope.
    O2,
}

impl OptLevel {
    /// Every optimization level, in ascending order. [`OptLevel::parse`] searches it.
    pub const ALL: [OptLevel; 3] = [OptLevel::O0, OptLevel::O1, OptLevel::O2];

    /// The command-line spelling, passed identically to bcc and to the reference compiler.
    pub fn flag(self) -> &'static str {
        match self {
            OptLevel::O0 => "-O0",
            OptLevel::O1 => "-O1",
            OptLevel::O2 => "-O2",
        }
    }

    /// The bare spelling used in workspace paths, report rows and artifact filenames,
    /// where a leading dash would be awkward.
    pub fn short(self) -> &'static str {
        match self {
            OptLevel::O0 => "O0",
            OptLevel::O1 => "O1",
            OptLevel::O2 => "O2",
        }
    }

    /// Parse an optimization level from either spelling, ignoring surrounding whitespace.
    ///
    /// Both are accepted because expectation records list the levels in flag form
    /// (`opt_levels = -O0, -O1, -O2`) while report rows and artifact names use the bare
    /// form.
    pub fn parse(text: &str) -> Option<OptLevel> {
        let wanted = text.trim();
        OptLevel::ALL
            .iter()
            .copied()
            .find(|candidate| candidate.flag() == wanted || candidate.short() == wanted)
    }
}

impl fmt::Display for OptLevel {
    /// Renders the command-line spelling, so a rendered level can be pasted straight into
    /// a reproduction command.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.flag())
    }
}

impl std::str::FromStr for OptLevel {
    type Err = HarnessError;

    fn from_str(text: &str) -> Result<OptLevel, HarnessError> {
        OptLevel::parse(text).ok_or_else(|| {
            HarnessError::new(
                "parsing an optimization level",
                format!(
                    "{text:?} is not an optimization level in scope; expected one of: {}",
                    comma_separated(&OptLevel::ALL.map(OptLevel::flag))
                ),
            )
        })
    }
}

/// Which of the three independent oracles produced a comparison.
///
/// Oracle identity is a value rather than a property of a call site so that an exclusion
/// can be expressed per oracle: a construct whose value legitimately differs between
/// architectures stays fully compared against its same-target reference while being
/// excluded from cross-backend value equality alone.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Oracle {
    /// bcc versus an external reference C compiler, same target and optimization level.
    ReferenceCompiler,
    /// Every non-baseline target versus [`Target::BASELINE`] at the same optimization
    /// level, which is where ABI, register-allocation and instruction-selection
    /// differences surface.
    CrossBackend,
    /// Every cell versus the `expected_stdout` recorded in the program's own expectation
    /// record, which is the only oracle that detects both compilers changing behaviour in
    /// the same direction at once.
    GoldenRecord,
}

impl Oracle {
    /// Every oracle, in requirement order. [`Oracle::parse`] searches it.
    pub const ALL: [Oracle; 3] = [
        Oracle::ReferenceCompiler,
        Oracle::CrossBackend,
        Oracle::GoldenRecord,
    ];

    /// The single letter that names this oracle in the requirements. `findings.rs` builds
    /// artifact filenames of the form `outputs/<letter>-<target>-<opt>.stdout` from it.
    pub fn letter(self) -> char {
        match self {
            Oracle::ReferenceCompiler => 'a',
            Oracle::CrossBackend => 'b',
            Oracle::GoldenRecord => 'c',
        }
    }

    /// The human-readable label used in reports and failure messages. Its leading token
    /// matches the per-oracle toggle key in an expectation record, so a report line and
    /// the record that governs it name the oracle the same way.
    pub fn label(self) -> &'static str {
        match self {
            Oracle::ReferenceCompiler => "oracle_a (reference compiler)",
            Oracle::CrossBackend => "oracle_b (cross-backend)",
            Oracle::GoldenRecord => "oracle_c (golden record)",
        }
    }

    /// Parse an oracle from its letter (`a`), its record key (`oracle_a`) or its full
    /// label, ignoring surrounding whitespace. All three forms are accepted because
    /// records use the key, reports use the label, and artifact names use the letter.
    pub fn parse(text: &str) -> Option<Oracle> {
        let wanted = text.trim();
        let bare = wanted.strip_prefix("oracle_").unwrap_or(wanted);
        Oracle::ALL.iter().copied().find(|candidate| {
            if wanted == candidate.label() {
                return true;
            }
            let mut characters = bare.chars();
            characters.next() == Some(candidate.letter()) && characters.next().is_none()
        })
    }
}

impl fmt::Display for Oracle {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.label())
    }
}

impl std::str::FromStr for Oracle {
    type Err = HarnessError;

    fn from_str(text: &str) -> Result<Oracle, HarnessError> {
        Oracle::parse(text).ok_or_else(|| {
            HarnessError::new(
                "parsing an oracle identity",
                format!(
                    "{text:?} names no oracle; expected a letter, a record key or a label from: {}",
                    comma_separated(&Oracle::ALL.map(Oracle::label))
                ),
            )
        })
    }
}

/// The shape a divergence took, independently of how it was classified into a verdict.
///
/// The set is closed at six members and stays closed: a newly observed failure shape is
/// mapped onto one of these rather than appended as a seventh, so the classification table
/// in `classify.rs` remains total. The labels are the tokens an expectation record uses in
/// the `class` field of an expected-divergence marker.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum DivergenceClass {
    /// One compiler rejected a program the other accepted. The diagnostics are captured
    /// even though they are never compared.
    CompileFailure,
    /// Compilation succeeded but the artifact failed to link — most often because a
    /// target's C runtime is missing, which the environment fingerprint in a finding is
    /// what distinguishes from a compiler defect.
    LinkFailure,
    /// The program terminated on a signal instead of exiting normally. Exit status is
    /// compared as a raw wait status so this is never conflated with a numerically equal
    /// ordinary exit.
    RunCrash,
    ExitCodeMismatch,
    /// The compared stdout byte streams differ. The first divergent line and byte offset
    /// are reported, because a divergence that cannot be located cannot be minimized.
    StdoutMismatch,
    /// Execution exceeded its per-cell budget. A divergence class rather than an
    /// infrastructure error, since a program that finishes promptly under one compiler and
    /// hangs under another is a defect worth surfacing.
    Timeout,
}

impl DivergenceClass {
    /// Every divergence class, in the order `classify.rs` considers them.
    pub const ALL: [DivergenceClass; 6] = [
        DivergenceClass::CompileFailure,
        DivergenceClass::LinkFailure,
        DivergenceClass::RunCrash,
        DivergenceClass::ExitCodeMismatch,
        DivergenceClass::StdoutMismatch,
        DivergenceClass::Timeout,
    ];

    /// The token that matches the `class` field of an expected-divergence marker.
    pub fn label(self) -> &'static str {
        match self {
            DivergenceClass::CompileFailure => "compile_failure",
            DivergenceClass::LinkFailure => "link_failure",
            DivergenceClass::RunCrash => "run_crash",
            DivergenceClass::ExitCodeMismatch => "exit_code_mismatch",
            DivergenceClass::StdoutMismatch => "stdout_mismatch",
            DivergenceClass::Timeout => "timeout",
        }
    }

    /// Parse a divergence class from its token, ignoring surrounding whitespace and ASCII
    /// case. Case is ignored so a marker written in a different case is understood rather
    /// than turning a documented expected divergence into an unexplained failure.
    pub fn parse(text: &str) -> Option<DivergenceClass> {
        let wanted = text.trim();
        DivergenceClass::ALL
            .iter()
            .copied()
            .find(|candidate| wanted.eq_ignore_ascii_case(candidate.label()))
    }
}

impl fmt::Display for DivergenceClass {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.label())
    }
}

impl std::str::FromStr for DivergenceClass {
    type Err = HarnessError;

    fn from_str(text: &str) -> Result<DivergenceClass, HarnessError> {
        DivergenceClass::parse(text).ok_or_else(|| {
            HarnessError::new(
                "parsing a divergence class",
                format!(
                    "{text:?} names no divergence class; the closed set is: {}",
                    comma_separated(&DivergenceClass::ALL.map(DivergenceClass::label))
                ),
            )
        })
    }
}

/// The outcome of one comparison, from a closed and exhaustive set of six.
///
/// There is deliberately NO "skip because unsupported" verdict, and no code path anywhere
/// in the harness may silently drop a cell. An oracle whose tooling is genuinely absent is
/// reported as [`Verdict::Unavailable`] — loudly, and in the summary — which is what keeps
/// a modest environment from masquerading as a passing run.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Verdict {
    /// The compared outputs agree exactly: identical stdout bytes and identical exit
    /// status.
    Pass,
    /// A divergence that a marker in the program's own expectation record explains, citing
    /// a limitation the repository already documents. A marked program still compiles and
    /// still runs the feature; a marker changes how a divergence is CLASSIFIED, never
    /// whether the feature is EXERCISED.
    XFail,
    /// A marker is present but the divergence it describes has disappeared.
    ///
    /// This fails the run by default, following the standard convention that unexpected
    /// success is a failure. The justification is asymmetric cost: a stale marker is stale
    /// documented knowledge that will mislead the next reader, whereas retiring it is a
    /// trivial test-only edit. An environment-variable escape hatch exists for a
    /// marker-retirement window, and this verdict is always listed separately and
    /// prominently in the summary so it can never pass unnoticed.
    XPass,
    /// An undocumented divergence. It yields a self-contained artifact directory — the
    /// minimized reproducer, its expectation record, a manifest, exact reproduction
    /// commands, the captured outputs per compiler and per backend, an environment
    /// fingerprint and the computed difference — plus an entry in the findings register.
    ///
    /// A finding is a deliverable, not a defect to patch: no compiler source change is
    /// ever made in response to one.
    Finding,
    /// A divergence with no explanation at all, or an internal inconsistency in the suite
    /// itself. Fails the run.
    Fail,
    /// An oracle's tooling is genuinely absent from the environment, so this comparison
    /// could not be attempted.
    ///
    /// Always reported, never silent, and never a pass. Under the strict setting intended
    /// for continuous integration — where the toolchain is installed deliberately, so a
    /// missing oracle indicates a broken workflow rather than a modest machine — the
    /// driver escalates this to a failure.
    Unavailable,
}

impl Verdict {
    /// Every verdict, in reporting order. `report.rs` iterates it so the summary tally is
    /// complete and ordered, including zero rows.
    pub const ALL: [Verdict; 6] = [
        Verdict::Pass,
        Verdict::XFail,
        Verdict::XPass,
        Verdict::Finding,
        Verdict::Fail,
        Verdict::Unavailable,
    ];

    /// True for exactly the two verdicts that make a run fail: an unexplained failure and
    /// an unexpected success.
    ///
    /// The four verdicts permitted in a passing run are [`Verdict::Pass`],
    /// [`Verdict::XFail`], [`Verdict::Finding`] and [`Verdict::Unavailable`] — each of
    /// which is still reported in full. A finding does not fail the run because findings
    /// are deliverables; an unavailable oracle does not fail the run by default because
    /// the environment, not the compiler, is what is incomplete.
    pub fn fails_run(self) -> bool {
        matches!(self, Verdict::Fail | Verdict::XPass)
    }

    /// The uppercase report token, spelled as the requirements spell it.
    pub fn label(self) -> &'static str {
        match self {
            Verdict::Pass => "PASS",
            Verdict::XFail => "XFAIL",
            Verdict::XPass => "XPASS",
            Verdict::Finding => "FINDING",
            Verdict::Fail => "FAIL",
            Verdict::Unavailable => "UNAVAILABLE",
        }
    }

    /// Parse a verdict from its report token, ignoring surrounding whitespace and ASCII
    /// case, so that `report.rs` can re-read the machine-readable rows it wrote.
    pub fn parse(text: &str) -> Option<Verdict> {
        let wanted = text.trim();
        Verdict::ALL
            .iter()
            .copied()
            .find(|candidate| wanted.eq_ignore_ascii_case(candidate.label()))
    }
}

impl fmt::Display for Verdict {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.label())
    }
}

impl std::str::FromStr for Verdict {
    type Err = HarnessError;

    fn from_str(text: &str) -> Result<Verdict, HarnessError> {
        Verdict::parse(text).ok_or_else(|| {
            HarnessError::new(
                "parsing a verdict",
                format!(
                    "{text:?} names no verdict; the closed set is: {}",
                    comma_separated(&Verdict::ALL.map(Verdict::label))
                ),
            )
        })
    }
}

// Two kinds of text reach a report, a summary or a reproduction script from outside this
// harness: free text a maintainer wrote into an expectation record, and a banner an external
// tool printed when asked to identify itself. Neither may be emitted verbatim.
//
// A tab forges a column in a tab-separated report and can therefore relabel a verdict. A
// terminal escape sequence can hide a line, overwrite one already printed, or repaint a
// FINDING as a PASS in a maintainer's scrollback. A carriage return can erase the line it
// ends. None of these say anything about the compiler, and all of them corrupt the artifact
// the requirements ask for, so the functions below are the single place where such text is
// made safe. `manifest.rs` additionally REJECTS control characters at parse time, which is
// stronger; these functions are what protect the text the suite cannot refuse to accept —
// diagnostics naming an offending value, and the identification banner of a tool the suite
// did not write.

/// Characters that are not classed as controls but corrupt a report in exactly the same way,
/// and are therefore escaped alongside them.
///
/// The first twelve are the Unicode bidirectional formatting characters. They reorder the
/// *rendering* of text without changing its bytes, so a line can be made to display something
/// other than what it says — the mechanism behind the "Trojan Source" class of attack, and in
/// a verdict table the difference between reading `FAIL` and reading `PASS`. The last two are
/// the line and paragraph separators, which several Markdown and terminal renderers treat as
/// line breaks, so leaving them intact would let one report row become two.
const REPORT_HOSTILE_FORMATTING: &[char] = &[
    '\u{061c}', // ARABIC LETTER MARK
    '\u{200e}', // LEFT-TO-RIGHT MARK
    '\u{200f}', // RIGHT-TO-LEFT MARK
    '\u{202a}', // LEFT-TO-RIGHT EMBEDDING
    '\u{202b}', // RIGHT-TO-LEFT EMBEDDING
    '\u{202c}', // POP DIRECTIONAL FORMATTING
    '\u{202d}', // LEFT-TO-RIGHT OVERRIDE
    '\u{202e}', // RIGHT-TO-LEFT OVERRIDE
    '\u{2066}', // LEFT-TO-RIGHT ISOLATE
    '\u{2067}', // RIGHT-TO-LEFT ISOLATE
    '\u{2068}', // FIRST STRONG ISOLATE
    '\u{2069}', // POP DIRECTIONAL ISOLATE
    '\u{2028}', // LINE SEPARATOR
    '\u{2029}', // PARAGRAPH SEPARATOR
];

/// Whether `character` cannot appear literally in a report, a summary, a fingerprint or a
/// diagnostic without changing how that text behaves rather than merely what it says.
///
/// True for every character [`char::is_control`] reports — the C0 range, the delete character
/// and the C1 range — and for every entry of [`REPORT_HOSTILE_FORMATTING`].
///
/// This predicate is the **single authority** on the question, and it is deliberately shared
/// rather than reimplemented: [`sanitize_text_for_report`] escapes exactly the characters it
/// selects, [`CellKey::validate_stem`] refuses a name containing one, and `manifest.rs`
/// rejects one anywhere in a record — permitting only the line feed, and only inside a
/// heredoc body, by testing `must_escape_for_report(c) && c != '\n'`. One predicate with three
/// consumers cannot drift; three hand-written character tests would.
pub fn must_escape_for_report(character: char) -> bool {
    character.is_control() || REPORT_HOSTILE_FORMATTING.contains(&character)
}

/// Render text safely for a report, a summary, a fingerprint or a diagnostic.
///
/// Every character [`must_escape_for_report`] selects is replaced by a visible escape. The text can
/// then be read but can no longer act: no tab can forge a tab-separated column, no escape
/// introducer can begin a terminal sequence, no carriage return can erase the line it ends,
/// and no directional override can make a line render as something other than what it says.
/// The line feed is escaped too, because every consumer of this function writes a single line
/// and an embedded newline would split one record into two.
///
/// Escapes are written `\xNN` for a code point that fits in a byte and `\u{NNNN}` otherwise,
/// both of which are unambiguous and searchable. Printable text, including every non-ASCII
/// character that is neither a control nor a formatting character, passes through unchanged, so
/// a legitimate banner remains exactly as its tool printed it.
pub fn sanitize_text_for_report(raw: &str) -> String {
    let mut safe = String::with_capacity(raw.len());
    for character in raw.chars() {
        let code_point = u32::from(character);
        if !must_escape_for_report(character) {
            safe.push(character);
        } else if code_point <= 0xff {
            safe.push_str(&format!("\\x{code_point:02x}"));
        } else {
            safe.push_str(&format!("\\u{{{code_point:04x}}}"));
        }
    }
    safe
}

/// The characters a word may contain and still be safe to write into a shell script without
/// quoting.
///
/// Deliberately conservative: only characters that no POSIX shell treats specially in any
/// position. Everything else — whitespace, every redirection and list operator, every
/// quoting character, the expansion introducers, the pattern characters, the comment
/// character and the home-directory character — forces the quoted form.
const SHELL_SAFE_PUNCTUATION: &[char] = &['.', '_', '/', ':', '=', '@', '%', '+', ',', '-'];

/// Quote one word so that a POSIX shell reproduces it exactly.
///
/// A non-empty word made only of ASCII alphanumerics and [`SHELL_SAFE_PUNCTUATION`] is
/// returned unchanged, which keeps an ordinary command line readable. Anything else is
/// wrapped in single quotes, with each embedded single quote written as `'\''` — the standard
/// idiom, and the only one that is correct for **every** byte, because a single-quoted string
/// in a POSIX shell has no escape processing at all.
///
/// This is what makes a finding's reproduction commands "exact and copy-pasteable" rather
/// than merely plausible. A checkout path containing a space would otherwise split into two
/// arguments, and a path containing a semicolon, a backquote or a `$(` would be *executed*
/// rather than passed — which is precisely the difference between a reproduction script and
/// an injection. Control characters cannot reach this function from an expectation record,
/// because `manifest.rs` rejects them at parse time; a control character arriving from a
/// filesystem path is preserved verbatim inside the quotes, which is the only rendering that
/// still reproduces the path.
pub fn posix_quote(word: &str) -> String {
    let is_safe = !word.is_empty()
        && word
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || SHELL_SAFE_PUNCTUATION.contains(&c));
    if is_safe {
        return String::from(word);
    }
    let mut quoted = String::with_capacity(word.len() + 2);
    quoted.push('\'');
    for character in word.chars() {
        if character == '\'' {
            quoted.push_str("'\\''");
        } else {
            quoted.push(character);
        }
    }
    quoted.push('\'');
    quoted
}

/// Render an argument vector as a single POSIX shell line, each element quoted by
/// [`posix_quote`].
pub fn posix_command_line(argv: &[String]) -> String {
    argv.iter()
        .map(|word| posix_quote(word))
        .collect::<Vec<_>>()
        .join(" ")
}

/// Separator between the components of a cell slug.
///
/// A plus sign is chosen for one reason: [`encode_slug_component`] escapes it wherever it
/// occurs inside a component, so it never appears in encoded output. Splitting a slug on this
/// character therefore recovers exactly the four components that produced it, which is what
/// makes [`CellKey::slug`] injective rather than merely unlikely to collide. It is also safe
/// everywhere the harness uses a slug: no shell assigns it a special meaning, and no
/// supported filesystem reserves it.
const SLUG_SEPARATOR: char = '+';

/// Introducer for an escape sequence inside an encoded slug component.
///
/// The percent sign is itself escaped, as `%25`, so an escape sequence is always exactly
/// three characters long and can never be produced by passthrough input. That is what makes
/// the encoding reversible, and reversibility is precisely the property collision freedom
/// needs. Nothing in the harness decodes a slug; the escape is chosen to be reversible so
/// that collision freedom is a fact about the function rather than a hope about its inputs.
const SLUG_ESCAPE: char = '%';

/// Upper-case hexadecimal digits, indexed by nibble value.
///
/// Both index expressions in [`encode_slug_component`] are four bits wide, so the lookup
/// cannot be out of range: the encoder needs no fallback arm and cannot panic. That matters
/// because a slug is rendered on the failure path of every cell, where a panic would replace
/// a diagnosable divergence with a harness crash.
const SLUG_HEX_DIGITS: &[u8; 16] = b"0123456789ABCDEF";

/// Append one slug component to `encoded`, escaping it injectively into the passthrough
/// alphabet `[A-Za-z0-9_]` plus [`SLUG_ESCAPE`]-introduced hexadecimal escapes.
///
/// This is the single authority for turning an identity component into path text: every slug,
/// every workspace directory and every report row derives from it, so an identity can never be
/// rendered two ways.
///
/// A byte of the passthrough alphabet — ASCII letters, ASCII digits and the underscore — is
/// emitted verbatim, so the canonical corpus names stay readable: `01_integer_conversions`
/// encodes to itself. **Every other byte** — including the separator, the escape character
/// itself, and each individual byte of a multi-byte UTF-8 character — becomes [`SLUG_ESCAPE`]
/// followed by that byte's two upper-case hexadecimal digits. Encoding operates on bytes rather
/// than characters, so the result is always pure ASCII.
///
/// The mapping is injective, and the argument is short enough to check by hand: the passthrough
/// alphabet and the escape character are disjoint, an escape sequence has a fixed length of
/// three, and the two hexadecimal digits name exactly one byte, so the output can be read left
/// to right to recover the input byte sequence exactly. Folding could not offer that. A scheme
/// that folded every character outside the alphabet to a single underscore and collapsed runs
/// made `a_b`, `a__b`, `a b` and `a/b` indistinguishable, and made an empty name
/// indistinguishable from a name that was literally `unnamed`; under this encoding those six
/// inputs render as `a_b`, `a__b`, `a%20b`, `a%2Fb`, the empty string and `unnamed`.
///
/// Two further properties follow from that alphabet, and they are what make a slug safe to join
/// onto a path rather than merely tidy:
///
/// - The separator can never occur inside an encoded component, so splitting a slug on it
///   recovers exactly the components that produced it.
/// - No encoded component can be `.` or `..`, or contain a path separator, because the dot, the
///   forward slash and the backslash are all outside the passthrough alphabet. A slug is
///   therefore always a single path component that cannot traverse upwards, so joining it to
///   [`work_root`] always yields a direct child of that root.
///
/// Injectivity is what removes the need for a lock. The slug alone decides a cell's workspace
/// directory and the feature-area tests run concurrently, so under a lossy fold two distinct
/// identities that differed only outside the safe alphabet would share one workspace and
/// overwrite each other's artifacts mid-run — surfacing as an inexplicable divergence rather
/// than an error. A separate duplicate-slug detection pass would merely assert that theorem.
///
/// The mapping is a pure function of its input: no clock, no process identifier, no counter, no
/// randomness, no environment.
fn encode_slug_component(raw: &str, encoded: &mut String) {
    for byte in raw.bytes() {
        if byte.is_ascii_alphanumeric() || byte == b'_' {
            encoded.push(char::from(byte));
        } else {
            encoded.push(SLUG_ESCAPE);
            encoded.push(char::from(SLUG_HEX_DIGITS[usize::from(byte >> 4)]));
            encoded.push(char::from(SLUG_HEX_DIGITS[usize::from(byte & 0x0f)]));
        }
    }
}

/// Identifies exactly one cell of the build matrix: one program, on one target, at one
/// optimization level.
///
/// This is the unit of work the harness is organized around, and the sole input to a
/// cell's workspace path.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct CellKey {
    pub area: String,
    pub program: String,
    pub target: Target,
    pub opt: OptLevel,
}

impl CellKey {
    /// A deterministic, collision-free, filesystem-safe rendering of this identity, for
    /// example `01_integer_conversions+004_narrowing_conversions+aarch64+O1`.
    ///
    /// Collision freedom is a property of the rendering rather than an assumption about the
    /// corpus. Each component is escaped by [`encode_slug_component`], which is injective and
    /// never emits [`SLUG_SEPARATOR`], so the separators mark exactly the four component
    /// boundaries and two distinct identities cannot render to the same slug. That is what
    /// removes the need for any lock — two concurrent cells own distinct workspaces by
    /// construction, and no duplicate-detection pass is needed because such a pass would merely
    /// assert the theorem — and it holds for a curated finding reproducer whose name was never
    /// part of the numbered corpus just as it holds for `004_narrowing_conversions`.
    ///
    /// The join is positional: a separator is written before every component after the first,
    /// always three of them, never "one between the non-empty ones". That is load-bearing in
    /// the argument above, because a join that emitted a separator only when something had
    /// already been written would drop a boundary whenever a preceding component encoded to
    /// empty text.
    ///
    /// The result is always exactly one path component: it can contain no path separator of
    /// either spelling and can be neither `.` nor `..`, because the encoder escapes every byte
    /// outside `[A-Za-z0-9_]`. Joining it onto [`work_root`] therefore cannot reach outside the
    /// workspace root, which is the mechanical half of the hermeticity contract.
    ///
    /// The slug contains no process identifier, no timestamp and no counter, so the same
    /// identity yields the same slug in every process and on every run. That is what makes a
    /// retained workspace reproducible and inspectable after the fact.
    pub fn slug(&self) -> String {
        let components: [&str; 4] = [
            self.area.as_str(),
            self.program.as_str(),
            self.target.short_name(),
            self.opt.short(),
        ];
        let mut rendered = String::new();
        for (index, component) in components.iter().enumerate() {
            if index > 0 {
                rendered.push(SLUG_SEPARATOR);
            }
            encode_slug_component(component, &mut rendered);
        }
        rendered
    }

    /// Reject an area or program name that is not a canonical corpus stem.
    ///
    /// The encoding in [`encode_slug_component`] is injective, so a strange name could
    /// never cause a workspace collision. This check exists for the other half of the
    /// problem: a name that is not a canonical stem means the identity itself was
    /// assembled wrongly — from an empty string, from a path fragment rather than a stem,
    /// or from text carrying control characters that would corrupt a report — and every one
    /// of those is a corpus or caller defect that must surface as an explanatory hard
    /// failure rather than as a strangely named directory nobody can trace back.
    ///
    /// A canonical stem is non-empty, is neither `.` nor `..`, carries no path separator of
    /// either spelling, and contains no whitespace and no control character. The
    /// corpus-wide convention is narrower still — lower-case ASCII, digits and underscores,
    /// as in `04_bitfields` and `003_compound_assignment` — but the check deliberately
    /// stops at the properties that actually threaten correctness, so that a future area or
    /// program name is not rejected for a stylistic reason.
    fn validate_identity(&self) -> HarnessResult<()> {
        CellKey::validate_stem("area", &self.area)?;
        CellKey::validate_stem("program", &self.program)
    }

    /// Apply the canonical-stem rules to one named component of this identity.
    ///
    /// Every diagnostic renders the offending value through [`sanitize_text_for_report`],
    /// so a name carrying a terminal escape cannot smuggle that escape into the failure
    /// message it provokes.
    fn validate_stem(role: &str, value: &str) -> HarnessResult<()> {
        let context = || format!("validating the {role} name of a cell identity");
        if value.is_empty() {
            return Err(HarnessError::new(
                context(),
                format!(
                    "the {role} name is empty; a cell identity is assembled from the corpus \
                     directory and file names, so an empty one means the identity was built \
                     from something other than a discovered corpus path"
                ),
            ));
        }
        let shown = sanitize_text_for_report(value);
        if value == "." || value == ".." {
            return Err(HarnessError::new(
                context(),
                format!(
                    "the {role} name is {shown:?}, which names a directory relative to another \
                     rather than a corpus stem; every area and program name is a plain stem"
                ),
            ));
        }
        if value.contains('/') || value.contains(std::path::MAIN_SEPARATOR) {
            return Err(HarnessError::new(
                context(),
                format!(
                    "the {role} name {shown:?} contains a path separator; the identity carries \
                     the area directory name and the program file stem, never a path fragment, \
                     because the cell's own paths are derived from the corpus root instead"
                ),
            ));
        }
        if value
            .chars()
            .any(|candidate| must_escape_for_report(candidate) || candidate.is_whitespace())
        {
            return Err(HarnessError::new(
                context(),
                format!(
                    "the {role} name {shown:?} contains whitespace or a character that cannot \
                     appear literally in a report; a stem carries neither, because it is written \
                     into report rows, workspace paths and reproduction commands, where such a \
                     character could forge a column, hide a line, or make a row render as \
                     something other than what it says"
                ),
            ));
        }
        Ok(())
    }
}

impl fmt::Display for CellKey {
    /// Human-readable form for failure messages, for example
    /// `04_bitfields/003_compound_assignment @ aarch64-linux-gnu -O1`.
    ///
    /// The two textual components are rendered through [`sanitize_text_for_report`]. A
    /// [`CellKey`] built from a discovered corpus path has already passed
    /// [`CellKey::validate_stem`] and is therefore unchanged by that call, but the fields are
    /// public and this rendering reaches report rows and the tab-separated summary, so the
    /// safety is applied at the point of output rather than assumed from the point of
    /// construction.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "{}/{} @ {} {}",
            sanitize_text_for_report(&self.area),
            sanitize_text_for_report(&self.program),
            self.target,
            self.opt
        )
    }
}

/// One fully resolved cell: its identity, the two files that define it, and the single
/// directory it is permitted to write into.
///
/// Both paths travel with the identity rather than being recomputed by each consumer,
/// because a cell must be reproducible from its source file and its expectation record
/// alone.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct Cell {
    pub key: CellKey,
    /// Canonical absolute path to the C program.
    ///
    /// This is the fully resolved path [`Cell::new`] proved to be a regular file inside the
    /// corpus, not the possibly indirect spelling that was handed in. Storing the resolved
    /// form means every consumer compiles, reads and reports the same file the constructor
    /// validated, and that a reproduction command carries a path with no `..` segment and no
    /// intermediate symbolic link for a maintainer to resolve by hand.
    pub source: PathBuf,
    /// Canonical absolute path to the sibling expectation record that governs this program.
    pub expectation: PathBuf,
    /// The one directory this cell may write into, derived from [`work_root`] and
    /// [`CellKey::slug`].
    pub workspace: PathBuf,
}

impl Cell {
    /// Resolve a cell and derive its workspace.
    ///
    /// The workspace is derived rather than supplied, so hermeticity is decided in exactly one
    /// place: every cell writes beneath [`work_root`] and nowhere else. The two input paths are
    /// stored resolved, so a report and a reproduction command always name the files that were
    /// actually read.
    ///
    /// # Errors
    ///
    /// Validation is strict on purpose: every rejection below is a broken corpus invariant
    /// rather than a condition an environment can legitimately produce, so it becomes an
    /// explanatory hard failure naming the cell — never a quiet skip and never an opaque panic.
    ///
    /// Absoluteness and the right extension are necessary but nowhere near sufficient: both are
    /// satisfied by `/etc/shadow.c` and by a committed symbolic link pointing anywhere on the
    /// machine. Validation therefore covers three things:
    ///
    /// - the identity, through [`CellKey::validate_identity`]: the area and program names must
    ///   be canonical stems, so an identity assembled from an empty string, a path fragment or
    ///   text carrying control characters fails here rather than becoming a strangely named
    ///   directory nobody can trace back;
    /// - the read half of hermeticity, through [`require_contained_corpus_file`]: each input
    ///   must be an absolute path to a regular, non-symbolic-link file that resolves strictly
    ///   inside the corpus and carries the extension its role requires. A symbolic link is
    ///   refused rather than followed, because following one is how a corpus path comes to name
    ///   a file anywhere on the machine while every report still shows the corpus path — and a
    ///   discovered file is not merely read but compiled and *executed*;
    /// - the identity-to-location agreement: the two inputs must be same-directory siblings
    ///   sharing one stem, and the resolved location must agree with the key — the containing
    ///   directory with [`CellKey::area`] and the stem with [`CellKey::program`]. Without that
    ///   agreement a cell could be reported under one identity while compiling a different
    ///   program, and the workspace path, derived from the key alone, would name the wrong cell.
    ///
    /// The derived workspace is then asserted to be a direct child of [`work_root`]. That
    /// already follows from the slug being a single path component, and it is re-checked here
    /// because it is the one line on which the whole hermeticity argument rests.
    ///
    /// The two path fields of the returned cell hold the **canonical** forms, so a consumer can
    /// never operate on a different file from the one that was validated, and a reproduction
    /// command carries a path with no `..` segment and no intermediate symbolic link for a
    /// maintainer to resolve by hand.
    pub fn new(key: CellKey, source: PathBuf, expectation: PathBuf) -> HarnessResult<Cell> {
        let context = format!("resolving the input paths for {key}");
        key.validate_identity()?;
        let source = require_contained_corpus_file(&context, "source", &source, "c")?;
        let expectation = require_contained_corpus_file(
            &context,
            "expectation record",
            &expectation,
            "expected",
        )?;
        Cell::require_sibling_pair(&context, &source, &expectation)?;
        Cell::require_identity(&context, &key, &source)?;

        let root = work_root();
        let workspace = root.join(key.slug());
        if workspace.parent() != Some(root.as_path()) {
            return Err(HarnessError::new(
                format!("deriving the workspace path for {key}"),
                format!(
                    "{} is not a direct child of the work root {}; every cell writes into one \
                     directory immediately beneath that root and nowhere else, which is the \
                     property the suite's hermeticity rests on",
                    workspace.display(),
                    root.display()
                ),
            ));
        }
        Ok(Cell {
            key,
            source,
            expectation,
            workspace,
        })
    }

    /// Reject a program and record that are not same-directory siblings of one stem.
    ///
    /// The pairing is what makes "source file, build commands, and expected output recorded
    /// together" literally true, so a record borrowed from a neighbouring program — the one
    /// mistake that would leave every individual path check satisfied — is refused here.
    fn require_sibling_pair(context: &str, source: &Path, expectation: &Path) -> HarnessResult<()> {
        if source.parent() != expectation.parent() {
            return Err(HarnessError::new(
                context,
                format!(
                    "the program {} and the expectation record {} are not in the same directory; \
                     every record is the sibling of the program it governs, which is what makes \
                     a cell reproducible from those two files alone",
                    source.display(),
                    expectation.display()
                ),
            ));
        }
        if source.file_stem() != expectation.file_stem() {
            return Err(HarnessError::new(
                context,
                format!(
                    "the program {} and the expectation record {} do not share a file stem; a \
                     record that governs a different program is the one mistake every individual \
                     path check would still accept",
                    source.display(),
                    expectation.display()
                ),
            ));
        }
        Ok(())
    }

    /// Reject a resolved program path that disagrees with the identity it is being given.
    fn require_identity(context: &str, key: &CellKey, source: &Path) -> HarnessResult<()> {
        let area = source
            .parent()
            .and_then(Path::file_name)
            .and_then(|name| name.to_str());
        if area != Some(key.area.as_str()) {
            return Err(HarnessError::new(
                context,
                format!(
                    "the program {} lives in the feature-area directory {:?}, but this cell claims \
                     the area {:?}; the workspace path is derived from the identity alone, so a \
                     disagreement would file a cell's artifacts under another cell's name",
                    source.display(),
                    area.unwrap_or("<unreadable>"),
                    key.area
                ),
            ));
        }
        let stem = source.file_stem().and_then(|stem| stem.to_str());
        if stem != Some(key.program.as_str()) {
            return Err(HarnessError::new(
                context,
                format!(
                    "the program {} has the file stem {:?}, but this cell claims the program {:?}; \
                     a cell reported under one identity while compiling another program would make \
                     every verdict about it meaningless",
                    source.display(),
                    stem.unwrap_or("<unreadable>"),
                    key.program
                ),
            ));
        }
        Ok(())
    }
}

impl fmt::Display for Cell {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "{} [source {}, expectation {}, workspace {}]",
            self.key,
            self.source.display(),
            self.expectation.display(),
            self.workspace.display()
        )
    }
}

/// One accumulated verdict: what a single oracle concluded about a single cell.
///
/// Outcomes are accumulated rather than asserted one at a time, because each area test
/// must enumerate every result in its report and stopping at the first divergence would
/// truncate it. Keying by oracle as well as by cell is what lets a construct be excluded
/// from one oracle while remaining fully compared under the others.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct Outcome {
    pub key: CellKey,
    pub oracle: Oracle,
    pub verdict: Verdict,
    /// The shape of the divergence, when there was one. `None` for an agreement and for an
    /// oracle that could not be attempted.
    pub class: Option<DivergenceClass>,
    /// Identifier of the expected-divergence marker that explains this outcome, present for
    /// an expected divergence and for an unexpected success, absent otherwise.
    pub marker_id: Option<String>,
    /// Everything a reader needs to understand the outcome without re-running it: the first
    /// divergent line and byte offset, both exit statuses, and the command lines involved.
    pub detail: String,
}

impl Outcome {
    /// Record one outcome.
    ///
    /// An empty `detail` is replaced with a sentence naming the verdict, the oracle and the
    /// cell, because a run-failing outcome carrying an opaque message is what makes a real
    /// divergence impossible to act on.
    pub fn new(
        key: CellKey,
        oracle: Oracle,
        verdict: Verdict,
        class: Option<DivergenceClass>,
        marker_id: Option<String>,
        detail: impl Into<String>,
    ) -> Outcome {
        let supplied = detail.into();
        let detail = if supplied.trim().is_empty() {
            let severity = if verdict.fails_run() {
                "this verdict fails the run, so the absent detail is itself a defect in the \
                 caller that recorded it"
            } else {
                "no further detail was recorded"
            };
            format!("{verdict} from {oracle} for {key} carries no detail: {severity}")
        } else {
            supplied
        };
        Outcome {
            key,
            oracle,
            verdict,
            class,
            marker_id,
            detail,
        }
    }
}

impl fmt::Display for Outcome {
    /// One-line rendering used verbatim in both the driver's verdict table and its failure
    /// messages, so a failing run reproduces the same text the report contains.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "[{}] {} {}", self.verdict, self.oracle, self.key)?;
        if let Some(class) = self.class {
            write!(f, " (class {class})")?;
        }
        if let Some(marker) = &self.marker_id {
            write!(f, " (marker {marker})")?;
        }
        write!(f, ": {}", self.detail)
    }
}

/// A harness failure that is the suite's or the corpus's fault rather than the
/// environment's.
///
/// A tool an environment can legitimately lack is not an error: it becomes
/// [`Verdict::Unavailable`] and is reported in the summary. This type is reserved for a
/// broken invariant — an unreadable corpus directory, an absent compiler under test, a
/// marker citing a document that does not exist — and always surfaces as a hard failure.
///
/// Context and cause are carried separately so a message says what the harness was doing
/// as well as what went wrong, which makes a failure actionable without a stack trace.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct HarnessError {
    /// What the harness was attempting, phrased as a gerund, for example
    /// `resolving the source path for 04_bitfields/002_read_write @ i686-linux-gnu -O1`.
    pub context: String,
    /// What went wrong, in enough detail to act on without re-running.
    pub cause: String,
}

impl HarnessError {
    /// Build an error from its context and its cause.
    pub fn new(context: impl Into<String>, cause: impl Into<String>) -> HarnessError {
        HarnessError {
            context: context.into(),
            cause: cause.into(),
        }
    }
}

impl fmt::Display for HarnessError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "conformance harness failed while {}: {}",
            self.context, self.cause
        )
    }
}

impl std::error::Error for HarnessError {}

impl From<std::io::Error> for HarnessError {
    /// Adapt a filesystem or process error so the question-mark operator works throughout
    /// the harness.
    ///
    /// The context is generic, so a call site that knows what it was doing should build the
    /// error with [`HarnessError::new`] instead. The underlying message is preserved
    /// verbatim.
    fn from(error: std::io::Error) -> HarnessError {
        HarnessError::new(
            "performing a filesystem or process operation",
            error.to_string(),
        )
    }
}

/// Result alias used throughout the harness.
pub type HarnessResult<T> = Result<T, HarnessError>;

// Every filesystem location the harness touches is derived from the roots below, so
// hermeticity can be checked in one place: the suite reads a program's source and its
// expectation record, and writes only beneath the work, report and findings roots.

/// Absolute path to the package root, taken from the manifest directory Cargo provides at
/// compile time.
///
/// Resolved from the manifest directory rather than the working directory because
/// `cargo test` makes no guarantee about a test process's working directory.
pub fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// Absolute path to the corpus root, which holds the feature-area directories, the
/// registers, the fixture header, the maintenance tooling and the curated findings.
///
/// The corpus is discovered by scanning this directory, so adding a program takes two new
/// files and no harness change.
pub fn corpus_root() -> PathBuf {
    manifest_dir().join("tests").join("conformance")
}

/// Absolute path to the Cargo build directory, the only place the harness writes.
///
/// A configured target directory is honoured, so a build that redirects its output does not
/// leave the harness writing into a directory the build does not own. A relative
/// configured value is resolved against the package root rather than the working
/// directory, so the result is absolute whenever [`manifest_dir`] is.
pub fn build_root() -> PathBuf {
    let configured = std::env::var_os("CARGO_TARGET_DIR").filter(|value| !value.is_empty());
    match configured {
        Some(value) => {
            let configured_root = PathBuf::from(value);
            if configured_root.is_absolute() {
                configured_root
            } else {
                manifest_dir().join(configured_root)
            }
        }
        None => manifest_dir().join("target"),
    }
}

/// Root of the per-cell workspaces, one subdirectory per [`CellKey::slug`].
///
/// A workspace is removed once its cell has passed and retained when it has not, so a
/// failing cell leaves behind the artifacts needed to investigate it. The retention setting
/// in `env.rs` keeps passing workspaces too.
pub fn work_root() -> PathBuf {
    build_root().join("conformance-work")
}

/// Root of the run's reports: one Markdown and one tab-separated file per feature area,
/// plus the run summary in both forms.
///
/// Each area writes only its own file, so concurrently executing areas never contend, and
/// the summary is finalized by a check-and-write that succeeds once every area file exists,
/// which needs no ordering between tests.
pub fn report_root() -> PathBuf {
    build_root().join("conformance-report")
}

/// Root of the findings generated by the current run.
///
/// Distinct from the curated finding set committed under [`corpus_root`], which is a
/// deliverable: no function here returns a writable handle to it, so an in-progress run
/// cannot pollute it.
pub fn findings_root() -> PathBuf {
    build_root().join("conformance-findings")
}

/// The corpus root with every symbolic link resolved.
///
/// Resolved rather than merely joined, because containment can only be decided between two
/// paths that have both been reduced to their real locations: comparing a real path against an
/// unresolved root would reject a legitimate file whenever the build tree itself sits behind a
/// link, and comparing an unresolved path against an unresolved root would accept an escape.
///
/// An unreadable corpus root is a hard failure. It is the one directory the suite cannot do
/// without, and a run that quietly discovered no programs would report success while testing
/// nothing.
pub fn canonical_corpus_root() -> HarnessResult<PathBuf> {
    let declared = corpus_root();
    declared.canonicalize().map_err(|error| {
        HarnessError::new(
            "resolving the corpus root",
            format!(
                "{} could not be resolved: {error}; the corpus is the directory the suite reads \
                 every program and every expectation record from, so a root that cannot be \
                 resolved is a hard failure rather than an empty run",
                declared.display()
            ),
        )
    })
}

// Constraint four permits the suite to compile and execute the programs it discovers, and
// forbids those programs from touching anything outside the sandbox working directory. That
// permission is only safe while the set of things the suite will compile is exactly the set
// of files committed under the corpus root, because a program is an input the suite hands to
// a compiler and then *runs*. A file that reaches the matrix from elsewhere is arbitrary code
// execution with the suite's privileges, and a file the suite merely *reads* from elsewhere
// is disclosure: its bytes are copied into a finding artifact and a report.
//
// Two properties are therefore established before any discovered path is used, and they are
// established here so that every caller — cell construction, record loading, area discovery —
// gets the same answer:
//
//   1. the path names an existing regular file, not a symbolic link and not a directory,
//      device node, socket or FIFO;
//   2. after canonicalization the path lies strictly beneath the canonical corpus root.
//
// The order matters. Testing the link status first, with `symlink_metadata`, means a committed
// symbolic link is refused outright rather than silently followed — a link is not a program,
// and accepting one would let the corpus name a file it does not contain. Canonicalizing
// second means an intermediate directory that *is* a link is resolved and then judged on where
// it actually leads, so a link that stays inside the corpus is harmless and one that escapes
// upward is rejected by the containment test rather than by a special case.
//
// Containment is compared component by component rather than by string prefix. A prefix test
// on text answers "does `/corpus-evil/x` start with `/corpus`" with yes, which is wrong; a
// component test answers it with no, because `corpus-evil` and `corpus` are different
// components. This is the classic path-prefix confusion, and comparing components is the only
// spelling that does not have it.

/// Require that `path` is an existing regular file, rejecting symbolic links.
///
/// `context` describes the operation in progress and is used verbatim in the error, so the
/// failure names what the harness was doing as well as what was wrong.
///
/// [`std::fs::symlink_metadata`] is used rather than [`std::fs::metadata`] precisely because
/// it does **not** follow a final symbolic link: the link itself is inspected, so a link is
/// reported as a link and refused. Following it would mean the corpus could name any file on
/// the machine — `/etc/shadow` renamed to something ending in `.c` satisfies every other
/// check this harness makes — and that file's bytes would then be compiled, executed and
/// copied into a report.
pub fn require_regular_file(context: &str, path: &Path) -> HarnessResult<()> {
    let metadata = std::fs::symlink_metadata(path).map_err(|error| {
        HarnessError::new(
            String::from(context),
            format!(
                "{} could not be inspected: {error}; every path the suite compiles, runs or \
                 reads must be a regular file that exists in the checkout",
                path.display()
            ),
        )
    })?;
    let file_type = metadata.file_type();
    if file_type.is_symlink() {
        return Err(HarnessError::new(
            String::from(context),
            format!(
                "{} is a symbolic link; the suite refuses to follow one, because a link lets the \
                 corpus name a file it does not contain and every discovered file is compiled, \
                 executed and copied into a report",
                path.display()
            ),
        ));
    }
    if !file_type.is_file() {
        return Err(HarnessError::new(
            String::from(context),
            format!(
                "{} is not a regular file; a directory, device node, socket or FIFO cannot be a \
                 program or an expectation record, and reading one can block indefinitely",
                path.display()
            ),
        ));
    }
    Ok(())
}

/// Require that `path` lies strictly beneath `root` once both have been canonicalized, and
/// return the canonical form of `path`.
///
/// Both sides are canonicalized so that the comparison is between two fully resolved,
/// absolute, link-free paths. Canonicalizing only one side would compare a resolved path
/// against an unresolved root and could reject a legitimate file — for instance when the
/// checkout itself is reached through a symbolic link, which is ordinary on a build machine.
///
/// "Strictly beneath" means the root's component sequence is a proper prefix of the path's.
/// The root itself is therefore not contained in itself, which is correct here: a root is a
/// directory and every caller is asking about a file.
pub fn ensure_within(context: &str, root: &Path, path: &Path) -> HarnessResult<PathBuf> {
    let canonical_root = root.canonicalize().map_err(|error| {
        HarnessError::new(
            String::from(context),
            format!(
                "the containment root {} could not be resolved: {error}; the suite cannot prove \
                 a file lies inside a directory it cannot find",
                root.display()
            ),
        )
    })?;
    let canonical_path = path.canonicalize().map_err(|error| {
        HarnessError::new(
            String::from(context),
            format!(
                "{} could not be resolved: {error}; containment is decided on the fully resolved \
                 path so that no symbolic link along the way can change the answer",
                path.display()
            ),
        )
    })?;

    let mut path_components = canonical_path.components();
    for root_component in canonical_root.components() {
        if path_components.next() != Some(root_component) {
            return Err(HarnessError::new(
                String::from(context),
                format!(
                    "{} resolves to {}, which is not inside {}; the suite compiles, executes and \
                     reports only files committed beneath that directory, so a path that leaves \
                     it is refused rather than followed",
                    path.display(),
                    canonical_path.display(),
                    canonical_root.display()
                ),
            ));
        }
    }
    if path_components.next().is_none() {
        return Err(HarnessError::new(
            String::from(context),
            format!(
                "{} resolves to the containment root {} itself rather than to a file beneath it",
                path.display(),
                canonical_root.display()
            ),
        ));
    }
    Ok(canonical_path)
}

/// Require that `path` lies beneath [`corpus_root`], and return its canonical form.
///
/// This is the containment check every consumer of a discovered path uses. It is a thin
/// specialization of [`ensure_within`] so that the corpus root is named in exactly one place
/// and cannot drift between callers.
pub fn ensure_within_corpus(context: &str, path: &Path) -> HarnessResult<PathBuf> {
    ensure_within(context, &corpus_root(), path)
}

/// Validate one corpus input and return its resolved path.
///
/// Four conditions must hold, and each closes a distinct way a path could name something the
/// suite must not read:
///
/// - the path is absolute, so the file a cell names never depends on the working directory,
///   about which the test harness makes no guarantee;
/// - the entry is a regular file and **not a symbolic link**, delegated to
///   [`require_regular_file`];
/// - the resolved path lies strictly beneath the corpus root, delegated to
///   [`ensure_within_corpus`], which also rejects a file whose parent directory is a link out
///   of the corpus, since resolution reduces the whole path;
/// - the extension is the one the role requires, so a program and its record cannot be
///   swapped.
///
/// The two properties in the middle are delegated rather than repeated so that this funnel and
/// the primitives above cannot disagree about what "inside the corpus" means.
///
/// The returned path is the resolved one. Callers record it rather than the path they were
/// given, so that a report and a reproduction command always name the file that was actually
/// read.
pub fn require_contained_corpus_file(
    context: &str,
    role: &str,
    path: &Path,
    extension: &str,
) -> HarnessResult<PathBuf> {
    if !path.is_absolute() {
        return Err(HarnessError::new(
            context,
            format!(
                "the {role} path {} is not absolute; corpus paths are derived from the package \
                 manifest directory so that a cell never depends on the working directory",
                path.display()
            ),
        ));
    }

    let scoped = format!("{context}: the {role} path");
    require_regular_file(&scoped, path)?;
    let resolved = ensure_within_corpus(&scoped, path)?;

    let found = resolved
        .extension()
        .and_then(|value| value.to_str())
        .map(String::from);
    if found.as_deref() != Some(extension) {
        return Err(HarnessError::new(
            context,
            format!(
                "the {role} path {} does not have the required extension {extension:?}; every \
                 program in the corpus is a .c file paired with a sibling .expected record",
                resolved.display()
            ),
        ));
    }

    Ok(resolved)
}
