//! Per-cell workspace management for the differential conformance suite.
//!
//! Every compile-and-run cell of the build matrix gets one directory of its own. This
//! module is the only thing in the suite that decides where that directory is, creates it,
//! writes into it and removes it, which is what lets the suite's whole artifact-and-path
//! discipline be checked by reading one file.
//!
//! # What the discipline is, and what it is not
//!
//! The guarantee this module provides is **path discipline over harness-managed writes**: the
//! paths this suite constructs are derived from a cell's identity, validated, and confined to
//! the three roots below, and the corpus is opened read-only. That is a property of the code
//! and is checkable here.
//!
//! It is **not an operating-system sandbox**, and reading it as one would be a mistake worth
//! naming explicitly. Nothing here isolates syscalls or the network, enters a namespace or a
//! `chroot`, clears the environment a child inherits, sets `TMPDIR`, or restricts what an
//! absolute path handed to an external tool may reach. Three consequences follow directly and
//! are stated rather than left to be discovered:
//!
//! - **External tools keep their own temporaries wherever they normally put them.** A
//!   reference compiler driver writes intermediate files under the system temporary directory
//!   — `gcc -###` shows `/tmp/cc*` entries for the assembler input, the object and the linker
//!   response file — and this module neither sees nor relocates them.
//! - **The bounding utility and the execution runners live outside the build tree.** The
//!   system `timeout` utility and the QEMU runners are executed from wherever they are
//!   installed; only the artifact they are pointed at is required to be inside a workspace.
//! - **A crash dump is the host's decision.** Whether a signalled child writes a core image,
//!   and where it lands, is decided by the host's `kernel.core_pattern` and core-size limit.
//!
//! What keeps the *programs under test* from reaching the network or the wider filesystem is
//! therefore corpus-authoring policy rather than enforcement here: every corpus program takes
//! its whole input from literals in its own source, opens no socket and no file. That policy is
//! auditable because the corpus is committed, and it is the half of constraint four this suite
//! actually discharges.
//!
//! # The three write roots, and nothing else
//!
//! The suite writes beneath exactly three directories, all of them inside the Cargo build
//! directory: [`work_root`] (one workspace per cell), [`report_root`] (one file per feature
//! area plus the run summary) and [`findings_root`] (findings generated by the current run).
//! This module owns the first and, in [`ensure_roots`], creates all three, establishes the run's
//! identity once per process, and retires the previous run's account of itself.
//!
//! Two things follow, and both are properties of the code rather than promises about it:
//!
//! - **The corpus is read-only to the harness.** A program's `.c` file and its sibling
//!   `.expected` record are read and *copied into* a workspace by [`Workspace::copy_in`];
//!   they are never modified in place. No function here returns a writable handle to
//!   anything under the corpus, so the committed, curated finding set that ships as a
//!   deliverable cannot be polluted by a run in progress.
//! - **This module opens no socket.** The only operations it performs are local filesystem
//!   calls from [`std::fs`]. It does not follow that a child process it later hands a path to
//!   is similarly constrained; that is the distinction the section above draws.
//!
//! # Layout
//!
//! ```text
//! target/conformance-report/run.txt          which run produced the reports beside it
//! target/conformance-work/                                  <- work_root()
//! |
//! +-- 01_integer_conversions+004_narrowing_conversions+x86_64+O0/
//! |   +-- program.c        a copy of the corpus program, so the directory stands alone
//! |   +-- program.expected a copy of its expectation record, so the directory also states
//! |   |                    what the result was supposed to be
//! |   +-- bcc.out          artifact built by the compiler under test
//! |   +-- ref.out          artifact built by the reference compiler
//! |   +-- bcc.stdout   bcc.stderr   bcc.exit
//! |   +-- ref.stdout   ref.stderr   ref.exit
//! |   +-- commands.txt     the exact rendered command lines for this cell
//! |
//! +-- _flagprobe/<flag>/                     one directory per flag the probe verifies
//! +-- _ubaudit/<area>/<program>/<gate>/      one directory per audit gate invocation
//! ```
//!
//! The well-known entry names above are spelled once, as the `*_NAME` constants below, so
//! the modules that build a cell, run it and write its finding artifacts cannot disagree
//! about which file is which.
//!
//! ## Why one flat directory per cell rather than a nested tree
//!
//! A cell's directory name is [`CellKey::slug`], which already encodes all four components
//! of the cell's identity — feature area, program, target and optimization level — as a
//! single path component, so the directory is one level beneath the work root rather than
//! four.
//!
//! That is not a stylistic choice. [`Cell::new`] derives a cell's own workspace with the same
//! expression and then *rejects* any derivation that is not a direct child of the work root,
//! because the derived workspace is the one directory a cell may write into. Were this module
//! to nest instead, the same cell would have two different directory names: the compile step
//! would place `bcc.out` in the path carried by its [`Cell`], while the execute step would run
//! with a working directory somewhere else entirely, and the artifacts would silently fail to
//! line up. [`for_resolved_cell`] exists to make that impossible — it checks the derivation in
//! this module against the one already carried by a resolved [`Cell`] and fails loudly if they
//! ever diverge.
//!
//! ## Determinism, and why it is preferred to unpredictability here
//!
//! A workspace path is a pure function of the cell's identity. It contains no clock reading,
//! no counter, no process or thread identifier and no unpredictable element of any kind, so
//! the same cell yields the same path in every process and on every run.
//!
//! The conventional instinct would be a scratch directory with an unpredictable name. It is
//! the wrong tool for this suite: the artifact being chased is a compiler divergence across
//! more than a thousand cells, and a maintainer reading one row of a report must be able to
//! predict, from that row alone, exactly which directory to open. Reproducibility is worth
//! more here than unpredictability, so it is what the naming optimizes for.
//!
//! Determinism also supplies the parallel-safety argument. [`CellKey::slug`] is injective,
//! so two distinct cells cannot name the same directory, and the feature-area tests can run
//! concurrently — as `cargo test` does by default — with no lock and no coordination over any
//! *path*.
//!
//! The module does hold shared mutable state, and only for one purpose: the run's retention
//! accounting. A ceiling on what a whole run may keep is by definition a fact about the run
//! rather than about any one cell, so it cannot be derived from a cell's identity the way a path
//! can. It is therefore kept in two atomics and one mutex-guarded list of notes, all of them
//! write-mostly and none of them consulted to decide *where* anything is written — so the
//! hermeticity argument above still rests on pure functions of the cell identity, and the
//! concurrency argument for paths is unchanged.
//!
//! ## Stale artifacts, and why allocation purges
//!
//! Because paths are deterministic, a second run finds the directory the previous run left
//! behind. Allocation therefore removes the directory tree and recreates it, so a workspace
//! is always empty when its cell begins. Skipping that step would be a correctness bug rather
//! than untidiness: a leftover `bcc.out` from an earlier build compared against a freshly
//! produced `ref.out` would yield a verdict about two different compilations and report it as
//! though it meant something.
//!
//! The same reasoning applies one level up, to the run's *account of itself*, and that is why
//! [`ensure_roots`] does more than create directories. A per-area report and a generated finding
//! also live at deterministic paths, so a previous run's `areas/09_optimization_levels.tsv` sits
//! exactly where this run's will and a previous run's finding directory sits exactly where this
//! run's would. Finalization would then aggregate a set of files that never described one run — a
//! reduced run's rows counted beside a full run's, or a finding fixed weeks ago presented as
//! current — and the summary would state that total with no way for a reader to tell. Both are
//! therefore retired once, at the start of the run, and the run's identity is written to
//! [`RUN_MANIFEST_NAME`] beside the reports so a reader can see whose they are.
//!
//! ## Retention policy
//!
//! The success and failure paths are both explicit at the call site, and both consume the
//! workspace:
//!
//! - [`Workspace::discard`] removes the directory once its cell has passed. It removes
//!   nothing when the run was asked to keep every workspace.
//! - [`Workspace::retain`] leaves the directory in place, so a cell that failed — including a
//!   cell that timed out, which is a divergence like any other — leaves behind exactly the
//!   artifacts needed to investigate it, and returns a [`Retention`] naming the path so a report
//!   can send a maintainer to it.
//!
//! A retained directory is complete in a specific, checkable sense: it holds the program
//! ([`PROGRAM_SOURCE_NAME`]) and its expectation record ([`PROGRAM_RECORD_NAME`]) as copies,
//! both compiled artifacts, every captured stream, the recorded termination statuses, and the
//! exact rendered command lines ([`COMMANDS_NAME`]) — and those command lines name the copied
//! source rather than the corpus one, so the recipe in the directory rebuilds the bytes in the
//! directory. Nothing in it refers to a file that a later corpus edit could change underneath it.
//!
//! Deliberately, this type has no destructor that deletes. A destructor would run while a
//! panicking cell unwound and would erase the evidence for precisely the cell whose evidence
//! matters most.
//!
//! ### Retention is bounded, and every bound is reported
//!
//! Retention is the one thing here that would otherwise grow without limit: 1,296 cells, each
//! keeping its directory when it does not pass, and the run in which the compiler under test
//! builds nothing at all is the run in which all of them do. Three ceilings therefore apply at
//! the moment of retention — one entry, one workspace, and the run as a whole — and pruning
//! removes the largest entries first, so the executables go and the captured streams, recorded
//! statuses and command lines stay. Every pruning is recorded in the returned [`Retention`] and in
//! [`retention_pruning_notes`], because a pruned workspace and a workspace that never existed look
//! identical on disk and mean opposite things.
//!
//! Edition 2021, minimum supported Rust 1.70. Only the standard library is used, as the
//! project permits no third-party crate; this module is what stands in for a scratch-directory
//! crate.

use std::fs;
use std::io;
use std::path::{Component, Path, PathBuf, MAIN_SEPARATOR};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Mutex, OnceLock};

use super::env::RunConfig;
use super::{
    build_root, create_directory_chain_below, encode_slug_component, ensure_within, findings_root,
    must_escape_for_report, publish_bytes_no_follow, read_file_bounded, remove_entry, report_root,
    require_directory_chain_below, require_real_directory_within, require_regular_file,
    run_generation, run_id, sanitize_text_for_report, shown_path, work_root, write_new_file, Cell,
    CellKey, HarnessError, HarnessResult,
};

// The well-known entries of a cell workspace. Named here so that the module which compiles a
// cell, the module which runs it and the module which writes its finding artifacts all refer
// to one spelling: a divergence between two hard-coded strings would surface as an absent
// artifact rather than as an error.

/// The copy of the program source that makes a workspace self-contained.
///
/// A retained workspace is reproducible on its own because the program travels with the
/// artifacts and the command lines, so investigating a divergence never depends on the corpus
/// still holding exactly the bytes that produced it.
pub const PROGRAM_SOURCE_NAME: &str = "program.c";

/// The copy of the program's expectation record that makes a workspace self-contained.
///
/// The record is what states the targets, the optimization levels, the command templates, the
/// expected termination and the golden standard output, so a retained workspace holding the program
/// without it is only half a reproducer: a maintainer could rebuild the artifacts but not know what
/// the cell was asserting. Copying both is what makes "source file, build commands, and expected
/// output recorded together" true of the retained directory itself and not merely of the corpus it
/// came from.
///
/// Copied in beside the program at allocation, under a fixed name sharing the stem of
/// [`PROGRAM_SOURCE_NAME`] rather than the corpus stem, so every workspace holds its two inputs in
/// the same two places and as the sibling pair of one stem the suite requires everywhere else.
pub const PROGRAM_RECORD_NAME: &str = "program.expected";

/// The executable built by the compiler under test.
pub const BCC_ARTIFACT_NAME: &str = "bcc.out";

/// The executable built by the reference compiler.
pub const REFERENCE_ARTIFACT_NAME: &str = "ref.out";

/// Captured standard output of the artifact built by the compiler under test.
///
/// Held as raw bytes: comparison is byte-exact, so nothing may normalize line endings or
/// substitute a replacement character for a byte that is not valid text.
pub const BCC_STDOUT_NAME: &str = "bcc.stdout";

/// Captured standard error from the compiler under test and from running its artifact.
///
/// Kept for finding artifacts and never compared, because diagnostic wording legitimately
/// differs between compilers.
pub const BCC_STDERR_NAME: &str = "bcc.stderr";

/// Recorded termination status of the artifact built by the compiler under test.
pub const BCC_EXIT_NAME: &str = "bcc.exit";

/// Captured standard output of the artifact built by the reference compiler.
pub const REFERENCE_STDOUT_NAME: &str = "ref.stdout";

/// Captured standard error from the reference compiler and from running its artifact.
pub const REFERENCE_STDERR_NAME: &str = "ref.stderr";

/// Recorded termination status of the artifact built by the reference compiler.
pub const REFERENCE_EXIT_NAME: &str = "ref.exit";

/// Standard output the compiler under test wrote while building this cell.
///
/// # Why the build's streams need names of their own
///
/// [`BCC_STDERR_NAME`] and its reference counterpart hold what the *artifact* wrote when it ran.
/// Writing a build's diagnostics there too would mean one of the two overwrote the other — and it
/// would be the build that lost, because a build necessarily precedes the run of what it produced.
/// The compile-time and run-time streams are different evidence about different events, so they get
/// different names and a retained workspace holds both.
pub const BCC_COMPILE_STDOUT_NAME: &str = "bcc.compile.stdout";

/// Diagnostics the compiler under test wrote while building this cell.
///
/// The stream a build failure is read from, and therefore the first file a maintainer opens when a
/// cell was retained because its build refused. Never compared between compilers: wording
/// legitimately differs between implementations.
pub const BCC_COMPILE_STDERR_NAME: &str = "bcc.compile.stderr";

/// Termination and capture facts of the build performed by the compiler under test.
///
/// Line-oriented and free of any measured time, so two retained workspaces differ only where the
/// compilations differed. Records the exit code, signal termination, timeout, artifact size and the
/// fidelity of each captured stream, so a truncated diagnostic listing is visible as truncated
/// rather than read as a short one.
pub const BCC_COMPILE_STATUS_NAME: &str = "bcc.compile.status";

/// Standard output the reference compiler wrote while building this cell.
pub const REFERENCE_COMPILE_STDOUT_NAME: &str = "ref.compile.stdout";

/// Diagnostics the reference compiler wrote while building this cell.
pub const REFERENCE_COMPILE_STDERR_NAME: &str = "ref.compile.stderr";

/// Termination and capture facts of the build performed by the reference compiler.
pub const REFERENCE_COMPILE_STATUS_NAME: &str = "ref.compile.status";

/// The exact command lines used for this cell, one per line.
///
/// Written for every cell rather than only for a failing one, so a retained workspace is
/// reproducible by hand with no harness, no Cargo and no Rust toolchain.
pub const COMMANDS_NAME: &str = "commands.txt";

/// Container for the workspaces of the flag-capability probe.
///
/// The probe verifies command-line flags rather than corpus programs, so its workspaces are
/// keyed by flag instead of by cell identity.
pub const FLAG_PROBE_ROOT_NAME: &str = "_flagprobe";

/// Container for the workspaces of the undefined-behaviour audit gates.
pub const UB_AUDIT_ROOT_NAME: &str = "_ubaudit";

/// Directory names immediately beneath [`work_root`] that are reserved for the two
/// infrastructure users and may therefore never be taken by a cell.
///
/// Both begin with an underscore and every feature-area directory begins with a digit, so in
/// practice the sets are disjoint already. [`for_cell`] checks it anyway rather than relying on
/// that convention holding forever: the check costs one comparison, and a future area name
/// that happened to collide would otherwise let a cell and the probe write into one directory
/// concurrently — the one failure this module exists to make impossible.
/// Directory beneath [`work_root`] that holds the emulator attestation workspaces.
///
/// An emulator has to be proved to execute the architecture it was selected for, which means
/// building a program and running it — before any cell runs, and therefore before any cell workspace
/// exists. Its own grouping directory keeps that pre-flight work distinguishable from the matrix.
pub const ATTESTATION_ROOT_NAME: &str = "_attest";

pub const RESERVED_ROOT_NAMES: &[&str] = &[
    FLAG_PROBE_ROOT_NAME,
    UB_AUDIT_ROOT_NAME,
    ATTESTATION_ROOT_NAME,
];

/// Name of the ownership stamp every deterministically named directory in this suite carries.
///
/// Workspace paths are a pure function of a cell's identity, with no process identifier and no
/// clock reading in them — deliberately, because a maintainer reading one report row has to be
/// able to predict which directory to open. The cost of that determinism is that two *processes*
/// address the same directories, so a second `cargo test` invocation, or a stale one still
/// finishing, allocates over a workspace this run is in the middle of producing: allocation purges,
/// so the first run's artifacts vanish and it compares a half-written pair.
///
/// Randomizing the path would destroy the property the determinism was for. The stamp is the
/// alternative: it records *which run owns this directory*, so a foreign owner that is still
/// running is detected and refused, while a foreign owner that has exited is recognised as stale
/// and purged exactly as before. Determinism is kept and the collision becomes visible.
///
/// The reasoning is not specific to workspaces, so neither is the stamp: `findings.rs` publishes
/// each finding into a directory named after the divergence, and `report.rs` publishes into a
/// report root named by convention. Both face the identical collision and both claim through this
/// same entry name.
///
/// The leading dot keeps it out of the way of the well-known artifact names, and
/// [`validate_entry_name`] refuses it so a cell can never overwrite its own claim.
pub const RUN_OWNER_ENTRY: &str = ".run-owner";

/// Upper bound on the ownership stamp, which is one short line.
const RUN_OWNER_MAX_BYTES: u64 = 512;

/// The directory a cell owns, derived from its identity alone.
///
/// A pure function: the same [`CellKey`] yields the same path in every process and on every
/// run, so a report row leads straight to a directory. The result is
/// [`work_root`] joined with [`CellKey::slug`], and because a slug is always exactly one path
/// component the result is always a direct child of that root — the same derivation
/// [`Cell::new`] performs and then asserts.
///
/// Deriving a path does not create it. [`for_cell`] is what allocates.
///
/// This is also the working directory every child process of the cell is given, through
/// [`Workspace::root`]: a compiler that wrote to a relative path, and an executed artifact that
/// did the same, both land inside the cell's own directory. The process-wide working directory is
/// never changed instead, because the feature-area tests execute concurrently in one process and
/// a directory shared by every thread would be a data race rather than a confinement. There is
/// deliberately no second function returning the same path under another name — one derivation
/// cannot drift from itself.
pub fn workspace_path(key: &CellKey) -> PathBuf {
    work_root().join(key.slug())
}

/// Name of the sidecar that records which run owns the artifacts beneath [`report_root`].
///
/// A sidecar rather than a header inside each report, because a report's Markdown and
/// tab-separated bytes are documented as identical for identical inputs and a run token would
/// break that on every run. The identity therefore lives beside the reports, where a reader — and
/// [`report`](super::report)'s finalization — can consult it without making the reports themselves
/// non-deterministic.
pub const RUN_MANIFEST_NAME: &str = "run.txt";

/// Upper bound on the bytes one retained entry may contribute to the run's retention budget.
///
/// A statically linked executable for four architectures is the largest thing a workspace holds,
/// and a few megabytes covers one comfortably. An entry larger than this is pruned and the pruning
/// is reported, because a single pathological artifact must not be able to fill the build
/// directory — and because an entry nobody can open is not evidence.
pub const RETAINED_ENTRY_BYTES_MAX: u64 = 8 * 1024 * 1024;

/// Upper bound on the bytes one retained workspace may hold.
///
/// A cell workspace holds the program, its record, two artifacts, four captured streams and two
/// status records, so this is generous. Reaching it means something produced far more than a
/// corpus program can, which is itself worth reporting.
pub const RETAINED_WORKSPACE_BYTES_MAX: u64 = 32 * 1024 * 1024;

/// Upper bound on the bytes every retained workspace of one run may hold together.
///
/// This is the bound the review's resource-management finding is really about. The matrix has 1,296
/// cells, and a run in which every one of them fails — a compiler under test that cannot build
/// anything at all is exactly that run — would otherwise retain 1,296 workspaces with no ceiling
/// whatever. Two gigabytes is far more evidence than any investigation needs and far less than a
/// build directory can be allowed to lose.
pub const RETAINED_RUN_BYTES_MAX: u64 = 2 * 1024 * 1024 * 1024;

/// How many workspaces one run may retain before further retentions are pruned.
///
/// The count matters independently of the bytes: ten thousand empty directories are cheap in bytes
/// and expensive to read, and an investigation that begins with more than a few hundred candidate
/// directories has not been helped by the rest.
pub const RETAINED_WORKSPACE_COUNT_MAX: usize = 512;

/// Create the directories the suite writes into and establish this run's identity, exactly once.
///
/// Safe to call from every feature-area test, and every call after the first is a no-op: the work
/// is performed under a [`OnceLock`], so fourteen concurrently starting areas initialize the run
/// once between them and all fourteen observe the same result.
///
/// # What initialization does, and why creating the roots is not enough
///
/// The three roots are created, and then the two that hold *this run's account of itself* are
/// emptied completely: every per-area report, the run summary, and every generated finding of any
/// previous run is removed. That is the correction the review's report-lifecycle finding asks for,
/// and it closes a failure that merely creating the directories leaves wide open. Report and finding
/// paths are deterministic, so a previous run's `areas/09_optimization_levels.tsv` sits exactly
/// where this run's will, its `summary.md` sits exactly where this run's would, and so does its
/// finding directory. Finalization would then aggregate a set of files that never described one run
/// — a reduced run's rows counted beside a full run's, or a finding that was fixed weeks ago
/// presented as current — and the summary would state the total with no way for a reader to tell.
/// Worse, a run that never reached finalization at all would leave the *previous* run's summary
/// standing as though it were this one's.
///
/// The per-cell workspace root is deliberately **not** wiped: [`allocate`] purges each workspace as
/// it is allocated, so a cell always starts empty, and wiping the whole root would destroy the
/// retained evidence of a run a maintainer is still reading while a second, filtered run gathers
/// one more data point.
///
/// The identity itself is written to [`RUN_MANIFEST_NAME`] beside the reports, so a reader looking
/// at a report directory can tell which run produced it.
///
/// Created through the suite's shared guarded walk rather than a bare recursive create, so a
/// symbolic link planted at one of the three root names is refused here — at the first moment the
/// suite touches it — instead of by whichever of the three consumers happened to reach it first.
/// All three consumers do refuse it, but discovering it once, up front, and in one wording is what
/// makes the refusal legible.
///
/// # Why the report root is created but never emptied
///
/// Each root is only ever created here, never cleared, and for the report root that is a
/// correctness requirement rather than an economy. The per-area reports outlive the process that
/// wrote them, so a later run does find earlier files there — but the fourteen area tests run
/// concurrently in one process, so whichever area happened to reach a clearing step last would
/// erase the reports of every area already finished. Emptying the root would therefore trade a
/// stale-data problem for a lost-data race.
///
/// Staleness is resolved where it can be resolved safely: `report.rs` stamps every area report with
/// the identity of the run that wrote it and excludes any file carrying a different stamp from the
/// summary, naming it in the diagnostics. That needs no ordering between the area tests and destroys
/// nothing.
///
/// # Errors
///
/// Returns an error naming the absolute path and the underlying cause if a root cannot be created,
/// if it is not a real directory beneath the build directory, if a previous run's artifacts cannot
/// be retired, or if the run manifest cannot be published. Every one is a hard failure rather than
/// a degraded run: a suite that cannot write its workspaces cannot test anything, and a suite that
/// cannot prove which run its reports belong to cannot report honestly.
pub fn ensure_roots() -> HarnessResult<()> {
    static INITIALIZED: OnceLock<Result<(), String>> = OnceLock::new();
    match INITIALIZED.get_or_init(|| initialize_run().map_err(|error| error.to_string())) {
        Ok(()) => Ok(()),
        Err(rendered) => Err(HarnessError::new(
            "initializing the run's build-directory roots",
            rendered.clone(),
        )),
    }
}

/// The work performed by the first caller of [`ensure_roots`].
fn initialize_run() -> HarnessResult<()> {
    let generation = run_generation();
    let build = build_root();

    for (role, root) in [
        ("per-cell workspace", work_root()),
        ("run report", report_root()),
        ("generated finding", findings_root()),
    ] {
        let context = format!("creating the {role} root directory");
        // Created component by component rather than with a bare recursive create, so a symbolic
        // link planted at one of the three root names is refused at the level it sits on rather
        // than followed out of the build directory.
        create_directory_chain_below(&context, &root, &root)?;
        require_real_directory_within(&context, &build, &root)?;
    }

    // Retire the previous run's account of itself, whole. Both roots are emptied entry by entry
    // rather than removed and recreated, so a reader holding a directory open keeps a valid handle,
    // and every removal refuses to follow a symbolic link.
    //
    // The report root is emptied rather than having its two known artifacts named, and that
    // distinction is load-bearing: the summary pair sits in the root beside the areas directory, and
    // a rule that retired only the areas directory would leave the previous run's `summary.md` in
    // place. A run that then never finalized — a filtered run, or one that failed partway — would
    // leave a reader looking at a complete, plausible summary of a *different* run, with this run's
    // manifest beside it. Emptying the root has no list to keep in step with the artifacts written
    // into it, so it cannot fall behind one.
    retire_directory_contents(
        "retiring the previous run's generated findings",
        &findings_root(),
    )?;
    retire_directory_contents("retiring the previous run's reports", &report_root())?;
    let areas_dir_name = super::report::AREAS_DIR_NAME;

    let manifest = report_root().join(RUN_MANIFEST_NAME);
    let text = format!(
        "# identity of the run that produced the reports in this directory\n\
         run_token = {}\n\
         configuration = {}\n\
         area_reports = {areas_dir_name}/\n\
         retained_run_bytes_max = {RETAINED_RUN_BYTES_MAX}\n\
         retained_workspace_bytes_max = {RETAINED_WORKSPACE_BYTES_MAX}\n\
         retained_entry_bytes_max = {RETAINED_ENTRY_BYTES_MAX}\n\
         retained_workspace_count_max = {RETAINED_WORKSPACE_COUNT_MAX}\n\
         # The token identifies this process's run and is deliberately absent from the reports\n\
         # themselves, which are byte-identical for identical inputs. The configuration\n\
         # fingerprint is deterministic and is carried by the reports, so a reduced run's numbers\n\
         # can never be mistaken for a full run's.\n",
        generation.token(),
        generation.configuration(),
    );
    publish_bytes_no_follow(
        "publishing the run manifest beside the reports",
        &manifest,
        text.as_bytes(),
    )
}

/// Remove every entry directly inside `directory`, following no symbolic link.
///
/// The directory itself is left in place, so a concurrent reader's handle stays valid and no
/// caller has to re-create it. Absence of the directory is success: there is nothing to retire.
fn retire_directory_contents(context: &str, directory: &Path) -> HarnessResult<()> {
    let entries = match fs::read_dir(directory) {
        Ok(entries) => entries,
        Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(()),
        Err(error) => {
            return Err(HarnessError::new(
                String::from(context),
                format!(
                    "{} could not be listed: {error}; a run that cannot retire the previous run's \
                     artifacts cannot state which run its own artifacts describe",
                    directory.display()
                ),
            ));
        }
    };
    for entry in entries {
        let entry = entry.map_err(|error| {
            HarnessError::new(
                String::from(context),
                format!(
                    "an entry of {} could not be read: {error}",
                    directory.display()
                ),
            )
        })?;
        remove_entry(context, &entry.path())?;
    }
    Ok(())
}

// -------------------------------------------------------------------------------------------------
// The run's retention budget
//
// Retention is what makes a failing cell investigable, and it is also the one thing in this module
// that grows without an obvious bound: the matrix has 1,296 cells, every one of them retains its
// workspace when it does not pass, and a compiler under test that cannot build anything produces
// exactly that run. The budget below is the ceiling, and it is applied at the moment of retention
// rather than as a sweep afterwards, so the bound holds continuously rather than eventually.
//
// Two properties are deliberate. Pruning is **reported**, never silent: a caller receives the note
// and puts it in the report, because a workspace that was pruned and a workspace that was never
// created look identical on disk and mean opposite things. And pruning removes the *largest*
// entries first, so that when a byte ceiling is what bites, the small text captures — the statuses,
// the command lines, the recorded streams — survive and the linked executables go first. The count
// ceiling below is different in kind: past it, every entry of a newly retained workspace is pruned.
// What keeps the loss recoverable either way is the workspace path, which names its cell precisely
// enough to re-run exactly that one cell.
// -------------------------------------------------------------------------------------------------

/// Bytes retained by this run so far, across every workspace.
static RETAINED_BYTES: AtomicU64 = AtomicU64::new(0);

/// Workspaces retained by this run so far.
static RETAINED_COUNT: AtomicU64 = AtomicU64::new(0);

/// Notes describing every pruning this run performed, in the order they happened.
fn pruning_notes() -> &'static Mutex<Vec<String>> {
    static NOTES: OnceLock<Mutex<Vec<String>>> = OnceLock::new();
    NOTES.get_or_init(|| Mutex::new(Vec::new()))
}

/// What retaining one workspace cost the run's budget, and what had to be given up for it.
///
/// Returned by [`Workspace::retain`] so the caller can put the accounting in the report next to the
/// cell it belongs to. A retention that fitted inside the budget carries no notes, which is the
/// ordinary case and reads as silence.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Retention {
    root: PathBuf,
    bytes: u64,
    notes: Vec<String>,
}

impl Retention {
    /// The directory that was retained.
    pub fn root(&self) -> &Path {
        self.root.as_path()
    }

    // There is deliberately no `bytes` accessor. [`Retention::describe`] already states this
    // workspace's contribution beside the run total it was charged against, and the run's totals are
    // read once, from [`retention_totals`], when the summary is assembled. A second way to ask the
    // same question is a second thing that can be updated without the other: a caller reporting a
    // byte count it rendered itself and another reporting the one `describe` renders would look
    // interchangeable right up until one of the two ceilings changed.

    /// What had to be pruned to stay inside the budget, if anything.
    ///
    /// Empty for a retention that fitted. Never empty for one that did not, because a pruning that
    /// went unreported would leave a report describing evidence that is not there.
    pub fn notes(&self) -> &[String] {
        &self.notes
    }

    /// One line naming the directory and the accounting, for a report row.
    pub fn describe(&self) -> String {
        let mut text = format!(
            "{} ({} byte(s) retained; run total {} of {RETAINED_RUN_BYTES_MAX})",
            shown_path(&self.root),
            self.bytes,
            RETAINED_BYTES.load(Ordering::Relaxed),
        );
        for note in &self.notes {
            text.push_str("; ");
            text.push_str(note);
        }
        sanitize_text_for_report(&text)
    }
}

/// Everything this run pruned in order to stay inside its retention budget.
///
/// Consulted once, when the run summary is assembled, so that a reduced set of retained workspaces
/// is stated in the deliverable rather than discovered by a maintainer who went looking for a
/// directory that is not there.
pub fn retention_pruning_notes() -> Vec<String> {
    match pruning_notes().lock() {
        Ok(held) => held.clone(),
        // A poisoned lock means a thread panicked while recording a note. The notes already
        // recorded are still true, so they are recovered rather than discarded: losing them would
        // turn a reported pruning back into a silent one.
        Err(poisoned) => poisoned.into_inner().clone(),
    }
}

/// Bytes and workspaces this run has retained so far.
pub fn retention_totals() -> (u64, u64) {
    (
        RETAINED_BYTES.load(Ordering::Relaxed),
        RETAINED_COUNT.load(Ordering::Relaxed),
    )
}

/// Record one pruning so that it reaches both the caller's row and the run summary.
fn note_pruning(note: String) -> String {
    match pruning_notes().lock() {
        Ok(mut held) => held.push(note.clone()),
        Err(poisoned) => poisoned.into_inner().push(note.clone()),
    }
    note
}

/// Create `path` and any missing parent, attributing a failure to `context`.
///
/// The caller supplies the context so that a failure names the operation in progress — creating
/// a root, or allocating the workspace of a named cell — rather than a phrase this function
/// invented without knowing which.
///
/// [`fs::create_dir_all`] is used for both reasons it exists: it builds the intermediate
/// directories of a nested audit workspace in one call, and it succeeds when the directory is
/// already there, which is what makes concurrent allocation safe without coordination.
/// Require that `candidate` is a path strictly beneath [`work_root`], deciding it lexically.
///
/// This is the single guard every creation, every write and every removal in this module passes
/// through, and it is deliberately **lexical** rather than resolved. [`ensure_within`] answers
/// the same question on disk, with symbolic links reduced, but it can only answer it for a path
/// that already exists — which is never true of a directory about to be created or a file about
/// to be written. The two are complementary and both are used: this one before, that one after.
///
/// Three conditions are required, and each closes a distinct way a path could reach somewhere
/// it must not:
///
/// - the work root's component sequence is a prefix of the candidate's, compared component by
///   component rather than as text. A text prefix test would answer "does
///   `…/conformance-work-scratch/x` start with `…/conformance-work`" with yes, which is wrong;
///   comparing components answers it with no, because the two directory names are different
///   components;
/// - every remaining component is [`Component::Normal`], so a candidate carrying a parent
///   directory component in its tail is refused rather than followed upward. This is the
///   condition that makes it impossible for a recursive removal in this module to reach a file
///   in the checkout;
/// - at least one component remains, so the work root **itself** is never a candidate. Without
///   it, one defective identity could turn a routine cleanup into the removal of every
///   workspace in the run.
fn require_beneath_work_root(context: &str, candidate: &Path) -> HarnessResult<()> {
    let root = work_root();
    let mut remaining = candidate.components();
    for expected in root.components() {
        if remaining.next() != Some(expected) {
            return Err(HarnessError::new(
                String::from(context),
                format!(
                    "{} does not lie beneath the workspace root {}; this module writes and \
                     removes nothing outside that directory, so a path that leaves it is a defect \
                     to report rather than a location to use",
                    shown_path(candidate),
                    shown_path(&root)
                ),
            ));
        }
    }

    let mut depth = 0usize;
    for component in remaining {
        match component {
            Component::Normal(_) => depth += 1,
            _ => {
                return Err(HarnessError::new(
                    String::from(context),
                    format!(
                        "{} contains a component that is not a plain name below the workspace \
                         root {}; a parent-directory or root component would let the path climb \
                         out of the build directory, so it is refused instead of resolved",
                        shown_path(candidate),
                        shown_path(&root)
                    ),
                ));
            }
        }
    }
    if depth == 0 {
        return Err(HarnessError::new(
            String::from(context),
            format!(
                "{} is the workspace root {} itself rather than a directory beneath it; the root \
                 holds every workspace of the run, so it is never the target of a creation or a \
                 removal",
                shown_path(candidate),
                shown_path(&root)
            ),
        ));
    }
    Ok(())
}

/// Validate and encode one path component of a non-cell workspace.
///
/// Encoding is delegated to the same function [`CellKey::slug`] uses, so this module introduces
/// no second naming scheme. That mapping is injective — every byte outside `[A-Za-z0-9_]`
/// becomes an escape naming exactly that byte — which is what keeps two distinct names in
/// distinct directories. A scheme that folded such bytes to a single character instead would
/// make `a b` and `a/b` indistinguishable, and two probes that differed only there would then
/// overwrite each other's artifacts while running concurrently.
///
/// Validation happens first, and rejects rather than repairs. Encoding would make any of the
/// names below *safe* to use as a directory name, but a caller that assembled an empty name, a
/// relative directory name, a path fragment or text carrying a control character has a defect,
/// and turning that into a strangely named directory nobody can trace back would hide it. A
/// hard failure naming the value is the correct outcome.
///
/// Whitespace is deliberately allowed, unlike in a corpus stem: a probe may legitimately be
/// keyed by a flag spelling that contains a space, and such a byte encodes to an escape that is
/// still exactly one safe component.
fn encode_component(role: &str, raw: &str) -> HarnessResult<String> {
    let context = format!("deriving the {role} component of a workspace path");
    if raw.is_empty() {
        return Err(HarnessError::new(
            context,
            format!(
                "the {role} name is empty; a workspace component is always a name the caller \
                 chose deliberately, so an empty one means it was assembled from something \
                 absent"
            ),
        ));
    }
    let shown = sanitize_text_for_report(raw);
    if raw == "." || raw == ".." {
        return Err(HarnessError::new(
            context,
            format!(
                "the {role} name is {shown:?}, which names a directory relative to another rather \
                 than a component of its own"
            ),
        ));
    }
    if raw.contains('/') || raw.contains(MAIN_SEPARATOR) {
        return Err(HarnessError::new(
            context,
            format!(
                "the {role} name {shown:?} contains a path separator; each component is one name, \
                 and the containing directories are supplied by this module rather than by the \
                 caller"
            ),
        ));
    }
    if raw.chars().any(must_escape_for_report) {
        return Err(HarnessError::new(
            context,
            format!(
                "the {role} name {shown:?} contains a character that cannot appear literally in a \
                 report; such a name would be written into report rows and reproduction commands, \
                 where it could forge a column or hide a line"
            ),
        ));
    }

    // A non-empty input always encodes to non-empty output, because every byte contributes
    // either itself or a three-character escape. Rejecting an empty input above is therefore
    // sufficient to guarantee a non-empty component here.
    let mut encoded = String::new();
    encode_slug_component(raw, &mut encoded);
    Ok(encoded)
}

/// Validate the name of one entry inside a workspace.
///
/// The rules are those of [`encode_component`] minus the encoding: an entry name is used
/// verbatim, because the well-known names are chosen by this module and appear in reproduction
/// commands exactly as written.
fn validate_entry_name(context: &str, name: &str) -> HarnessResult<()> {
    if name.is_empty() {
        return Err(HarnessError::new(
            String::from(context),
            String::from(
                "the entry name is empty; a workspace entry is always a file this module named",
            ),
        ));
    }
    let shown = sanitize_text_for_report(name);
    if name == "." || name == ".." {
        return Err(HarnessError::new(
            String::from(context),
            format!("the entry name is {shown:?}, which names a directory rather than a file"),
        ));
    }
    if name.contains('/') || name.contains(MAIN_SEPARATOR) {
        return Err(HarnessError::new(
            String::from(context),
            format!(
                "the entry name {shown:?} contains a path separator; a workspace is flat, and an \
                 entry is written directly inside it so that a retained directory can be read at \
                 a glance"
            ),
        ));
    }
    if name == RUN_OWNER_ENTRY {
        return Err(HarnessError::new(
            String::from(context),
            format!(
                "the entry name {shown:?} is the workspace's own run-ownership stamp; a cell may \
                 not write it, because a workspace that could rewrite its own claim could hand \
                 itself to another run mid-cell"
            ),
        ));
    }
    if name.chars().any(must_escape_for_report) {
        return Err(HarnessError::new(
            String::from(context),
            format!(
                "the entry name {shown:?} contains a character that cannot appear literally in a \
                 report or a reproduction command"
            ),
        ));
    }
    Ok(())
}

/// Remove `path` and everything beneath it, treating absence as success.
///
/// Every removal in this module funnels through here, and the containment guard is applied
/// first, so no removal can reach outside the workspace root however the path was derived. That
/// guard is this function's whole content: the removal itself is the harness's shared
/// [`remove_entry`], which is where the symbolic-link-versus-directory decision lives and is
/// documented, so this module, the report module and the findings module cannot drift apart on the
/// one judgement in a removal that is easy to get subtly wrong.
fn purge(context: &str, path: &Path) -> HarnessResult<()> {
    require_beneath_work_root(context, path)?;
    remove_entry(context, path)
}

/// Allocate one workspace: purge whatever is there, create it, and prove where it landed.
///
/// The order is deliberate. The lexical guard runs before anything touches the filesystem, so a
/// path that should not exist is never created and never removed. The purge follows, which is
/// what makes allocation idempotent across runs: because the path is deterministic, a second
/// run finds the first run's directory, and a leftover artifact compared against a freshly
/// produced one would be a silently wrong result rather than a visible error. Creation then
/// builds the directory and any intermediate one it needs.
///
/// The final step re-answers the containment question on disk through [`ensure_within`], which
/// canonicalizes both sides. The lexical guard cannot see a symbolic link, so a workspace name
/// that some earlier process turned into a link out of the build directory would satisfy it;
/// this check resolves the directory that now exists and refuses it if it is not really inside
/// the work root. Its resolved form is deliberately **not** stored: the workspace keeps the
/// derived spelling, so its path is identical to the workspace a resolved [`Cell`] carries and
/// to the working directory handed to the cell's child processes, and one cell is never described
/// two ways.
fn allocate(role: &str, root: PathBuf, keep_on_success: bool) -> HarnessResult<Workspace> {
    let context = format!(
        "allocating the workspace for {role} at {}",
        shown_path(&root)
    );
    require_beneath_work_root(&context, &root)?;
    if let Some(conflict) = live_foreign_owner(&root) {
        return Err(HarnessError::new(context, conflict));
    }
    purge(&context, &root)?;
    create_directory_chain_below(&context, &work_root(), &root)?;
    ensure_within(&context, &work_root(), &root)?;
    claim_ownership(&context, &root)?;
    Ok(Workspace {
        root,
        keep_on_success,
    })
}

/// The identity of the run that owns a workspace, as recorded in its stamp.
///
/// The process identifier and its start time are both kept, because a process identifier alone is
/// reused: a stamp naming a long-gone process whose number has since been handed to something else
/// would report a live owner that is not this suite at all. Comparing the start time as well makes
/// the pair effectively unique for the life of the machine.
struct RunOwner {
    run: String,
    pid: u32,
    started: String,
}

impl RunOwner {
    /// This run, as it will be written into a stamp.
    fn current() -> RunOwner {
        let pid = std::process::id();
        RunOwner {
            run: String::from(run_id()),
            pid,
            started: process_start_token(pid).unwrap_or_else(|| String::from("unknown")),
        }
    }

    /// The stamp's on-disk form: three tab-separated fields on one line.
    ///
    /// Tab-separated and single-line so it parses with no dependency, and so a maintainer can read
    /// it with `cat`. None of the three fields can contain a tab: two are decimal numbers and
    /// [`run_id`] is hexadecimal.
    fn encode(&self) -> String {
        format!("{}\t{}\t{}\n", self.run, self.pid, self.started)
    }

    /// Parse a stamp, returning [`None`] for anything that is not one.
    ///
    /// An unparseable stamp is treated as absent rather than as an error. It can only have been
    /// produced by a different version of this suite or by a truncated write, and in both cases the
    /// safe reading is "nobody currently owns this", which restores the ordinary purge-and-recreate
    /// path instead of wedging every future run.
    fn decode(raw: &str) -> Option<RunOwner> {
        let line = raw.lines().next()?;
        let mut fields = line.split('\t');
        let run = fields.next()?.trim().to_string();
        let pid = fields.next()?.trim().parse::<u32>().ok()?;
        let started = fields.next()?.trim().to_string();
        if run.is_empty() || fields.next().is_some() {
            return None;
        }
        Some(RunOwner { run, pid, started })
    }

    /// True when this stamp still describes a process that is running.
    ///
    /// Answered from the process table where the platform exposes one. When it does not — the
    /// directory is unreadable, or this is not a system with a `/proc` filesystem — the answer is
    /// `false`, which means a foreign stamp is treated as stale and the directory is purged. That
    /// is the pre-existing behaviour rather than a regression: this check can only ever *add*
    /// refusals, never remove one.
    fn is_live(&self) -> bool {
        match process_start_token(self.pid) {
            Some(current) => current == self.started,
            None => false,
        }
    }
}

/// A token that identifies one incarnation of a process identifier, or [`None`] if unavailable.
///
/// On Linux this is the process's start time in clock ticks, field 22 of `/proc/<pid>/stat`. The
/// field is read positionally *from the end*, because field 2 is the executable name in parentheses
/// and may itself contain spaces and parentheses — splitting from the front is the classic way to
/// misparse this file. Fields 3 onwards contain no spaces, so counting back from the last field is
/// unambiguous.
fn process_start_token(pid: u32) -> Option<String> {
    let raw = fs::read_to_string(format!("/proc/{pid}/stat")).ok()?;
    let tail = raw.rsplit_once(')')?.1;
    let fields: Vec<&str> = tail.split_whitespace().collect();
    // `tail` begins at field 3, so field 22 is index 19.
    fields.get(19).map(|value| (*value).to_string())
}

/// The stamp a directory currently carries, if it has one this module can read.
fn recorded_owner(root: &Path) -> Option<RunOwner> {
    let path = root.join(RUN_OWNER_ENTRY);
    let bytes = read_file_bounded(
        "reading a workspace ownership stamp",
        &path,
        RUN_OWNER_MAX_BYTES,
    )
    .ok()?;
    RunOwner::decode(&String::from_utf8(bytes).ok()?)
}

/// The run identifier and process identifier of a *live foreign* owner of `root`, if there is one.
///
/// The mechanism half of the ownership check, shared with every other module that publishes into a
/// deterministically named directory: the workspaces here, the finding directories in `findings.rs`
/// and the report root in `report.rs` all face the identical hazard, and a second implementation of
/// "is somebody else still working in this directory" is a second chance to answer it wrongly. Each
/// caller phrases its own refusal from the returned identity, because the advice differs — a
/// workspace conflict is resolved by waiting or changing `CARGO_TARGET_DIR`, a finding conflict
/// additionally means two runs are recording the same divergence, and a report conflict means the
/// clearing this run would perform would destroy the artifacts the other run is still writing.
///
/// [`None`] covers every case in which publication may proceed: the directory does not exist, it
/// carries no readable stamp, the stamp is this run's own, or the stamp names a process that has
/// exited. Only a *live foreign* owner is reported, so the documented idempotent re-run is
/// unaffected — a previous run's leftovers are still purged and recreated exactly as before.
pub(super) fn live_foreign_owner_identity(root: &Path) -> Option<(String, u32)> {
    let owner = recorded_owner(root)?;
    if owner.run == run_id() {
        return None;
    }
    if !owner.is_live() {
        return None;
    }
    Some((owner.run, owner.pid))
}

/// A sentence explaining the conflict when a workspace belongs to another run that is still running.
///
/// Wraps [`live_foreign_owner_identity`] with the advice that applies to a workspace specifically.
fn live_foreign_owner(root: &Path) -> Option<String> {
    let (run, pid) = live_foreign_owner_identity(root)?;
    Some(format!(
        "{} is already owned by run {} (process {}), which is still running. Workspace paths are \
         deterministic so that a report row leads straight to a directory, which means two \
         concurrent runs address the same one; allocating it here would purge the artifacts that \
         run is still producing and leave both runs comparing half-written pairs. Let that run \
         finish, or set CARGO_TARGET_DIR to a different build directory for this one",
        shown_path(root),
        sanitize_text_for_report(&run),
        pid
    ))
}

/// Record this run as the owner of `root`, replacing a stamp a finished run left behind.
///
/// Written through the suite's exclusive creation path, so the stamp cannot follow a link and
/// cannot land on a pre-existing regular file. A previous stamp is removed first through the
/// shared guarded removal rather than truncated in place: at a workspace the entry is always
/// absent because the directory has just been purged and recreated, but a finding directory and the
/// report root are both republished in place across runs, and "truncate whatever is at this name"
/// is exactly the operation a planted link exploits.
///
/// Shared with `findings.rs` for the same reason as [`live_foreign_owner_identity`]: the claim and
/// the check must agree on the entry name and the encoding, and they can only be guaranteed to
/// agree by being the same code.
pub(super) fn claim_ownership(context: &str, root: &Path) -> HarnessResult<()> {
    let path = root.join(RUN_OWNER_ENTRY);
    remove_entry(context, &path)?;
    write_new_file(context, &path, RunOwner::current().encode().as_bytes())
}

/// One allocated workspace: the single directory its owner may write into.
///
/// The directory exists by the time an instance does, and the instance is the capability to
/// write into it — there is no way to obtain one for a directory that was never allocated, and
/// no method that writes anywhere else.
///
/// Deliberately not [`Clone`]: both endings consume the value, so the type system enforces that
/// a workspace is concluded exactly once and that the choice between removal and retention is
/// made explicitly at the call site. A copy could conclude the same directory twice, which is
/// how a retained failure comes to be deleted by an unrelated success path.
///
/// The retention policy is captured at allocation rather than consulted later. `env.rs` reads
/// the environment once and is the only interpreter of it, so nothing here re-derives a policy
/// from a variable: two concurrently executing areas therefore cannot behave differently
/// because a variable changed between their reads.
#[derive(Debug, PartialEq, Eq)]
pub struct Workspace {
    /// Absolute path to the directory, in the derived spelling rather than a resolved one, so it
    /// matches the workspace a resolved [`Cell`] carries, and the working directory every child
    /// process of that cell is given, exactly.
    root: PathBuf,
    /// Whether [`Workspace::discard`] must keep the directory anyway, because the run was asked
    /// to retain every workspace.
    keep_on_success: bool,
}

impl Workspace {
    /// The directory this workspace owns.
    pub fn root(&self) -> &Path {
        self.root.as_path()
    }

    /// Whether a successful cell will keep this directory rather than remove it.
    ///
    /// Exposed so a report can state that a run retained everything, which is the difference
    /// between an empty work tree that means every cell passed and one that means nothing ran.
    pub fn keeps_on_success(&self) -> bool {
        self.keep_on_success
    }

    /// Resolve one entry of this workspace by name.
    ///
    /// # Errors
    ///
    /// Rejects an empty name, a relative directory name, a name containing a path separator, and
    /// a name containing a character that cannot appear literally in a report, then re-applies
    /// the containment guard to the joined path. The guard cannot fail once the name has passed —
    /// a plain name joined to a contained directory stays contained — and it is applied anyway
    /// because it is the line the path discipline rests on, and a check that is cheap and
    /// unconditional cannot be forgotten during maintenance.
    ///
    /// Returns a result rather than a bare path on purpose. An infallible signature could only
    /// reject a bad name by panicking, and a panic here would replace a diagnosable divergence
    /// with a harness crash on the failure path of a cell.
    pub fn path(&self, name: &str) -> HarnessResult<PathBuf> {
        let context = format!(
            "resolving the entry {:?} of the workspace {}",
            sanitize_text_for_report(name),
            shown_path(&self.root)
        );
        validate_entry_name(&context, name)?;
        let resolved = self.root.join(name);
        require_beneath_work_root(&context, &resolved)?;
        Ok(resolved)
    }

    /// Write `bytes` to the named entry, replacing it if it is already there, and return its
    /// path.
    ///
    /// Bytes rather than text throughout: a captured standard output stream is compared byte for
    /// byte, so it must be stored exactly as the program produced it, with no line-ending
    /// normalization and no substitution for a byte that is not valid text.
    ///
    /// # Why this refuses to follow a symbolic link
    ///
    /// A plain write opens the destination by name and follows whatever is there. Every entry
    /// name in a workspace is fixed and public — `bcc.stdout`, `ref.exit`, `commands.txt` — and
    /// the workspace path is derived deterministically from the cell identity, so both are known
    /// to anything else running on the machine long before the cell runs. If one of those names
    /// were a symbolic link when the write happened, the captured bytes would land wherever the
    /// link pointed, the report would still name the workspace entry, and the divergence between
    /// the two would leave no trace at all.
    ///
    /// [`publish_bytes_no_follow`] closes that: it refuses a destination that is a link or
    /// anything other than a regular file, stages the bytes in a uniquely named temporary it
    /// creates exclusively, and renames the temporary into place. The rename also makes the entry
    /// appear whole — a reader never sees a half-written capture — which matters because a
    /// retained workspace is read by a maintainer while later cells are still running.
    ///
    /// # Errors
    ///
    /// Returns an error naming the absolute path and the underlying cause. The most likely causes
    /// are a workspace directory that no longer exists and a destination that is not a regular
    /// file; the message names the workspace directory in both cases.
    pub fn write(&self, name: &str, bytes: &[u8]) -> HarnessResult<PathBuf> {
        let path = self.path(name)?;
        let context = format!(
            "writing {} in the workspace {}",
            shown_path(&path),
            shown_path(&self.root)
        );
        // Every directory from the work root down to this workspace must be a real directory. The
        // lexical guard in `Workspace::path` cannot see a symbolic link, so this is what refuses a
        // workspace whose *parent* some other process replaced with a link out of the build tree.
        require_directory_chain_below(&context, &work_root(), &self.root)?;
        // The bytes are then published by the one guarded writer this suite has: they are staged in
        // a fresh temporary entry created exclusively and renamed into place, and a name already
        // occupied by a link — even a dangling one — is refused rather than followed. A plain
        // `fs::write` would instead have opened the link's target and written through it, with every
        // report still naming this path, and a truncating write would leave a partial file
        // observable to a reader.
        publish_bytes_no_follow(&context, &path, bytes)?;
        Ok(path)
    }

    /// Write `text` to the named entry as UTF-8 and return its path.
    ///
    /// For the entries that are genuinely text — the rendered command lines and the recorded
    /// termination status. Captured program output goes through [`Workspace::write`] instead.
    ///
    /// # Errors
    ///
    /// Delegated in full to [`Workspace::write`], and through it to [`Workspace::path`]: the name
    /// is rejected if it is empty, is `.` or `..`, contains a path separator, or contains a
    /// character that cannot appear literally in a report, and again if the joined path does not
    /// resolve beneath the work root. The write itself fails if the workspace directory no longer
    /// exists or is not writable. Nothing is added here — the text is handed on as its UTF-8 bytes
    /// — so there is no failure this wrapper owns.
    pub fn write_text(&self, name: &str, text: &str) -> HarnessResult<PathBuf> {
        self.write(name, text.as_bytes())
    }

    /// Copy an existing file into this workspace under the given name, and return its path.
    ///
    /// Used to bring a program's source in beside the artifacts built from it, which is what
    /// makes a retained workspace reproducible on its own rather than only in combination with
    /// whatever the corpus happens to contain later.
    ///
    /// # Errors
    ///
    /// The source must be an existing regular file and **not** a symbolic link, which
    /// [`require_regular_file`] establishes. Refusing a link matters because following one would
    /// copy in — and then compile and execute — a file from anywhere on the machine while every
    /// report still showed the path that was asked for. Refusing anything that is not a regular
    /// file also rules out reading a device node or a pipe, which can block without end.
    ///
    /// The copy is one-directional: this is the only way a file enters a workspace from outside,
    /// and there is no counterpart that writes back out, so the corpus stays read-only to the
    /// suite.
    ///
    /// The destination is published through [`Workspace::write`] rather than copied onto directly,
    /// so the same refusal to follow a link that protects a captured stream protects a copied-in
    /// program: a plain copy opens the destination by name, and every one of these names is fixed
    /// and predictable. The source is read whole first, which is safe because it is bounded — a
    /// source larger than [`RETAINED_ENTRY_BYTES_MAX`] is refused rather than read, since nothing
    /// the corpus contains approaches that and reading an unbounded file into memory on the
    /// failure path of a cell is how a diagnostic becomes an outage.
    pub fn copy_in(&self, source: &Path, name: &str) -> HarnessResult<PathBuf> {
        let context = format!(
            "copying {} into the workspace {}",
            shown_path(source),
            shown_path(&self.root)
        );
        require_regular_file(&context, source)?;
        // Read then write, rather than `fs::copy`. `fs::copy` follows a symbolic link at the
        // *destination*, so a pre-planted link there would have redirected a corpus program to
        // anywhere on the machine. `read_file_bounded` re-establishes the source's properties
        // through the same no-follow inspection and caps the transfer at the per-entry ceiling, and
        // `Workspace::write` is the one guarded publication path this suite has.
        let bytes = read_file_bounded(&context, source, RETAINED_ENTRY_BYTES_MAX)?;
        self.write(name, &bytes)
    }

    /// Remove this workspace, because its cell passed.
    ///
    /// Removes nothing when the run was asked to retain every workspace, in which case the
    /// directory is left exactly as the cell finished with it.
    ///
    /// Only the directory this workspace owns is removed, never a parent it merely sits inside.
    /// A cell workspace has no shared parent but the work root, and the grouping directories of
    /// the audit workspaces are shared by design, so pruning an emptied one would race a sibling
    /// being created on another thread: the sibling's directory could vanish between its creation
    /// and its first write. Leaving an empty grouping directory behind costs nothing and keeps
    /// allocation independent of what any other thread is doing.
    ///
    /// # Errors
    ///
    /// Returns an error naming the path and the cause if the directory cannot be removed. A
    /// caller on a success path should prefer [`Workspace::discard_advisory`]: a directory that
    /// resists removal is untidy, but turning that into a failure would report a defect in the
    /// compiler where there was only a defect in the cleanup, which is the one thing a cleanup
    /// step must never do.
    pub fn discard(self) -> HarnessResult<()> {
        if self.keep_on_success {
            return Ok(());
        }
        let context = format!(
            "removing the workspace {} after its cell passed",
            shown_path(&self.root)
        );
        purge(&context, &self.root)
    }

    /// Remove this workspace, returning a note to append to the cell's outcome detail instead of
    /// an error.
    ///
    /// The resilient form of [`Workspace::discard`], and the one a success path should use.
    /// Cleanup can never fail a run or mask a verdict: a removal that did not work becomes a
    /// sentence in the report, and the run continues.
    ///
    /// Returns [`None`] when the directory was removed, or was intentionally kept.
    pub fn discard_advisory(self) -> Option<String> {
        self.discard().err().map(|error| error.to_string())
    }

    /// Keep this workspace, because its cell did not pass, and account for what keeping it cost.
    ///
    /// The evidence-preservation ending. A failing cell — including one that exceeded its time
    /// budget, which is a divergence like any other rather than an infrastructure fault — leaves
    /// behind the program and its expectation record as copies, both artifacts, every captured
    /// stream, the recorded termination statuses and the exact command lines. The command lines
    /// name the copied program, so what the directory says to run is what the directory contains.
    ///
    /// # Why retention is bounded
    ///
    /// Retention is the one thing this module does that grows without a natural limit. The matrix
    /// has 1,296 cells; every cell that does not pass keeps its directory; and the run in which a
    /// compiler under test cannot build anything at all is exactly the run in which all 1,296 of
    /// them keep one. Unbounded, that fills the build directory of the machine, and the run that
    /// discovers the most is the run that is least able to report it.
    ///
    /// Three ceilings therefore apply, in order — [`RETAINED_ENTRY_BYTES_MAX`] to one entry,
    /// [`RETAINED_WORKSPACE_BYTES_MAX`] to this directory, and
    /// [`RETAINED_RUN_BYTES_MAX`]/[`RETAINED_WORKSPACE_COUNT_MAX`] to the run as a whole — and each
    /// is enforced at the moment of retention rather than by a sweep afterwards, so the bound holds
    /// continuously instead of eventually.
    ///
    /// Pruning removes the **largest** entries first. That is not an arbitrary order: when a byte
    /// ceiling is what bites, the large entries are the linked executables while the small ones are
    /// the captured streams, the recorded statuses and the command lines — which is everything an
    /// investigation actually reads, so the cheap evidence is what survives.
    ///
    /// [`RETAINED_WORKSPACE_COUNT_MAX`] is different in kind and the difference matters to anyone
    /// reading the result: past it a workspace is still created and still named by the report, but
    /// *every* entry in it is pruned, the command lines included. What makes the loss recoverable in
    /// either case is not something left in the directory but the directory itself, whose name
    /// identifies the cell precisely enough to re-run exactly it.
    ///
    /// Every pruning is **reported**, in the returned value and in the run summary. A workspace
    /// that was pruned and a workspace that was never created are indistinguishable on disk and
    /// mean opposite things, so a silent pruning would turn missing evidence into apparently absent
    /// evidence — which is the one outcome a diagnostic must never produce.
    ///
    /// A failure encountered while pruning is itself recorded as a note and never raised: this is
    /// the concluding step of a cell that has already been decided, and a tidying problem must not
    /// re-decide it.
    pub fn retain(self) -> Retention {
        let root = self.root;
        let mut notes = Vec::new();
        let mut entries = collect_entries(&root, &mut notes);

        // Ceiling one: no single entry may be larger than the per-entry bound. Applied before the
        // others so that one pathological artifact cannot consume a whole workspace's allowance and
        // push out every small capture beside it.
        let mut index = 0;
        while index < entries.len() {
            if entries[index].bytes > RETAINED_ENTRY_BYTES_MAX {
                let entry = entries.remove(index);
                prune_entry(
                    &entry,
                    &format!(
                        "it is larger than the {RETAINED_ENTRY_BYTES_MAX}-byte ceiling on one \
                         retained entry"
                    ),
                    &mut notes,
                );
            } else {
                index += 1;
            }
        }

        // Ceiling two: the workspace as a whole. Largest first, until it fits.
        let mut total: u64 = entries.iter().map(|entry| entry.bytes).sum();
        while total > RETAINED_WORKSPACE_BYTES_MAX {
            match take_largest(&mut entries) {
                Some(entry) => {
                    total = total.saturating_sub(entry.bytes);
                    prune_entry(
                        &entry,
                        &format!(
                            "the workspace exceeded the {RETAINED_WORKSPACE_BYTES_MAX}-byte ceiling \
                             on one retained workspace"
                        ),
                        &mut notes,
                    );
                }
                None => break,
            }
        }

        // Ceiling three: the run. The count is claimed first, because a run that has already kept
        // its full complement of directories keeps this one as an empty marker rather than as
        // evidence — the directory stays so that the report's path still names something, and the
        // note says why it is bare.
        let already = RETAINED_COUNT.fetch_add(1, Ordering::Relaxed);
        if already >= RETAINED_WORKSPACE_COUNT_MAX as u64 {
            while let Some(entry) = take_largest(&mut entries) {
                total = total.saturating_sub(entry.bytes);
                prune_entry(
                    &entry,
                    &format!(
                        "this run had already retained {RETAINED_WORKSPACE_COUNT_MAX} workspaces, \
                         which is the ceiling on the number one run may keep"
                    ),
                    &mut notes,
                );
            }
            total = 0;
        }

        // The byte reservation is a claim-then-verify loop rather than a read followed by an add,
        // because fourteen feature areas conclude cells concurrently and two of them reading the
        // same total before either added to it would both believe they fitted.
        loop {
            let current = RETAINED_BYTES.load(Ordering::Acquire);
            let projected = current.saturating_add(total);
            if projected <= RETAINED_RUN_BYTES_MAX {
                if RETAINED_BYTES
                    .compare_exchange(current, projected, Ordering::AcqRel, Ordering::Acquire)
                    .is_ok()
                {
                    break;
                }
                continue;
            }
            match take_largest(&mut entries) {
                Some(entry) => {
                    total = total.saturating_sub(entry.bytes);
                    prune_entry(
                        &entry,
                        &format!(
                            "this run had already retained {current} of the \
                             {RETAINED_RUN_BYTES_MAX} bytes one run may keep"
                        ),
                        &mut notes,
                    );
                }
                // Nothing left to give up, so the reservation is zero and the next pass through
                // the loop necessarily fits.
                None => total = 0,
            }
        }

        Retention {
            root,
            bytes: total,
            notes,
        }
    }
}

/// One entry of a workspace that is about to be retained, and the bytes it occupies.
///
/// A directory counts as one entry carrying its recursive size, because the only nested structure
/// a workspace ever holds is one a compiler produced beside its output, and pruning it whole is
/// both simpler to explain in a note and impossible to leave half-removed.
#[derive(Debug, Clone, PartialEq, Eq)]
struct RetainedEntry {
    path: PathBuf,
    bytes: u64,
}

/// List the direct entries of `root`, measuring each, without following a symbolic link.
///
/// A directory that cannot be listed, or an entry that cannot be measured, contributes a note
/// rather than an error: this runs while a cell is being concluded, and a measurement problem must
/// not become a verdict. An entry whose size is unknown is treated as zero bytes and left in place,
/// because pruning something on the strength of a failed measurement would destroy evidence to
/// enforce a bound nobody could show was exceeded.
fn collect_entries(root: &Path, notes: &mut Vec<String>) -> Vec<RetainedEntry> {
    let listing = match fs::read_dir(root) {
        Ok(listing) => listing,
        Err(error) => {
            notes.push(note_pruning(format!(
                "the retained workspace {} could not be listed to account for its size: {error}",
                root.display()
            )));
            return Vec::new();
        }
    };
    let mut entries = Vec::new();
    for entry in listing {
        let entry = match entry {
            Ok(entry) => entry,
            Err(error) => {
                notes.push(note_pruning(format!(
                    "an entry of the retained workspace {} could not be read: {error}",
                    root.display()
                )));
                continue;
            }
        };
        let path = entry.path();
        entries.push(RetainedEntry {
            bytes: entry_bytes(&path),
            path,
        });
    }
    // Deterministic order, so that two runs pruning the same workspace prune it the same way and a
    // note is reproducible rather than dependent on the order the filesystem happened to list.
    entries.sort_by(|left, right| left.path.cmp(&right.path));
    entries
}

/// Bytes occupied by one entry, recursing into a directory and counting a symbolic link as nothing.
///
/// A link counts as nothing because its target is not this workspace's to account for, and because
/// following it to measure the target is exactly the traversal every other guard in this module
/// refuses.
fn entry_bytes(path: &Path) -> u64 {
    let Ok(metadata) = fs::symlink_metadata(path) else {
        return 0;
    };
    let file_type = metadata.file_type();
    if file_type.is_symlink() {
        return 0;
    }
    if !file_type.is_dir() {
        return metadata.len();
    }
    let Ok(listing) = fs::read_dir(path) else {
        return 0;
    };
    let mut total = 0u64;
    for entry in listing.flatten() {
        total = total.saturating_add(entry_bytes(&entry.path()));
    }
    total
}

/// Remove and return the largest remaining entry, breaking a tie by path so the choice is stable.
fn take_largest(entries: &mut Vec<RetainedEntry>) -> Option<RetainedEntry> {
    let mut chosen = 0;
    for (index, entry) in entries.iter().enumerate() {
        let best = &entries[chosen];
        if entry.bytes > best.bytes || (entry.bytes == best.bytes && entry.path < best.path) {
            chosen = index;
        }
    }
    if entries.is_empty() {
        None
    } else {
        Some(entries.remove(chosen))
    }
}

/// Remove one entry to stay inside the budget, and record why.
///
/// A removal that fails is recorded too, and with the same prominence: an entry the accounting
/// believes is gone but which is still on disk would make the run's retained total wrong, and a
/// wrong total is how a ceiling stops holding.
fn prune_entry(entry: &RetainedEntry, reason: &str, notes: &mut Vec<String>) {
    let context = format!("pruning the retained entry {}", entry.path.display());
    match purge(&context, &entry.path) {
        // What the note may promise is bounded by what is actually still there. An earlier wording
        // said the entry could be rebuilt from the command lines retained beside it, which is true
        // of a pruned executable in a workspace that kept its `commands.txt` and false in the two
        // cases that matter most: the workspace-count ceiling prunes *every* entry, command lines
        // included, and the program source and its record were copies rather than build products in
        // the first place. So the note promises only what always holds — the directory the entry
        // stood in names the cell exactly, so re-running that one cell reproduces it — which is also
        // the more useful instruction, because it works whatever else was pruned.
        Ok(()) => notes.push(note_pruning(format!(
            "{} ({} byte(s)) was pruned from the retained evidence because {reason}; the directory \
             it stood in names the cell, so re-running that one cell reproduces it",
            entry.path.display(),
            entry.bytes
        ))),
        Err(error) => notes.push(note_pruning(format!(
            "{} ({} byte(s)) should have been pruned because {reason}, and could not be: {}",
            entry.path.display(),
            entry.bytes,
            error.cause()
        ))),
    }
}

/// Allocate the workspace for one cell of the build matrix.
///
/// # Errors
///
/// The identity is validated first, with the same rule [`Cell::new`] applies, so an area or
/// program name that is not a canonical corpus stem — empty, a relative directory name, a path
/// fragment, or text carrying a control character — is refused here. That rejection is the point:
/// the encoding used for a slug is injective and would happily turn a path fragment into one
/// safe directory name, so without this check a caller that built an identity out of the wrong
/// thing would get a working workspace under a name nobody could trace back to a cell.
///
/// Also fails if the derived name collides with one of [`RESERVED_ROOT_NAMES`], and if the
/// directory cannot be purged or created. A failure is always a hard error naming the path and
/// the cause, never a quietly skipped cell: a cell that did not run must be visible.
pub fn for_cell(key: &CellKey, config: &RunConfig) -> HarnessResult<Workspace> {
    key.validate_identity()?;

    let slug = key.slug();
    if RESERVED_ROOT_NAMES.contains(&slug.as_str()) {
        return Err(HarnessError::new(
            format!("allocating the workspace for {key}"),
            format!(
                "the derived directory name {slug:?} is reserved for the suite's own \
                 infrastructure workspaces; a cell and an infrastructure user sharing one \
                 directory would let two concurrent writers overwrite each other's artifacts"
            ),
        ));
    }

    allocate(&key.to_string(), workspace_path(key), config.keep_work())
}

/// Allocate the workspace for an already resolved [`Cell`], checking that both derivations
/// agree.
///
/// The preferred entry point wherever a resolved cell is at hand, because it is the one place
/// the suite can prove that the workspace path this module derives and the one carried by
/// the one a resolved [`Cell`] already carries are the same directory.
///
/// # Errors
///
/// Fails if the two derivations disagree, naming both paths. Such a disagreement would not
/// announce itself otherwise: the compile step writes into the path its cell carries while the
/// execution step runs in the directory this module names, so the artifacts would simply fail to
/// appear where the next step looked for them, and the cell would fail for a reason that has
/// nothing to do with any compiler. Everything [`for_cell`] can reject is also rejected here.
pub fn for_resolved_cell(cell: &Cell, config: &RunConfig) -> HarnessResult<Workspace> {
    // Read through the type's own accessors rather than its private fields. A sibling module of
    // `mod.rs` can reach those fields directly, which is precisely how the invariants `Cell::new`
    // established get bypassed during maintenance; going through the accessors keeps the only
    // supported reading path the one every other consumer uses.
    let derived = workspace_path(cell.key());
    if cell.workspace() != derived {
        return Err(HarnessError::new(
            format!("allocating the workspace for {}", cell.key()),
            format!(
                "the cell carries the workspace {} while this module derives {}; both are built \
                 from the cell's identity and must be the same directory, because one step writes \
                 the artifacts and another runs in the directory that holds them",
                shown_path(cell.workspace()),
                shown_path(&derived)
            ),
        ));
    }
    let workspace = for_cell(cell.key(), config)?;
    workspace.copy_in(cell.source(), PROGRAM_SOURCE_NAME)?;
    workspace.copy_in(cell.expectation(), PROGRAM_RECORD_NAME)?;
    Ok(workspace)
}

/// Allocate a workspace for one flag examined by the flag-capability probe.
///
/// The probe verifies command-line flags rather than corpus programs, so its workspaces are
/// keyed by the flag under examination and live together beneath [`FLAG_PROBE_ROOT_NAME`]. A
/// flag spelling is encoded exactly as a cell identity component is, so `-static` becomes one
/// safe, distinct directory name.
///
/// # Errors
///
/// Fails on a name [`encode_component`] rejects, and on a directory that cannot be purged or
/// created.
pub fn probe_workspace(name: &str, config: &RunConfig) -> HarnessResult<Workspace> {
    let component = encode_component("flag", name)?;
    let root = work_root().join(FLAG_PROBE_ROOT_NAME).join(component);
    let role = format!("the flag probe {:?}", sanitize_text_for_report(name));
    allocate(&role, root, config.keep_work())
}

/// Allocate a workspace for attesting that one emulator really executes one architecture.
///
/// Keyed by the architecture under attestation and grouped beneath [`ATTESTATION_ROOT_NAME`], so a
/// retained attestation workspace holds exactly the program, the artifact and the captured output
/// that decided whether that arm's runner could be trusted.
///
/// # Errors
///
/// Fails on a label [`encode_component`] rejects, and on a directory that cannot be purged or
/// created.
pub fn attestation_workspace(label: &str, config: &RunConfig) -> HarnessResult<Workspace> {
    let component = encode_component("attested architecture", label)?;
    let root = work_root().join(ATTESTATION_ROOT_NAME).join(component);
    let role = format!(
        "the emulator attestation for {}",
        sanitize_text_for_report(label)
    );
    allocate(&role, root, config.keep_work())
}

/// Allocate a workspace for one undefined-behaviour audit gate applied to one program.
///
/// Every program passes through more than one gate — a strict warning gate and a sanitizer run —
/// and each gate compiles the program separately, so each needs a directory of its own. Keying
/// by feature area, program and gate keeps them distinct and keeps the tree readable, beneath
/// [`UB_AUDIT_ROOT_NAME`].
///
/// The audit is driven entirely by the reference compiler and renders no verdict about the
/// compiler under test: it establishes that a program is free of undefined behaviour, which is
/// the precondition that makes a divergence between two compilers mean anything at all.
///
/// # Errors
///
/// Fails on a component [`encode_component`] rejects, and on a directory that cannot be purged
/// or created.
pub fn audit_workspace(
    area: &str,
    program: &str,
    gate: &str,
    config: &RunConfig,
) -> HarnessResult<Workspace> {
    let area_component = encode_component("feature area", area)?;
    let program_component = encode_component("program", program)?;
    let gate_component = encode_component("audit gate", gate)?;
    let root = work_root()
        .join(UB_AUDIT_ROOT_NAME)
        .join(area_component)
        .join(program_component)
        .join(gate_component);
    let role = format!(
        "the {} audit gate of {}/{}",
        sanitize_text_for_report(gate),
        sanitize_text_for_report(area),
        sanitize_text_for_report(program)
    );
    allocate(&role, root, config.keep_work())
}
