//! Hermetic per-cell workspace management for the differential conformance suite.
//!
//! Every compile-and-run cell of the build matrix gets one directory of its own. This
//! module is the only thing in the suite that decides where that directory is, creates it,
//! writes into it and removes it, which is what lets the whole hermeticity argument be
//! checked by reading one file.
//!
//! # The three write roots, and nothing else
//!
//! The suite writes beneath exactly three directories, all of them inside the Cargo build
//! directory: [`work_root`] (one workspace per cell), [`report_root`] (one file per feature
//! area plus the run summary) and [`findings_root`] (findings generated by the current run).
//! This module owns the first and creates all three in [`ensure_roots`].
//!
//! Two things follow, and both are properties of the code rather than promises about it:
//!
//! - **The corpus is read-only to the harness.** A program's `.c` file and its sibling
//!   `.expected` record are read and *copied into* a workspace by [`Workspace::copy_in`];
//!   they are never modified in place. No function here returns a writable handle to
//!   anything under the corpus, so the committed, curated finding set that ships as a
//!   deliverable cannot be polluted by a run in progress.
//! - **Nothing here reaches the network.** The only operations performed are local
//!   filesystem calls from [`std::fs`].
//!
//! # Layout
//!
//! ```text
//! target/conformance-work/                                  <- work_root()
//! |
//! +-- 01_integer_conversions+004_narrowing_conversions+x86_64+O0/
//! |   +-- program.c        a copy of the corpus program, so the directory stands alone
//! |   +-- bcc.out          artifact built by the compiler under test
//! |   +-- ref.out          artifact built by the reference compiler
//! |   +-- bcc.stdout   bcc.stderr   bcc.exit
//! |   +-- ref.stdout   ref.stderr   ref.exit
//! |   +-- commands.txt     the exact rendered command lines for this cell
//! |
//! +-- _flagprobe/<flag>/                     one directory per flag the probe verifies
//! +-- _ubaudit/<area>/<program>/<gate>/      one directory per audit gate invocation
//! ```
//!
//! The well-known entry names above are spelled once, as the `*_NAME` constants below, so
//! the modules that build a cell, run it and write its finding artifacts cannot disagree
//! about which file is which.
//!
//! ## Why one flat directory per cell rather than a nested tree
//!
//! A cell's directory name is [`CellKey::slug`], which already encodes all four components
//! of the cell's identity — feature area, program, target and optimization level — as a
//! single path component, so the directory is one level beneath the work root rather than
//! four.
//!
//! That is not a stylistic choice. [`Cell::new`] derives [`Cell::workspace`] with the same
//! expression and then *rejects* any derivation that is not a direct child of the work root,
//! because the derived workspace is the one directory a cell may write into. Were this module
//! to nest instead, the same cell would have two different directory names: the compile step
//! would place `bcc.out` in the path carried by its [`Cell`], while the execute step would run
//! with a working directory somewhere else entirely, and the artifacts would silently fail to
//! line up. [`for_resolved_cell`] exists to make that impossible — it checks the derivation in
//! this module against the one already carried by a resolved [`Cell`] and fails loudly if they
//! ever diverge.
//!
//! ## Determinism, and why it is preferred to unpredictability here
//!
//! A workspace path is a pure function of the cell's identity. It contains no clock reading,
//! no counter, no process or thread identifier and no unpredictable element of any kind, so
//! the same cell yields the same path in every process and on every run.
//!
//! The conventional instinct would be a scratch directory with an unpredictable name. It is
//! the wrong tool for this suite: the artifact being chased is a compiler divergence across
//! more than a thousand cells, and a maintainer reading one row of a report must be able to
//! predict, from that row alone, exactly which directory to open. Reproducibility is worth
//! more here than unpredictability, so it is what the naming optimizes for.
//!
//! Determinism also supplies the parallel-safety argument. [`CellKey::slug`] is injective,
//! so two distinct cells cannot name the same directory, and the feature-area tests can run
//! concurrently — as `cargo test` does by default — with no lock, no mutex, no atomic counter
//! and no shared mutable state anywhere in this module.
//!
//! ## Stale artifacts, and why allocation purges
//!
//! Because paths are deterministic, a second run finds the directory the previous run left
//! behind. Allocation therefore removes the directory tree and recreates it, so a workspace
//! is always empty when its cell begins. Skipping that step would be a correctness bug rather
//! than untidiness: a leftover `bcc.out` from an earlier build compared against a freshly
//! produced `ref.out` would yield a verdict about two different compilations and report it as
//! though it meant something.
//!
//! ## Retention policy
//!
//! The success and failure paths are both explicit at the call site, and both consume the
//! workspace:
//!
//! - [`Workspace::discard`] removes the directory once its cell has passed. It removes
//!   nothing when the run was asked to keep every workspace.
//! - [`Workspace::retain`] leaves the directory in place, so a cell that failed — including a
//!   cell that timed out, which is a divergence like any other — leaves behind exactly the
//!   artifacts needed to investigate it, and returns the path so a report can name it.
//!
//! Deliberately, this type has no destructor that deletes. A destructor would run while a
//! panicking cell unwound and would erase the evidence for precisely the cell whose evidence
//! matters most.
//!
//! Edition 2021, minimum supported Rust 1.70. Only the standard library is used, as the
//! project permits no third-party crate; this module is what stands in for a scratch-directory
//! crate.

use std::fs;
use std::io;
use std::path::{Component, Path, PathBuf, MAIN_SEPARATOR};

use super::env::RunConfig;
use super::{
    encode_slug_component, ensure_within, findings_root, must_escape_for_report, report_root,
    require_regular_file, sanitize_text_for_report, work_root, Cell, CellKey, HarnessError,
    HarnessResult,
};

// The well-known entries of a cell workspace. Named here so that the module which compiles a
// cell, the module which runs it and the module which writes its finding artifacts all refer
// to one spelling: a divergence between two hard-coded strings would surface as an absent
// artifact rather than as an error.

/// The copy of the program source that makes a workspace self-contained.
///
/// A retained workspace is reproducible on its own because the program travels with the
/// artifacts and the command lines, so investigating a divergence never depends on the corpus
/// still holding exactly the bytes that produced it.
pub const PROGRAM_SOURCE_NAME: &str = "program.c";

/// The executable built by the compiler under test.
pub const BCC_ARTIFACT_NAME: &str = "bcc.out";

/// The executable built by the reference compiler.
pub const REFERENCE_ARTIFACT_NAME: &str = "ref.out";

/// Captured standard output of the artifact built by the compiler under test.
///
/// Held as raw bytes: comparison is byte-exact, so nothing may normalize line endings or
/// substitute a replacement character for a byte that is not valid text.
pub const BCC_STDOUT_NAME: &str = "bcc.stdout";

/// Captured standard error from the compiler under test and from running its artifact.
///
/// Kept for finding artifacts and never compared, because diagnostic wording legitimately
/// differs between compilers.
pub const BCC_STDERR_NAME: &str = "bcc.stderr";

/// Recorded termination status of the artifact built by the compiler under test.
pub const BCC_EXIT_NAME: &str = "bcc.exit";

/// Captured standard output of the artifact built by the reference compiler.
pub const REFERENCE_STDOUT_NAME: &str = "ref.stdout";

/// Captured standard error from the reference compiler and from running its artifact.
pub const REFERENCE_STDERR_NAME: &str = "ref.stderr";

/// Recorded termination status of the artifact built by the reference compiler.
pub const REFERENCE_EXIT_NAME: &str = "ref.exit";

/// The exact command lines used for this cell, one per line.
///
/// Written for every cell rather than only for a failing one, so a retained workspace is
/// reproducible by hand with no harness, no Cargo and no Rust toolchain.
pub const COMMANDS_NAME: &str = "commands.txt";

/// Container for the workspaces of the flag-capability probe.
///
/// The probe verifies command-line flags rather than corpus programs, so its workspaces are
/// keyed by flag instead of by cell identity.
pub const FLAG_PROBE_ROOT_NAME: &str = "_flagprobe";

/// Container for the workspaces of the undefined-behaviour audit gates.
pub const UB_AUDIT_ROOT_NAME: &str = "_ubaudit";

/// Directory names immediately beneath [`work_root`] that are reserved for the two
/// infrastructure users and may therefore never be taken by a cell.
///
/// Both begin with an underscore and every feature-area directory begins with a digit, so in
/// practice the sets are disjoint already. [`for_cell`] checks it anyway rather than relying on
/// that convention holding forever: the check costs one comparison, and a future area name
/// that happened to collide would otherwise let a cell and the probe write into one directory
/// concurrently — the one failure this module exists to make impossible.
pub const RESERVED_ROOT_NAMES: &[&str] = &[FLAG_PROBE_ROOT_NAME, UB_AUDIT_ROOT_NAME];

/// The directory a cell owns, derived from its identity alone.
///
/// A pure function: the same [`CellKey`] yields the same path in every process and on every
/// run, so a report row leads straight to a directory. The result is
/// [`work_root`] joined with [`CellKey::slug`], and because a slug is always exactly one path
/// component the result is always a direct child of that root — the same derivation
/// [`Cell::new`] performs and then asserts.
///
/// Deriving a path does not create it. [`for_cell`] is what allocates.
pub fn workspace_path(key: &CellKey) -> PathBuf {
    work_root().join(key.slug())
}

/// The working directory a cell's child processes must be given.
///
/// Every compiler and every emulated or native execution for a cell runs with its current
/// directory set to this path. That is what confines a program which wrote to a relative path,
/// and it is why the process-wide working directory is never altered instead: the feature-area
/// tests execute concurrently in one process, so changing a directory shared by every thread
/// would be a data race rather than a confinement.
///
/// Identical to [`workspace_path`] by construction, and named separately because the two
/// call sites express different intentions.
pub fn working_dir_for(key: &CellKey) -> PathBuf {
    workspace_path(key)
}

/// Create the three directories the suite writes into, if they are not already present.
///
/// Intended to be called once by the driver before any area begins, and safe to call from
/// several areas at once: [`fs::create_dir_all`] treats an existing directory as success, so
/// concurrent creation is not an error and no lock is needed.
///
/// # Errors
///
/// Returns an error naming the absolute path and the underlying cause if a root cannot be
/// created. This is a hard failure rather than a degraded run: a suite that cannot write its
/// workspaces cannot test anything, and reporting that as an empty pass would be worse than
/// stopping.
pub fn ensure_roots() -> HarnessResult<()> {
    for (role, root) in [
        ("per-cell workspace", work_root()),
        ("run report", report_root()),
        ("generated finding", findings_root()),
    ] {
        create_directory(&format!("creating the {role} root directory"), &root)?;
    }
    Ok(())
}

/// Create `path` and any missing parent, attributing a failure to `context`.
///
/// The caller supplies the context so that a failure names the operation in progress — creating
/// a root, or allocating the workspace of a named cell — rather than a phrase this function
/// invented without knowing which.
///
/// [`fs::create_dir_all`] is used for both reasons it exists: it builds the intermediate
/// directories of a nested audit workspace in one call, and it succeeds when the directory is
/// already there, which is what makes concurrent allocation safe without coordination.
fn create_directory(context: &str, path: &Path) -> HarnessResult<()> {
    fs::create_dir_all(path).map_err(|error| {
        HarnessError::new(
            String::from(context),
            format!(
                "{} could not be created: {error}; every artifact the suite produces is written \
                 beneath the Cargo build directory, so a root that cannot be created stops the \
                 run rather than diverting it elsewhere",
                path.display()
            ),
        )
    })
}

/// Require that `candidate` is a path strictly beneath [`work_root`], deciding it lexically.
///
/// This is the single guard every creation, every write and every removal in this module passes
/// through, and it is deliberately **lexical** rather than resolved. [`ensure_within`] answers
/// the same question on disk, with symbolic links reduced, but it can only answer it for a path
/// that already exists — which is never true of a directory about to be created or a file about
/// to be written. The two are complementary and both are used: this one before, that one after.
///
/// Three conditions are required, and each closes a distinct way a path could reach somewhere
/// it must not:
///
/// - the work root's component sequence is a prefix of the candidate's, compared component by
///   component rather than as text. A text prefix test would answer "does
///   `…/conformance-work-scratch/x` start with `…/conformance-work`" with yes, which is wrong;
///   comparing components answers it with no, because the two directory names are different
///   components;
/// - every remaining component is [`Component::Normal`], so a candidate carrying a parent
///   directory component in its tail is refused rather than followed upward. This is the
///   condition that makes it impossible for a recursive removal in this module to reach a file
///   in the checkout;
/// - at least one component remains, so the work root **itself** is never a candidate. Without
///   it, one defective identity could turn a routine cleanup into the removal of every
///   workspace in the run.
fn require_beneath_work_root(context: &str, candidate: &Path) -> HarnessResult<()> {
    let root = work_root();
    let mut remaining = candidate.components();
    for expected in root.components() {
        if remaining.next() != Some(expected) {
            return Err(HarnessError::new(
                String::from(context),
                format!(
                    "{} does not lie beneath the workspace root {}; this module writes and \
                     removes nothing outside that directory, so a path that leaves it is a defect \
                     to report rather than a location to use",
                    candidate.display(),
                    root.display()
                ),
            ));
        }
    }

    let mut depth = 0usize;
    for component in remaining {
        match component {
            Component::Normal(_) => depth += 1,
            _ => {
                return Err(HarnessError::new(
                    String::from(context),
                    format!(
                        "{} contains a component that is not a plain name below the workspace \
                         root {}; a parent-directory or root component would let the path climb \
                         out of the build directory, so it is refused instead of resolved",
                        candidate.display(),
                        root.display()
                    ),
                ));
            }
        }
    }
    if depth == 0 {
        return Err(HarnessError::new(
            String::from(context),
            format!(
                "{} is the workspace root {} itself rather than a directory beneath it; the root \
                 holds every workspace of the run, so it is never the target of a creation or a \
                 removal",
                candidate.display(),
                root.display()
            ),
        ));
    }
    Ok(())
}

/// Validate and encode one path component of a non-cell workspace.
///
/// Encoding is delegated to the same function [`CellKey::slug`] uses, so this module introduces
/// no second naming scheme. That mapping is injective — every byte outside `[A-Za-z0-9_]`
/// becomes an escape naming exactly that byte — which is what keeps two distinct names in
/// distinct directories. A scheme that folded such bytes to a single character instead would
/// make `a b` and `a/b` indistinguishable, and two probes that differed only there would then
/// overwrite each other's artifacts while running concurrently.
///
/// Validation happens first, and rejects rather than repairs. Encoding would make any of the
/// names below *safe* to use as a directory name, but a caller that assembled an empty name, a
/// relative directory name, a path fragment or text carrying a control character has a defect,
/// and turning that into a strangely named directory nobody can trace back would hide it. A
/// hard failure naming the value is the correct outcome.
///
/// Whitespace is deliberately allowed, unlike in a corpus stem: a probe may legitimately be
/// keyed by a flag spelling that contains a space, and such a byte encodes to an escape that is
/// still exactly one safe component.
fn encode_component(role: &str, raw: &str) -> HarnessResult<String> {
    let context = format!("deriving the {role} component of a workspace path");
    if raw.is_empty() {
        return Err(HarnessError::new(
            context,
            format!(
                "the {role} name is empty; a workspace component is always a name the caller \
                 chose deliberately, so an empty one means it was assembled from something \
                 absent"
            ),
        ));
    }
    let shown = sanitize_text_for_report(raw);
    if raw == "." || raw == ".." {
        return Err(HarnessError::new(
            context,
            format!(
                "the {role} name is {shown:?}, which names a directory relative to another rather \
                 than a component of its own"
            ),
        ));
    }
    if raw.contains('/') || raw.contains(MAIN_SEPARATOR) {
        return Err(HarnessError::new(
            context,
            format!(
                "the {role} name {shown:?} contains a path separator; each component is one name, \
                 and the containing directories are supplied by this module rather than by the \
                 caller"
            ),
        ));
    }
    if raw.chars().any(must_escape_for_report) {
        return Err(HarnessError::new(
            context,
            format!(
                "the {role} name {shown:?} contains a character that cannot appear literally in a \
                 report; such a name would be written into report rows and reproduction commands, \
                 where it could forge a column or hide a line"
            ),
        ));
    }

    // A non-empty input always encodes to non-empty output, because every byte contributes
    // either itself or a three-character escape. Rejecting an empty input above is therefore
    // sufficient to guarantee a non-empty component here.
    let mut encoded = String::new();
    encode_slug_component(raw, &mut encoded);
    Ok(encoded)
}

/// Validate the name of one entry inside a workspace.
///
/// The rules are those of [`encode_component`] minus the encoding: an entry name is used
/// verbatim, because the well-known names are chosen by this module and appear in reproduction
/// commands exactly as written.
fn validate_entry_name(context: &str, name: &str) -> HarnessResult<()> {
    if name.is_empty() {
        return Err(HarnessError::new(
            String::from(context),
            String::from(
                "the entry name is empty; a workspace entry is always a file this module named",
            ),
        ));
    }
    let shown = sanitize_text_for_report(name);
    if name == "." || name == ".." {
        return Err(HarnessError::new(
            String::from(context),
            format!("the entry name is {shown:?}, which names a directory rather than a file"),
        ));
    }
    if name.contains('/') || name.contains(MAIN_SEPARATOR) {
        return Err(HarnessError::new(
            String::from(context),
            format!(
                "the entry name {shown:?} contains a path separator; a workspace is flat, and an \
                 entry is written directly inside it so that a retained directory can be read at \
                 a glance"
            ),
        ));
    }
    if name.chars().any(must_escape_for_report) {
        return Err(HarnessError::new(
            String::from(context),
            format!(
                "the entry name {shown:?} contains a character that cannot appear literally in a \
                 report or a reproduction command"
            ),
        ));
    }
    Ok(())
}

/// Remove `path` and everything beneath it, treating absence as success.
///
/// Every removal in this module funnels through here, and the containment guard is applied
/// first, so no removal can reach outside the workspace root however the path was derived.
///
/// A symbolic link is removed as a link rather than followed. That distinction matters: a
/// recursive directory removal aimed at a link would either fail or, on a platform that
/// followed it, delete the contents of whatever it pointed at. Removing the link itself leaves
/// its target untouched, which is the only correct behaviour for a name the suite did not
/// create.
///
/// A stale entry that is a plain file where a directory belongs is removed too, so a previous
/// run cannot leave something behind that blocks this one.
fn purge(context: &str, path: &Path) -> HarnessResult<()> {
    require_beneath_work_root(context, path)?;

    let metadata = match fs::symlink_metadata(path) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(()),
        Err(error) => {
            return Err(HarnessError::new(
                String::from(context),
                format!(
                    "{} could not be inspected before removal: {error}",
                    path.display()
                ),
            ));
        }
    };

    let file_type = metadata.file_type();
    let removal = if file_type.is_symlink() || !file_type.is_dir() {
        fs::remove_file(path)
    } else {
        fs::remove_dir_all(path)
    };
    removal.map_err(|error| {
        HarnessError::new(
            String::from(context),
            format!("{} could not be removed: {error}", path.display()),
        )
    })
}

/// Allocate one workspace: purge whatever is there, create it, and prove where it landed.
///
/// The order is deliberate. The lexical guard runs before anything touches the filesystem, so a
/// path that should not exist is never created and never removed. The purge follows, which is
/// what makes allocation idempotent across runs: because the path is deterministic, a second
/// run finds the first run's directory, and a leftover artifact compared against a freshly
/// produced one would be a silently wrong result rather than a visible error. Creation then
/// builds the directory and any intermediate one it needs.
///
/// The final step re-answers the containment question on disk through [`ensure_within`], which
/// canonicalizes both sides. The lexical guard cannot see a symbolic link, so a workspace name
/// that some earlier process turned into a link out of the build directory would satisfy it;
/// this check resolves the directory that now exists and refuses it if it is not really inside
/// the work root. Its resolved form is deliberately **not** stored: the workspace keeps the
/// derived spelling, so its path is identical to [`Cell::workspace`] and to the working
/// directory handed to the cell's child processes, and one cell is never described two ways.
fn allocate(role: &str, root: PathBuf, keep_on_success: bool) -> HarnessResult<Workspace> {
    let context = format!("allocating the workspace for {role} at {}", root.display());
    require_beneath_work_root(&context, &root)?;
    purge(&context, &root)?;
    create_directory(&context, &root)?;
    ensure_within(&context, &work_root(), &root)?;
    Ok(Workspace {
        root,
        keep_on_success,
    })
}

/// One allocated workspace: the single directory its owner may write into.
///
/// The directory exists by the time an instance does, and the instance is the capability to
/// write into it — there is no way to obtain one for a directory that was never allocated, and
/// no method that writes anywhere else.
///
/// Deliberately not [`Clone`]: both endings consume the value, so the type system enforces that
/// a workspace is concluded exactly once and that the choice between removal and retention is
/// made explicitly at the call site. A copy could conclude the same directory twice, which is
/// how a retained failure comes to be deleted by an unrelated success path.
///
/// The retention policy is captured at allocation rather than consulted later. `env.rs` reads
/// the environment once and is the only interpreter of it, so nothing here re-derives a policy
/// from a variable: two concurrently executing areas therefore cannot behave differently
/// because a variable changed between their reads.
#[derive(Debug, PartialEq, Eq)]
pub struct Workspace {
    /// Absolute path to the directory, in the derived spelling rather than a resolved one, so it
    /// matches [`Cell::workspace`] and [`working_dir_for`] exactly.
    root: PathBuf,
    /// Whether [`Workspace::discard`] must keep the directory anyway, because the run was asked
    /// to retain every workspace.
    keep_on_success: bool,
}

impl Workspace {
    /// The directory this workspace owns.
    pub fn root(&self) -> &Path {
        self.root.as_path()
    }

    /// Whether a successful cell will keep this directory rather than remove it.
    ///
    /// Exposed so a report can state that a run retained everything, which is the difference
    /// between an empty work tree that means every cell passed and one that means nothing ran.
    pub fn keeps_on_success(&self) -> bool {
        self.keep_on_success
    }

    /// Resolve one entry of this workspace by name.
    ///
    /// # Errors
    ///
    /// Rejects an empty name, a relative directory name, a name containing a path separator, and
    /// a name containing a character that cannot appear literally in a report, then re-applies
    /// the containment guard to the joined path. The guard cannot fail once the name has passed —
    /// a plain name joined to a contained directory stays contained — and it is applied anyway
    /// because it is the line the hermeticity argument rests on, and a check that is cheap and
    /// unconditional cannot be forgotten during maintenance.
    ///
    /// Returns a result rather than a bare path on purpose. An infallible signature could only
    /// reject a bad name by panicking, and a panic here would replace a diagnosable divergence
    /// with a harness crash on the failure path of a cell.
    pub fn path(&self, name: &str) -> HarnessResult<PathBuf> {
        let context = format!(
            "resolving the entry {:?} of the workspace {}",
            sanitize_text_for_report(name),
            self.root.display()
        );
        validate_entry_name(&context, name)?;
        let resolved = self.root.join(name);
        require_beneath_work_root(&context, &resolved)?;
        Ok(resolved)
    }

    /// Write `bytes` to the named entry, replacing it if it is already there, and return its
    /// path.
    ///
    /// Bytes rather than text throughout: a captured standard output stream is compared byte for
    /// byte, so it must be stored exactly as the program produced it, with no line-ending
    /// normalization and no substitution for a byte that is not valid text.
    ///
    /// The write is a plain one rather than a write-and-rename, because a workspace has exactly
    /// one owner — its cell — and no concurrent writer to be atomic against.
    ///
    /// # Errors
    ///
    /// Returns an error naming the absolute path and the underlying cause. The most likely cause
    /// is a workspace directory that no longer exists, so the message names the directory too.
    pub fn write(&self, name: &str, bytes: &[u8]) -> HarnessResult<PathBuf> {
        let path = self.path(name)?;
        fs::write(&path, bytes).map_err(|error| {
            HarnessError::new(
                format!(
                    "writing {} in the workspace {}",
                    path.display(),
                    self.root.display()
                ),
                format!(
                    "{} could not be written: {error}; the workspace directory {} must exist and \
                     be writable for the whole of its cell",
                    path.display(),
                    self.root.display()
                ),
            )
        })?;
        Ok(path)
    }

    /// Write `text` to the named entry as UTF-8 and return its path.
    ///
    /// For the entries that are genuinely text — the rendered command lines and the recorded
    /// termination status. Captured program output goes through [`Workspace::write`] instead.
    pub fn write_text(&self, name: &str, text: &str) -> HarnessResult<PathBuf> {
        self.write(name, text.as_bytes())
    }

    /// Copy an existing file into this workspace under the given name, and return its path.
    ///
    /// Used to bring a program's source in beside the artifacts built from it, which is what
    /// makes a retained workspace reproducible on its own rather than only in combination with
    /// whatever the corpus happens to contain later.
    ///
    /// # Errors
    ///
    /// The source must be an existing regular file and **not** a symbolic link, which
    /// [`require_regular_file`] establishes. Refusing a link matters because following one would
    /// copy in — and then compile and execute — a file from anywhere on the machine while every
    /// report still showed the path that was asked for. Refusing anything that is not a regular
    /// file also rules out reading a device node or a pipe, which can block without end.
    ///
    /// The copy is one-directional: this is the only way a file enters a workspace from outside,
    /// and there is no counterpart that writes back out, so the corpus stays read-only to the
    /// suite.
    pub fn copy_in(&self, source: &Path, name: &str) -> HarnessResult<PathBuf> {
        let destination = self.path(name)?;
        let context = format!(
            "copying {} into the workspace {}",
            source.display(),
            self.root.display()
        );
        require_regular_file(&context, source)?;
        fs::copy(source, &destination).map_err(|error| {
            HarnessError::new(
                context,
                format!(
                    "{} could not be copied to {}: {error}",
                    source.display(),
                    destination.display()
                ),
            )
        })?;
        Ok(destination)
    }

    /// Remove this workspace, because its cell passed.
    ///
    /// Removes nothing when the run was asked to retain every workspace, in which case the
    /// directory is left exactly as the cell finished with it.
    ///
    /// Only the directory this workspace owns is removed, never a parent it merely sits inside.
    /// A cell workspace has no shared parent but the work root, and the grouping directories of
    /// the audit workspaces are shared by design, so pruning an emptied one would race a sibling
    /// being created on another thread: the sibling's directory could vanish between its creation
    /// and its first write. Leaving an empty grouping directory behind costs nothing and keeps
    /// allocation independent of what any other thread is doing.
    ///
    /// # Errors
    ///
    /// Returns an error naming the path and the cause if the directory cannot be removed. A
    /// caller on a success path should prefer [`Workspace::discard_advisory`]: a directory that
    /// resists removal is untidy, but turning that into a failure would report a defect in the
    /// compiler where there was only a defect in the cleanup, which is the one thing a cleanup
    /// step must never do.
    pub fn discard(self) -> HarnessResult<()> {
        if self.keep_on_success {
            return Ok(());
        }
        let context = format!(
            "removing the workspace {} after its cell passed",
            self.root.display()
        );
        purge(&context, &self.root)
    }

    /// Remove this workspace, returning a note to append to the cell's outcome detail instead of
    /// an error.
    ///
    /// The resilient form of [`Workspace::discard`], and the one a success path should use.
    /// Cleanup can never fail a run or mask a verdict: a removal that did not work becomes a
    /// sentence in the report, and the run continues.
    ///
    /// Returns [`None`] when the directory was removed, or was intentionally kept.
    pub fn discard_advisory(self) -> Option<String> {
        self.discard().err().map(|error| error.to_string())
    }

    /// Keep this workspace, because its cell did not pass, and return its path.
    ///
    /// The evidence-preservation ending. A failing cell — including one that exceeded its time
    /// budget, which is a divergence like any other rather than an infrastructure fault — leaves
    /// behind the program, both artifacts, every captured stream, the recorded termination
    /// statuses and the exact command lines.
    ///
    /// The path is returned so a report or a finding can name the directory it should send a
    /// maintainer to.
    pub fn retain(self) -> PathBuf {
        self.root
    }
}

/// Allocate the workspace for one cell of the build matrix.
///
/// # Errors
///
/// The identity is validated first, with the same rule [`Cell::new`] applies, so an area or
/// program name that is not a canonical corpus stem — empty, a relative directory name, a path
/// fragment, or text carrying a control character — is refused here. That rejection is the point:
/// the encoding used for a slug is injective and would happily turn a path fragment into one
/// safe directory name, so without this check a caller that built an identity out of the wrong
/// thing would get a working workspace under a name nobody could trace back to a cell.
///
/// Also fails if the derived name collides with one of [`RESERVED_ROOT_NAMES`], and if the
/// directory cannot be purged or created. A failure is always a hard error naming the path and
/// the cause, never a quietly skipped cell: a cell that did not run must be visible.
pub fn for_cell(key: &CellKey, config: &RunConfig) -> HarnessResult<Workspace> {
    key.validate_identity()?;

    let slug = key.slug();
    if RESERVED_ROOT_NAMES.contains(&slug.as_str()) {
        return Err(HarnessError::new(
            format!("allocating the workspace for {key}"),
            format!(
                "the derived directory name {slug:?} is reserved for the suite's own \
                 infrastructure workspaces; a cell and an infrastructure user sharing one \
                 directory would let two concurrent writers overwrite each other's artifacts"
            ),
        ));
    }

    allocate(&key.to_string(), workspace_path(key), config.keep_work())
}

/// Allocate the workspace for an already resolved [`Cell`], checking that both derivations
/// agree.
///
/// The preferred entry point wherever a resolved cell is at hand, because it is the one place
/// the suite can prove that the workspace path this module derives and the one carried by
/// [`Cell::workspace`] are the same directory.
///
/// # Errors
///
/// Fails if the two derivations disagree, naming both paths. Such a disagreement would not
/// announce itself otherwise: the compile step writes into the path its cell carries while the
/// execution step runs in the directory this module names, so the artifacts would simply fail to
/// appear where the next step looked for them, and the cell would fail for a reason that has
/// nothing to do with any compiler. Everything [`for_cell`] can reject is also rejected here.
pub fn for_resolved_cell(cell: &Cell, config: &RunConfig) -> HarnessResult<Workspace> {
    let derived = workspace_path(&cell.key);
    if cell.workspace != derived {
        return Err(HarnessError::new(
            format!("allocating the workspace for {}", cell.key),
            format!(
                "the cell carries the workspace {} while this module derives {}; both are built \
                 from the cell's identity and must be the same directory, because one step writes \
                 the artifacts and another runs in the directory that holds them",
                cell.workspace.display(),
                derived.display()
            ),
        ));
    }
    for_cell(&cell.key, config)
}

/// Allocate a workspace for one flag examined by the flag-capability probe.
///
/// The probe verifies command-line flags rather than corpus programs, so its workspaces are
/// keyed by the flag under examination and live together beneath [`FLAG_PROBE_ROOT_NAME`]. A
/// flag spelling is encoded exactly as a cell identity component is, so `-static` becomes one
/// safe, distinct directory name.
///
/// # Errors
///
/// Fails on a name [`encode_component`] rejects, and on a directory that cannot be purged or
/// created.
pub fn probe_workspace(name: &str, config: &RunConfig) -> HarnessResult<Workspace> {
    let component = encode_component("flag", name)?;
    let root = work_root().join(FLAG_PROBE_ROOT_NAME).join(component);
    let role = format!("the flag probe {:?}", sanitize_text_for_report(name));
    allocate(&role, root, config.keep_work())
}

/// Allocate a workspace for one undefined-behaviour audit gate applied to one program.
///
/// Every program passes through more than one gate — a strict warning gate and a sanitizer run —
/// and each gate compiles the program separately, so each needs a directory of its own. Keying
/// by feature area, program and gate keeps them distinct and keeps the tree readable, beneath
/// [`UB_AUDIT_ROOT_NAME`].
///
/// The audit is driven entirely by the reference compiler and renders no verdict about the
/// compiler under test: it establishes that a program is free of undefined behaviour, which is
/// the precondition that makes a divergence between two compilers mean anything at all.
///
/// # Errors
///
/// Fails on a component [`encode_component`] rejects, and on a directory that cannot be purged
/// or created.
pub fn audit_workspace(
    area: &str,
    program: &str,
    gate: &str,
    config: &RunConfig,
) -> HarnessResult<Workspace> {
    let area_component = encode_component("feature area", area)?;
    let program_component = encode_component("program", program)?;
    let gate_component = encode_component("audit gate", gate)?;
    let root = work_root()
        .join(UB_AUDIT_ROOT_NAME)
        .join(area_component)
        .join(program_component)
        .join(gate_component);
    let role = format!(
        "the {} audit gate of {}/{}",
        sanitize_text_for_report(gate),
        sanitize_text_for_report(area),
        sanitize_text_for_report(program)
    );
    allocate(&role, root, config.keep_work())
}
